### ISSUE TITLE
java.lang.IllegalStateException: Expected expression 'errType' to be a method invocation or field access, but was IDENTIFIER

### ISSUE THREAD

**Issue by dpursehouse** [google/error-prone#1072]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using? 

2.3.1
### Does this issue reproduce with the latest release?

2.3.1 is the latest release
### What did you do?

Check out the head of master on the gerrit project

```
bazel build --javacopt=-Xep:ExpectedExceptionChecker:ERROR //javatests/com/google/gerrit/acceptance/rest/project:rest_project.jar
```

### What did you expect to see?

The build completes, possibly with errors due to misuse of `ExpectedException`.

### What did you see instead?

Fails with `IllegalStateException`.

```
gerrit $ bazel build --javacopt=-Xep:ExpectedExceptionChecker:ERROR //javatests/com/google/gerrit/acceptance/rest/project:rest_project.jar
INFO: Analysed target //javatests/com/google/gerrit/acceptance/rest/project:rest_project.jar (0 packages loaded).
INFO: Found 1 target...
ERROR: /Users/dpursehouse/git/gerrit/javatests/com/google/gerrit/acceptance/rest/project/BUILD:3:1: Building javatests/com/google/gerrit/acceptance/rest/project/rest_project.jar (24 source files) and running annotation processors (AutoAnnotationProcessor, AutoValueProcessor) failed (Exit 1)
javatests/com/google/gerrit/acceptance/rest/project/CreateBranchIT.java:153: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
  private void assertCreateFails(
               ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.3.1
     BugPattern: ExpectedExceptionChecker
     Stack Trace:
     java.lang.IllegalStateException: Expected expression 'errType' to be a method invocation or field access, but was IDENTIFIER
  	at com.google.errorprone.util.ASTHelpers.getReceiver(ASTHelpers.java:454)
  	at com.google.errorprone.bugpatterns.AbstractExpectedExceptionChecker.buildBaseFix(AbstractExpectedExceptionChecker.java:159)
  	at com.google.errorprone.bugpatterns.ExpectedExceptionChecker.handleMatch(ExpectedExceptionChecker.java:61)
  	at com.google.errorprone.bugpatterns.AbstractExpectedExceptionChecker.scanBlock(AbstractExpectedExceptionChecker.java:123)
  	at com.google.errorprone.bugpatterns.AbstractExpectedExceptionChecker$1.visitBlock(AbstractExpectedExceptionChecker.java:93)
  	at com.google.errorprone.bugpatterns.AbstractExpectedExceptionChecker$1.visitBlock(AbstractExpectedExceptionChecker.java:90)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
  	at com.google.errorprone.bugpatterns.AbstractExpectedExceptionChecker.matchMethod(AbstractExpectedExceptionChecker.java:89)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:889)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:587)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:602)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:145)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:110)
  	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:112)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1363)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
  	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:110)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$2.invokeJavac(SimpleJavaLibraryBuilder.java:121)
  	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:54)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:124)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:132)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Target //javatests/com/google/gerrit/acceptance/rest/project:rest_project.jar failed to build
```

**Comment by dpursehouse** [comment]
This is the code it's failing on:

```
private void assertCreateFails(
      Branch.NameKey branch,
      String revision,
      Class<? extends RestApiException> errType,
      String errMsg)
      throws Exception {
    exception.expect(errType);
    if (errMsg != null) {
      exception.expectMessage(errMsg);
    }
    BranchInput in = new BranchInput();
    in.revision = revision;
    branch(branch).create(in);
  }
```

**Comment by dpursehouse** [comment]
Restructuring the code prevents the failure:

```
private void assertCreateFails(
      Branch.NameKey branch,
      String revision,
      Class<? extends RestApiException> errType,
      String errMsg)
      throws Exception {
    BranchInput in = new BranchInput();
    in.revision = revision;
    if (errMsg != null) {
      exception.expectMessage(errMsg);
    }
    exception.expect(errType);
    branch(branch).create(in);
  }
```
