### ISSUE TITLE
java.lang.NullPointerException in the BugPattern HidingField

### ISSUE THREAD

**Issue by jacobovazquez** [google/error-prone#1122]
### What version of Error Prone are you using?

2.3.1

### Does this issue reproduce with the latest release?

2.3.1 is the latest release

### What did you do?

Compile using the maven compiler plugin.

### What did you expect to see?

The build completes with no errors.

### What did you see instead?

Fails with a `NullPointerException`.

```
error-prone version: 2.3.1
BugPattern: HidingField
Stack Trace:
java.lang.NullPointerException
at com.sun.tools.javac.jvm.ClassReader.setParameters(ClassReader.java:2538)
at com.sun.tools.javac.jvm.ClassReader.readMethod(ClassReader.java:2436)
at com.sun.tools.javac.jvm.ClassReader.readClass(ClassReader.java:2710)
at com.sun.tools.javac.jvm.ClassReader.readClassBuffer(ClassReader.java:2775)
at com.sun.tools.javac.jvm.ClassReader.readClassFile(ClassReader.java:2788)
at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:348)
at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:285)
at com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1314)
at com.sun.tools.javac.code.Symbol$ClassSymbol.flags(Symbol.java:1248)
at com.sun.tools.javac.code.Symbol$TypeSymbol.getEnclosedElements(Symbol.java:800)
at com.google.errorprone.bugpatterns.HidingField.matchClass(HidingField.java:79)
at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:581)
at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:145)
at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:602)
at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:145)
at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
at com.sun.tools.javac.main.Main.compile(Main.java:302)
at com.sun.tools.javac.main.Main.compile(Main.java:162)
at com.sun.tools.javac.Main.compile(Main.java:57)
at com.sun.tools.javac.Main.main(Main.java:43)
```

**Comment by TheBigFatPanda1996** [comment]
Which Java class was this null pointer exception encountered ? If you're using eclipse, it should be mentioned along with the line number.

**Comment by cushon** [comment]
Please re-open if you're still seeing this or have an example that reproduce that reproduces the problem.
