### ISSUE TITLE
IncompleteAnnotationException: DoNotCall missing element value

### ISSUE THREAD

**Issue by dahlstrom-g** [google/error-prone#1131]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using?
2.3.1

### Does this issue reproduce with the latest release?
¯\\\_(ツ)\_/¯

### What did you do?
I ran a build with Bazel 0.16.1.

### What did you expect to see?
nothing

### What did you see instead?
```
Futures.addCallback(task, new FutureCallback<CaptureObject>() {
                   ^
Please report this at https://github.com/google/error-prone/issues/new and include the following:

error-prone version: 2.3.1
BugPattern: DoNotCall
Stack Trace:
java.lang.annotation.IncompleteAnnotationException: com.google.errorprone.annotations.DoNotCall missing element value
   at sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:81)
   at com.sun.proxy.$Proxy5.value(Unknown Source)
   at com.google.errorprone.bugpatterns.DoNotCallChecker.checkTree(DoNotCallChecker.java:118)
   at com.google.errorprone.bugpatterns.DoNotCallChecker.matchMethodInvocation(DoNotCallChecker.java:104)
   at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:904)
   at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:145)
   at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1644)
   at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
   at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:433)
   at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:710)
   at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:145)
   at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1454)
   at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
   at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
   at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
   at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
   at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:527)
   at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:145)
   at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
   at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
   at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
   at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
   at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:895)
   at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:145)
   at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
   at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
   at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
   at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
   at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
   at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
   at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:587)
   at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:145)
   at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
   at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
   at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
   at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
   at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
   at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:602)    
   at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:145)    
   at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
   at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
   at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43) 
   at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
   at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:110)
   at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:112)
   at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1363)
   at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)
   at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
   at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
   at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
   at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
   at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:110)
   at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$2.invokeJavac(SimpleJavaLibraryBuilder.java:122)
   at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:54)
   at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:125)
   at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:133)
   at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
   at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:50)
```

**Comment by cushon** [comment]
Thanks for the report. It's not immediately obvious to me how that happened, there haven't been any changes to the definition of `@DoNoCall` and it shouldn't be missing `value`.

Any chance you can send me a repro?

(tip: escape shruggie as `¯\\\_(ツ)\_/¯` for best results)

**Comment by cushon** [comment]
The error that should have been reported (instead of the crash) was:

```java
.../CaptureObjectLoader.java:45: error: [DoNotCall] This method should not be called, see its documentation for details.
    Futures.addCallback(task, new FutureCallback<CaptureObject>() {
                       ^
```

The annotation was added to `Futures.addCallback` in https://github.com/google/guava/commit/49a1df62b9a8a5e96f4f32a6bad4afd9cd871b56#diff-5c3f56c125a86c8adde4e8754f104468, and the method was removed from more recent versions of guava: https://github.com/google/guava/commit/87d87f5cac5a540d46a6382683722ead7b72d1b3#diff-5c3f56c125a86c8adde4e8754f104468

The issue here is that there was a dependency on guava, but no dependency on the Error Prone annotations package, which guava depends on. Adding the missing dependency fixes the crash.
