### ISSUE TITLE
NullPointerException in NullableDereference

### ISSUE THREAD

**Issue by mattnworb** [google/error-prone#1151]
### What version of Error Prone are you using?
2.3.2

### What did you do?
With errorprone set up via `-Xplugin`, use Maven to compile [this class](https://github.com/spotify/helios/blob/2ec8895944067306e04e225f207a5b1971902a11/helios-client/src/main/java/com/spotify/helios/common/descriptors/Descriptor.java):

```java
package com.spotify.helios.common.descriptors;

import static java.nio.charset.StandardCharsets.UTF_8;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.spotify.helios.common.Json;
import java.io.IOException;

public abstract class Descriptor {

  public String toJsonString() {
    return Json.asStringUnchecked(this);
  }

  public byte[] toJsonBytes() {
    try {
      return Json.asBytes(this);
    } catch (JsonProcessingException e) {
      throw new RuntimeException(e);
    }
  }

  public static <T extends Descriptor> T parse(final byte[] bytes, Class<T> clazz)
      throws IOException {
    return Json.read(bytes, clazz);
  }

  public static <T extends Descriptor> T parse(final String value, Class<T> clazz)
      throws IOException {
    return parse(value.getBytes(UTF_8), clazz);
  }
}
```

The error from error-prone is (line 23 is the line `import static java.nio.charset.StandardCharsets.UTF_8`, if the line/column number in the error is to be trusted):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project helios-client: Compilation failure
[ERROR] /Users/mattbrown/code/helios/helios-client/src/main/java/com/spotify/helios/common/descriptors/Descriptor.java:[23,47] error: An unhandled exception was thrown by the Error Prone static analysis plugin.
[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:


error-prone version: 2.3.2
BugPattern: NullableDereference
Stack Trace:
java.lang.NullPointerException
   at com.google.errorprone.bugpatterns.nullness.NullableDereference.matchMemberSelect(NullableDereference.java:64)
   at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:870)
   at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:146)
   at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2112)
   at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:83)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
   at com.sun.source.util.TreeScanner.visitImport(TreeScanner.java:171)
   at com.google.errorprone.scanner.ErrorProneScanner.visitImport(ErrorProneScanner.java:771)
   at com.google.errorprone.scanner.ErrorProneScanner.visitImport(ErrorProneScanner.java:146)
   at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:660)
   at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:83)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
   at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
   at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
   at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:143)
   at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:603)
   at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
   at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
   at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
   at com.google.errorprone.scanner.Scanner.scan(Scanner.java:65)
   at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
   at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:151)
   at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
   at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
   at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
   at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
   at com.sun.tools.javac.main.Main.compile(Main.java:302)
   at com.sun.tools.javac.main.Main.compile(Main.java:162)
   at com.sun.tools.javac.Main.compile(Main.java:57)
   at com.sun.tools.javac.Main.main(Main.java:43)
```

my Maven configuration:

```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.8.0</version>
                    <configuration>
                        <source>1.8</source>
                        <target>1.8</target>
                        <compilerArgs>
                            <arg>-XDcompilePolicy=simple</arg>
                            <arg>-Xplugin:ErrorProne -XepAllDisabledChecksAsWarnings</arg>
                            <arg>-Xlint:cast</arg>
                            <arg>-Xlint:divzero</arg>
                            <arg>-Xlint:empty</arg>
                            <arg>-Xlint:fallthrough</arg>
                            <arg>-Xlint:finally</arg>
                            <arg>-Xlint:overrides</arg>
                            <arg>-Xlint:path</arg>
                            <arg>-Xlint:unchecked</arg>
                            <arg>-Xlint:-options</arg>
                        </compilerArgs>
                        <annotationProcessorPaths>
                            <path>
                                <groupId>com.google.errorprone</groupId>
                                <artifactId>error_prone_core</artifactId>
                                <version>2.3.2</version>
                            </path>
                        </annotationProcessorPaths>
                    </configuration>
                </plugin>
```

**Comment by tbroyer** [comment]
Looks like a duplicate of #1138

**Comment by mattnworb** [comment]
@tbroyer yes it is, thanks - sorry I did not check before posting
