### ISSUE TITLE
NullableDereference NPE

### ISSUE THREAD

**Issue by dietervdw-spotify** [google/error-prone#1168]
Please answer these questions before submitting your issue. Thanks!

### What version of Error Prone are you using?
2.3.2

### Does this issue reproduce with the latest release?
2.3.2 is the latest I assume?

### What did you do?

Just `mvn clean install` on my codebase.

### What did you expect to see?
No errors :) .

### What did you see instead?

```
`[ERROR]      error-prone version: 2.3.2
[ERROR]      BugPattern: NullableDereference
[ERROR]      Stack Trace:
[ERROR]      java.lang.NullPointerException
[ERROR]   	at com.google.errorprone.bugpatterns.nullness.NullableDereference.matchMemberSelect(NullableDereference.java:64)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:870)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2112)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:83)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
[ERROR]   	at com.sun.source.util.TreeScanner.visitImport(TreeScanner.java:171)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitImport(ErrorProneScanner.java:771)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitImport(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:660)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:83)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:143)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:603)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:65)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
[ERROR]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:151)
[ERROR]   	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:952)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
[ERROR]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:143)
[ERROR]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:114)
[ERROR]   	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:121)
[ERROR]   	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:223)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]   	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]   	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
[ERROR]   	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:943)
[ERROR]   	at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:164)
[ERROR]   	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]   	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]   	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]   	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]   	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]   	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]   	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]   	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]   	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]   	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]   	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]   	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]   	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]   	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]   	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]   	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)`
```

**Comment by cushon** [comment]
Thanks for the report. Do you have a self-contained example that reproduces the crash?
