### ISSUE TITLE
Symbol$CompletionFailure with ModifiedButNotUsed

### ISSUE THREAD

**Issue by AlexLandau** [google/error-prone#1222]
I'm encountering a problem with `ModifiedButNotUsed` in 2.3.2. It fails with a Symbol$CompletionFailure unless I disable that check or add a particular transitive dependency to the list of immediate dependencies for the project in Gradle. It looks similar to the issue encountered in #1080 and elsewhere, but with a different check causing the issue. Message and stacktrace are as follows:

```
error: cannot access InterfaceName
  class file for com.example.InterfaceName not found
  Consult the following stack trace for details.
  com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.example.InterfaceName not found
  	at com.sun.tools.javac.code.ClassFinder.newCompletionFailure(ClassFinder.java:381)
  	at com.sun.tools.javac.code.ClassFinder.classFileNotFound(ClassFinder.java:369)
  	at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:362)
  	at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:285)
  	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:633)
  	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1314)
  	at com.sun.tools.javac.code.Symbol$ClassSymbol.getSuperclass(Symbol.java:1340)
  	at com.sun.tools.javac.code.Types$15.visitClassType(Types.java:2236)
  	at com.sun.tools.javac.code.Types$15.visitClassType(Types.java:2225)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:992)
  	at com.sun.tools.javac.code.Types$UnaryVisitor.visit(Types.java:4703)
  	at com.sun.tools.javac.code.Types.supertype(Types.java:2222)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1888)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1877)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:992)
  	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4623)
  	at com.sun.tools.javac.code.Types.asSuper(Types.java:1874)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1897)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1877)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:992)
  	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4623)
  	at com.sun.tools.javac.code.Types.asSuper(Types.java:1874)
  	at com.sun.tools.javac.code.Types$4.visitClassType(Types.java:868)
  	at com.sun.tools.javac.code.Types$4.visitClassType(Types.java:789)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:992)
  	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4623)
  	at com.sun.tools.javac.code.Types.isSubtype(Types.java:785)
  	at com.sun.tools.javac.code.Types.isSubtype(Types.java:756)
  	at com.google.errorprone.util.ASTHelpers.isSubtype(ASTHelpers.java:921)
  	at com.google.errorprone.matchers.IsSubtypeOf.matches(IsSubtypeOf.java:40)
  	at com.google.errorprone.matchers.Matchers$5.matches(Matchers.java:156)
  	at com.google.errorprone.bugpatterns.ModifiedButNotUsed.matchVariable(ModifiedButNotUsed.java:229)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:1148)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:968)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:83)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:203)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:896)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:83)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:588)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:83)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:603)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:65)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:151)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
  	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
  	at org.gradle.api.internal.tasks.compile.AnnotationProcessingCompileTask.call(AnnotationProcessingCompileTask.java:89)
  	at org.gradle.api.internal.tasks.compile.ResourceCleaningCompilationTask.call(ResourceCleaningCompilationTask.java:57)
  	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
  	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
  	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:86)
  	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerCallable.call(AbstractDaemonCompiler.java:74)
  	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:42)
  	at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:36)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:102)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
  	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
  	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
  	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
  	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
  	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
  	at java.lang.Thread.run(Thread.java:748)
```

Fake name used due to an abundance of caution around a proprietary codebase; the actual interface named is part of a dependency that is on the classpath transitively. It does not extend anything.

(Note to anyone else who encountered an error like this but didn't get a stacktrace: you need to pass a compiler flag `-XDdev`; see [this comment](https://github.com/google/error-prone/issues/441#issuecomment-235432756).)

Environment information:
* ErrorProne version is 2.3.2
* Run using the Gradle plugin, version 0.6.1
* Javac version is `com.google.errorprone:javac:9+181-r4173-1`

**Comment by tbroyer** [comment]
Could it be that the dependency is declared as `implementation` (rather than `api`) and therefore not added transitively to the compile classpath (but only the runtime classpath) ?

**Comment by AlexLandau** [comment]
No, the dependency is external to the repository and brought in through Maven. The POM of the immediate dependency declares the "missing" dependency with runtime scope. And the codebase and dependency are all in Java 8 or lower and using classpaths rather than modulepaths.

**Comment by tbroyer** [comment]
Well, that's equivalent: with runtime scope, the dependency is not in the compile classpath.

**Comment by AlexLandau** [comment]
Oof... the Gradle build of the dependency is absolutely standard-looking and declares them as compile dependencies, so I didn't bother to double-check the maven scope meanings. That does look like a problem on our end; thanks for the help.

**Comment by AlexLandau** [comment]
(I'll note, though, that this never caused any issues with compilation, and this error did not come up in previous versions of ErrorProne.)
