### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin.

### ISSUE THREAD

**Issue by fanminshi** [google/error-prone#1247]
### Description of the problem / feature request:

```
 Compilation failure
[ERROR] /Users/fanminshi/work/src/github.com/fanminshi/jetcd/jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/EtcdClusterFactory.java:[19,1] An unhandled exception was thrown by the Error Prone static analysis plugin.

[ERROR]      error-prone version: 2.3.3
[ERROR]      BugPattern: BadImport
[ERROR]      Stack Trace:
[ERROR]      java.lang.BootstrapMethodError: call site initialization exception
[ERROR]   	at java.lang.invoke.CallSite.makeSite(CallSite.java:341)
[ERROR]   	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
[ERROR]   	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
[ERROR]   	at com.google.errorprone.bugpatterns.BadImport.isAcceptableImport(BadImport.java:134)
[ERROR]   	at com.google.errorprone.bugpatterns.BadImport.matchImport(BadImport.java:98)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner$$Lambda$308/304504964.process(Unknown Source)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:433)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitImport(ErrorProneScanner.java:646)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitImport(ErrorProneScanner.java:150)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCImport.accept(JCTree.java:660)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:143)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:546)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:55)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
[ERROR]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:151)
[ERROR]   	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:952)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl$$Lambda$71/2009492047.call(Unknown Source)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
[ERROR]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:143)
[ERROR]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:114)
[ERROR]   	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:121)
[ERROR]   	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:223)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]   	at java.lang.reflect.Method.invoke(Method.java:497)
[ERROR]   	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
[ERROR]   	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
[ERROR]   	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
[ERROR]   	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]   	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]   	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]   	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]   	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]   	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]   	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]   	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]   	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]   	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
[ERROR]   	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]   	at java.lang.reflect.Method.invoke(Method.java:497)
[ERROR]   	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]   	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]   	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]   	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]   	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]   	at java.lang.reflect.Method.invoke(Method.java:497)
[ERROR]   	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
[ERROR]   	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
[ERROR]   	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:55)
[ERROR]   Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type interface javax.lang.model.element.Name; not a subtype of implementation type interface javax.lang.model.element.Name
[ERROR]   	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:233)
[ERROR]   	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)
[ERROR]   	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
[ERROR]   	... 71 more
[ERROR]
[ERROR] -> [Help 1]
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

We encounter this issue when compiling https://github.com/etcd-io/jetcd. The easiest way to reproduce this is download the jetcd project and run:
```
./mvnw clean install -DskipTests
```
Then you will see the above error.

Specially it complains about this import 

```java
import static java.util.stream.Collectors.toList;
```

from https://github.com/etcd-io/jetcd/blob/master/jetcd-launcher/src/main/java/io/etcd/jetcd/launcher/EtcdClusterFactory.java#L19 

### What version of Error Prone are you using?

error-prone version: 2.3.3

###  Have you found anything relevant by searching the web?

https://github.com/google/error-prone/issues/684
But it has no answer

**Comment by tbroyer** [comment]
Try using ErrorProne as `-Xplugin:ErrorProne` rather than through the plexus compiler.

**Comment by vorburger** [comment]
> Try using ErrorProne as -Xplugin:ErrorProne rather than through the plexus compiler.

@fanminshi just FYI what @tbroyer means here is what was done e.g. in https://git.opendaylight.org/gerrit/#/c/79211/10/common/parent/pom.xml, just in case you (or anyone else) would like to replace the use of `plexus-compiler-javac-errorprone` (which shouldn't be required anymore, see #1242) e.g. in https://github.com/etcd-io/jetcd/issues/526 (or other projects like it).
