### ISSUE TITLE
Compile error: NoSuchMethodError checkArgument

### ISSUE THREAD

**Issue by reitzmichnicht** [google/error-prone#1251]
### Description of the problem / feature request:

When compiling a maven module with error prone the following compiler error occurs
```
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ dlm-filemaker-service ---
[INFO] Compiling 16 source files to C:\Dev\dlm\dlm-filemaker-service\target\classes
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.2, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.google.errorprone.BugCheckerInfo.create(BugCheckerInfo.java:95)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:420)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:413)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.<clinit>(BuiltInCheckerSuppliers.java:449)
	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:44)
	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:215)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:199)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] An unknown compilation problem occurred
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

I'm not yet sure what change leads to the error

### What version of Error Prone are you using?

OpenJDK 11.0.2 on Windows with the following error prone configuration:
```
<plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
              <compilerArgs combine.children="append">
                <arg>-XDcompilePolicy=simple</arg>
                <arg>-Xplugin:ErrorProne</arg>
              </compilerArgs>
              <annotationProcessorPaths>
                <path>
                  <groupId>com.google.errorprone</groupId>
                  <artifactId>error_prone_core</artifactId>
                  <version>2.3.3</version>
                </path>
              </annotationProcessorPaths>
            </configuration>
          </plugin>
```

###  Have you found anything relevant by searching the web?

No

**Comment by tbroyer** [comment]
That signature of `checkArgument` was added in Guava 20.0. Could it be that Maven somehow leaks such an old version of Guava to the processor path (unlikely but who knows?) Do you have other dependencies in the processor path that could possibly bring `com.google.common.base.Preconditions`? (in a way that Maven's dependency management couldn't detect the conflict)

**Comment by reitzmichnicht** [comment]
Yes we have other things in the processor path, like mapstruct. I had also the suspicion about guava version conflict, but could not find any problem. How could I debug the maven internal dependency tree?
I was wondering why the signature checkArgument(ZLjava/lang/String;Ljava/lang/Object;) is used, because the code of BugCheckerInfo uses checkArgument with 3 parameters.

**Comment by tbroyer** [comment]
> How could I debug the maven internal dependency tree?

I have no idea, might not even be possible.
I would dig into `mvn -X` output. At a minimum you'll have the `-processorpath` compiler argument and could check the content for each JAR.

> I was wondering why the signature checkArgument(ZLjava/lang/String;Ljava/lang/Object;) is used, because the code of BugCheckerInfo uses checkArgument with 3 parameters.

Yup, 3 arguments: boolean (`Z`), String (`Ljava/lang/String;`), and Object (`Ljava/lang/Object;`).

**Comment by reitzmichnicht** [comment]
Ok it is the mapstruct-processor which has a test dependency to guava 19.
Because we need the generated mappers in the test code, we had to register the processor directly in the compiler, not as dependency as usual:
```
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <configuration>
            <annotationProcessorPaths combine.children="append">
              <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${version.mapstruct}</version>
              </path>
            </annotationProcessorPaths>
          </configuration>
        </plugin>
      </plugins>
    </pluginManagement>
```

error-prone configuration in parent pom was not part of pluginManagement, but of normal build plugins and then mapstruct-processor seems to get more weight in dependency resolution. Defining both in pluginManagement section seems to work.

Thanks for your help
