### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin.

### ISSUE THREAD

**Issue by josephkim583** [google/error-prone#1345]
for (NameValueReferable<T> fact : facts) {
    ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.3.1.3-uber
     BugPattern: NullAway
     Stack Trace:
     com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
  	at com.google.common.cache.LocalCache.get(LocalCache.java:3952)
  	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4964)
  	at com.uber.nullaway.dataflow.DataFlow.dataflow(DataFlow.java:143)
  	at com.uber.nullaway.dataflow.DataFlow.resultFor(DataFlow.java:251)
  	at com.uber.nullaway.dataflow.DataFlow.resultForExpr(DataFlow.java:228)
  	at com.uber.nullaway.dataflow.DataFlow.expressionDataflow(DataFlow.java:173)
  	at com.uber.nullaway.dataflow.AccessPathNullnessAnalysis.getNullness(AccessPathNullnessAnalysis.java:90)
  	at com.uber.nullaway.NullAway.nullnessFromDataflow(NullAway.java:1939)
  	at com.uber.nullaway.NullAway.mayBeNullExpr(NullAway.java:1907)
  	at com.uber.nullaway.NullAway.matchEnhancedForLoop(NullAway.java:1231)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitEnhancedForLoop(ErrorProneScanner.java:705)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitEnhancedForLoop(ErrorProneScanner.java:147)
  	at com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1166)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:533)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:147)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:913)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:147)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:593)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:147)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:608)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:147)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:952)
  	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
  	at com.facebook.buck.jvm.java.plugin.adapter.JavacTaskWrapper.call(JavacTaskWrapper.java:100)
  	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTask.call(BuckJavacTask.java:52)
  	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTaskProxyImpl.call(BuckJavacTaskProxyImpl.java:134)
  	at com.facebook.buck.jvm.java.Jsr199JavacInvocation$CompilerWorker.lambda$startCompiler$2(Jsr199JavacInvocation.java:422)
  	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
  	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
  	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  	at java.lang.Thread.run(Thread.java:748)
  Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
  	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
  	at java.util.ArrayList.get(ArrayList.java:433)
  	at com.uber.nullaway.dataflow.AccessPathNullnessPropagation.setNullnessForMapCalls(AccessPathNullnessPropagation.java:892)
  	at com.uber.nullaway.dataflow.AccessPathNullnessPropagation.visitMethodInvocation(AccessPathNullnessPropagation.java:857)
  	at com.uber.nullaway.dataflow.AccessPathNullnessPropagation.visitMethodInvocation(AccessPathNullnessPropagation.java:138)
  	at shadow.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:76)
  	at shadow.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:408)
  	at shadow.checkerframework.dataflow.analysis.Analysis.performAnalysisBlock(Analysis.java:234)
  	at shadow.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:187)
  	at com.uber.nullaway.dataflow.DataFlow$1.load(DataFlow.java:85)
  	at com.uber.nullaway.dataflow.DataFlow$1.load(DataFlow.java:76)
  	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3528)
  	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2277)
  	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
  	... 73 more

**Comment by eaftan** [comment]
This looks like a NullAway bug, please file it there: https://github.com/uber/NullAway/issues

**Comment by RainbowTraveller** [comment]
I this fixed ? I am getting similar one here 
![image](https://user-images.githubusercontent.com/10987129/95246411-4c02b980-07c9-11eb-83cd-d9ac09927c00.png)

**Comment by lazaroclapp** [comment]
@RainbowTraveller Is this on one of the upstream Error Prone checkers or is that an Uber checker (e.g.  https://github.com/uber/NullAway ). In the later case, you can ping me internally and we can take a look before filing an EP issue. If it's an issue while running NullAway, even if it happens within EP code, it should not be reported here first.

**Comment by RainbowTraveller** [comment]
Talked to @lazaroclapp offline. Issue is not related to error-prone.
