### ISSUE TITLE
Fails with java13

### ISSUE THREAD

**Issue by davidkarlsen** [google/error-prone#1353]
```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure

/data/jenkins/workspace/-server_feature_java13-temp-RDQKHHU4ZDO7CEXADE6ITPPGYX6OUARH6FJO5WIIOVJSPHLPCGTQ/jfr-srv-service/src/test/java/com/edb/fs/tac/jfr/srv/service/account/CorsAccountServiceTest.java:[93,48] error: An unhandled exception was thrown by the Error Prone static analysis plugin.

     Please report this at https://github.com/google/error-prone/issues/new and include the following:

  

     error-prone version: 2.3.3

     BugPattern: JavaTimeDefaultTimeZone

     Stack Trace:

     java.lang.LinkageError: com.sun.tools.javac.comp.Resolve.findIdent(com.sun.tools.javac.comp.Env,com.sun.tools.javac.util.Name,com.sun.tools.javac.code.Kinds$KindSelector)

  	at com.google.errorprone.util.FindIdentifiers.findIdent(FindIdentifiers.java:104)

  	at com.google.errorprone.fixes.SuggestedFixes.qualifyType(SuggestedFixes.java:337)

  	at com.google.errorprone.bugpatterns.time.JavaTimeDefaultTimeZone.matchMethodInvocation(JavaTimeDefaultTimeZone.java:119)

  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:433)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:732)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1753)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:535)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:737)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1753)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMemberSelect(TreeScanner.java:706)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:714)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2225)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:534)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:737)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1753)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMemberSelect(TreeScanner.java:706)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:714)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2225)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:534)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:737)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1753)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:224)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:871)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:984)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:249)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:507)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1042)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:207)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:726)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:908)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:535)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:818)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)

  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)

  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:546)

  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)

  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:601)

  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)

  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:55)

  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)

  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:151)

  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)

  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1423)

  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1370)

  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:959)

  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:318)

  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)

  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:75)

  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

  	at java.base/java.lang.reflect.Method.invoke(Method.java:567)

  	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess0(JavacCompiler.java:626)

  	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcessWithProperClassloader(JavacCompiler.java:607)

  	at org.codehaus.plexus.compiler.javac.JavacCompiler.compileInProcess(JavacCompiler.java:596)

  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:178)

  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)

  	at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:180)

  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)

  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)

  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)

  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)

  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)

  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:190)

  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:186)

  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)

  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

  	at java.base/java.lang.Thread.run(Thread.java:830)

  Caused by: java.lang.NoSuchMethodException: com.sun.tools.javac.comp.Resolve.findIdent(com.sun.tools.javac.comp.Env,com.sun.tools.javac.util.Name,com.sun.tools.javac.code.Kinds$KindSelector)

  	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2476)

  	at com.google.errorprone.util.FindIdentifiers.findIdent(FindIdentifiers.java:98)

  	... 122 more



    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)

    at org.apache.maven.plugin.compiler.TestCompilerMojo.execute (TestCompilerMojo.java:180)

    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)

    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)

    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)

    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:190)

    at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call (MultiThreadedBuilder.java:186)

    at java.util.concurrent.FutureTask.run (FutureTask.java:264)

    at java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:515)

    at java.util.concurrent.FutureTask.run (FutureTask.java:264)

    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)

    at java.util.concurrent.ThreadPoolExecutor```

**Comment by davidkarlsen** [comment]
related https://github.com/google/error-prone/issues/1106
