### ISSUE TITLE
Unhandled exception when running with Checker Framework

### ISSUE THREAD

**Issue by eikemeier** [google/error-prone#1575]
### Description of the problem:

Trying to compile https://github.com/melsicon/kafka-sensors/tree/02c94d69f9b986c6987313185ec419c82b9c5c9e with `bazel build //...` results in:

```
ERROR: kafka-sensors/src/main/java/de/melsicon/kafka/sensors/serdes/BUILD:3:1: Building src/main/java/de/melsicon/kafka/sensors/serdes/libserdes.jar (2 source files) and running annotation processors (NullnessChecker) failed (Exit 1)
src/main/java/de/melsicon/kafka/sensors/serdes/SerDes.java:53: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    return serdeFactory.createSensorStateWithDurationSerde();
    ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.3.2-SNAPSHOT
     BugPattern: ReturnMissingNullable
     Stack Trace:
     com.google.common.util.concurrent.ExecutionError: java.lang.AssertionError: ENUM_CONSTANT
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2048)
  	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
  	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
  	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
  	at com.google.errorprone.dataflow.DataFlow.methodDataflow(DataFlow.java:173)
  	at com.google.errorprone.dataflow.DataFlow.expressionDataflow(DataFlow.java:226)
  	at com.google.errorprone.dataflow.nullnesspropagation.TrustingNullnessAnalysis.getNullness(TrustingNullnessAnalysis.java:79)
  	at com.google.errorprone.bugpatterns.nullness.ReturnMissingNullable.matchReturn(ReturnMissingNullable.java:79)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:1013)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:146)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1554)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:528)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1032)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:896)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:146)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:588)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:603)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:169)
  	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:115)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1375)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:114)
  	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:57)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:116)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:123)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:106)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:68)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:46)
  Caused by: java.lang.AssertionError: ENUM_CONSTANT
  	at com.google.errorprone.util.MoreAnnotations.isAnnotationOnType(MoreAnnotations.java:81)
  	at com.google.errorprone.util.MoreAnnotations.lambda$getDeclarationAndTypeAttributes$0(MoreAnnotations.java:58)
  	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
  	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
  	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
  	at com.google.common.collect.CollectSpliterators$1FlatMapSpliterator.lambda$forEachRemaining$1(CollectSpliterators.java:247)
  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
  	at com.google.common.collect.CollectSpliterators$1FlatMapSpliterator.forEachRemaining(CollectSpliterators.java:247)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base/java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:558)
  	at com.google.errorprone.dataflow.nullnesspropagation.Nullness.fromAnnotationStream(Nullness.java:140)
  	at com.google.errorprone.dataflow.nullnesspropagation.Nullness.fromAnnotationsOn(Nullness.java:148)
  	at com.google.errorprone.dataflow.nullnesspropagation.TrustingNullnessPropagation.fieldNullness(TrustingNullnessPropagation.java:70)
  	at com.google.errorprone.dataflow.nullnesspropagation.NullnessPropagationTransfer.visitFieldAccess(NullnessPropagationTransfer.java:551)
  	at com.google.errorprone.dataflow.nullnesspropagation.AbstractNullnessPropagationTransfer.visitFieldAccess(AbstractNullnessPropagationTransfer.java:288)
  	at com.google.errorprone.dataflow.nullnesspropagation.AbstractNullnessPropagationTransfer.visitFieldAccess(AbstractNullnessPropagationTransfer.java:128)
  	at org.checkerframework.dataflow.cfg.node.FieldAccessNode.accept(FieldAccessNode.java:71)
  	at org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:408)
  	at org.checkerframework.dataflow.analysis.Analysis.performAnalysisBlock(Analysis.java:210)
  	at org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:187)
  	at com.google.errorprone.dataflow.DataFlow$1.load(DataFlow.java:85)
  	at com.google.errorprone.dataflow.DataFlow$1.load(DataFlow.java:76)
  	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
  	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
  	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
  	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
  	... 66 more
```
### Feature requests: what underlying problem are you trying to solve with this feature?

Running Error Prone with the Checker Framework

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

Check out https://github.com/melsicon/kafka-sensors/tree/02c94d69f9b986c6987313185ec419c82b9c5c9e and run `bazel build //...`

### What version of Error Prone are you using?

2.3.2-SNAPSHOT (from Bazel 3.0.0)

**Comment by cushon** [comment]
The check that is crashing has been removed: https://github.com/google/error-prone/commit/c8c034d99b48df0034aad64ea777b480f6c3cbf9
