### ISSUE TITLE
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.6, {1}, {2}, {3}, {4}, {5}, {6}, {7} java.lang.NoClassDefFoundError: com/google/common/collect/Streams

### ISSUE THREAD

**Issue by venth** [google/error-prone#1584]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

Compilation of the sources fails with the message as follows:
```
compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.6, {1}, {2}, {3}, {4}, {5}, {6}, {7}
java.lang.NoClassDefFoundError: com/google/common/collect/Streams
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:452)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.getSuppliers(BuiltInCheckerSuppliers.java:447)
	at com.google.errorprone.scanner.BuiltInCheckerSuppliers.<clinit>(BuiltInCheckerSuppliers.java:481)
	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:44)
	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:215)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.prepareCompiler(JavacTaskImpl.java:199)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:101)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Streams
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 43 more
```

The project is build with maven 3.6.3 and openjdk 11.

The configuration of the maven-compiler-plugin looks as follows:
```xml
<plugin>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <encoding>${project.build.sourceEncoding}</encoding>
        <release>${java.version}</release>
        <source>${java.version}</source>
        <target>${java.version}</target>
        <parameters>true</parameters>
        <annotationProcessorPaths>
            <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
            </path>
            <path>
                <artifactId>lombok</artifactId>
                <groupId>org.projectlombok</groupId>
                <version>${lombok.version}</version>
            </path>
            <path>
                <groupId>com.google.errorprone</groupId>
                <artifactId>error_prone_core</artifactId>
                <version>${error_prone.version}</version>
            </path>
            <path>
                <groupId>com.uber.nullaway</groupId>
                <artifactId>nullaway</artifactId>
                <version>${nullaway.version}</version>
            </path>
            <path>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-configuration-processor</artifactId>
                <version>${project.parent.version}</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
    <executions>
        <execution>
            <configuration>
                <compilerArgs>
                    <arg>-Xlint:all,-options</arg>
                    <arg>-Xdoclint:all/protected</arg>
                    <arg>-XDcompilePolicy=simple</arg>
                    <arg>
                        -Xplugin:ErrorProne
                        -Xep:NullAway:ERROR
                        -XepOpt:NullAway:AnnotatedPackages=x.y.z
                        -XepOpt:NullAway:ExcludedClassAnnotations=org.springframework.boot.context.properties.ConfigurationProperties
                    </arg>
                </compilerArgs>
            </configuration>
            <id>default-compile</id>
            <phase>compile</phase>
        </execution>
        <execution>
            <configuration>
                <compilerArgs>
                    <arg>-Xlint:all,-options,-deprecation</arg>
                    <arg>-Xdoclint:none</arg>
                    <arg>-XDcompilePolicy=simple</arg>
                </compilerArgs>
            </configuration>
            <id>default-testCompile</id>
            <phase>test-compile</phase>
        </execution>
    </executions>
</plugin>
```

When `mapstruct-processor` is removed from `annotationProcessorPaths` the compilation process ends up with a success.

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

compile project using versions as follows:
* error_prone - 2.3.4
* nullaway - 0.7.9
* mapstruct - 1.3.1.Final

### What version of Error Prone are you using?

error_prone - 2.3.4

###  Have you found anything relevant by searching the web?

The issue which looks relevant: 
* [Compile error: NoSuchMethodError checkArgument](https://github.com/google/error-prone/issues/1251)

**Comment by tbroyer** [comment]
You probably have a Maven dependency resolution issue, where another entry in annotationProcessorPaths has a dependency on an old version of Guava and Maven choses it rather than the one from ErrorProne.
See http://andresalmiray.com/maven-dependencies-pop-quiz-results/
As a workaround, you can explicitly declare Guava in annotationProcessorPaths (and hope that it won't break the other processor, because a Guava without Streams is quite old already, and might predate the new release guarantees that they don't break backwards compatibility for non-Beta APIs)

**Comment by venth** [comment]
Thanks for the answer. I’ve already identified the `annotationProcessorPaths` entry causing troubles it’s `mapstruct-processor`. As you advised I’ll put guava in `annotationProcessorPaths` and see what will happen 😀

**Comment by venth** [comment]
Providing additional dependencies in the `annotationProcessorPaths` section worked. I ended up with configuration as follows:
```
<annotationProcessorPaths>
    <!-- these dependencies are to resolve conflict between error-prone and mapstruct -->
    <path>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>${guava.version}</version>
    </path>
    <path>
        <groupId>com.google.code.findbugs</groupId>
        <artifactId>jFormatString</artifactId>
        <version>${findbugs.version}</version>
    </path>
    <!-- -->
    <path>
        <artifactId>lombok</artifactId>
        <groupId>org.projectlombok</groupId>
        <version>${lombok.version}</version>
    </path>
    <path>
        <groupId>com.google.errorprone</groupId>
        <artifactId>error_prone_core</artifactId>
        <version>${error_prone.version}</version>
    </path>
    <path>
        <groupId>com.uber.nullaway</groupId>
        <artifactId>nullaway</artifactId>
        <version>${nullaway.version}</version>
    </path>
    <path>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-configuration-processor</artifactId>
        <version>${project.parent.version}</version>
    </path>
</annotationProcessorPaths>
```

**Comment by venth** [comment]
I close the issue. Thanks for the workaround 😀
