### ISSUE TITLE
NullableDereference causes UncheckedExecutionException

### ISSUE THREAD

**Issue by shevek** [google/error-prone#1617]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

NullableDereference causes UncheckedExecutionException. See below for stack.

### Feature requests: what underlying problem are you trying to solve with this feature?

Compile my code

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

No idea.

### What version of Error Prone are you using?

2.3.3

###  Have you found anything relevant by searching the web?

No

```

error: An unhandled exception was thrown by the Error Prone static analysis plugin. 
        out.add(new MyFacade(key, value));


public List<MyFacade> getMyFacadeList() {
    EnumMap<? extends MyEnum ? extends Long> data = new BusinessCalculation(...).getResult();
    List<MyFacade> out = new ArrayList<>();
    data.forEach((key, value) -> {
        if (value > 0)
            out.add(new MyFacade(key, value)); // here
    });
    return out;
}


     error-prone version: 2.3.3
     BugPattern: NullableDereference
     Stack Trace:
     com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Not a primitive type: NONE
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4966)
        at com.google.errorprone.dataflow.DataFlow.methodDataflow(DataFlow.java:168)
        at com.google.errorprone.dataflow.DataFlow.expressionDataflow(DataFlow.java:227)
        at com.google.errorprone.dataflow.nullnesspropagation.TrustingNullnessAnalysis.getNullness(TrustingNullnessAnalysis.java:79)
        at com.google.errorprone.bugpatterns.nullness.NullableDereference.checkExpression(NullableDereference.java:157)
        at com.google.errorprone.bugpatterns.nullness.NullableDereference.matchMemberSelect(NullableDereference.java:81)
        at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:433)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:712)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:150)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2112)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
        at com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:508)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:737)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1644)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:433)
        at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:619)
        at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:150)
        at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1454)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
        at com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:419)
        at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:640)
        at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:150)
        at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1427)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:71)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
        at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:507)
[trim N uninteresting lines]
  Caused by: java.lang.IllegalArgumentException: Not a primitive type: NONE
        at com.sun.tools.javac.model.JavacTypes.getPrimitiveType(JavacTypes.java:170)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.binaryPromotedType(CFGBuilder.java:2059)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBinary(CFGBuilder.java:3109)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBinary(CFGBuilder.java:1415)
        at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1993)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitParenthesized(CFGBuilder.java:4122)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitParenthesized(CFGBuilder.java:1415)
        at com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:1849)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitIf(CFGBuilder.java:3926)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitIf(CFGBuilder.java:1415)
        at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1427)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:3257)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.visitBlock(CFGBuilder.java:1415)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1570)
        at org.checkerframework.dataflow.cfg.CFGBuilder$CFGTranslationPhaseOne.process(CFGBuilder.java:1614)
        at org.checkerframework.dataflow.cfg.CFGBuilder.build(CFGBuilder.java:229)
        at com.google.errorprone.dataflow.DataFlow$2.load(DataFlow.java:120)
        at com.google.errorprone.dataflow.DataFlow$2.load(DataFlow.java:94)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
        ... 259 more
```

**Comment by shevek** [comment]
Also fails in 2.3.4

**Comment by shevek** [comment]
Declaring types in lambda did *not* work around it.
Switching to a for-each loop *did* work around it.
This is presumably something to do with the combination of lambdas and unboxing.

**Comment by shevek** [comment]
Was ths fix for this to remove the feature? Does this mean that errorprone no longer does null-reference checks?

**Comment by cushon** [comment]
The check was experimental and was never enabled by default. We still have some nullness related checks, but providing a comprehensive set a static analysis for nullness (similar to the Checker Framework, or NullAway) is not a goal at this time.
