### ISSUE TITLE
IAE encountered for AlmostJavadoc bug pattern during scan of rules_kotlin

### ISSUE THREAD

**Issue by davido** [google/error-prone#1632]
Running 2.3.5 SNAPSHOT EP version on rule_kotlin@HEAD is failing with:

```
src/test/kotlin/io/bazel/kotlin/builder/KotlinJvmTestBuilder.java:17: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
package io.bazel.kotlin.builder;
^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.3.5-SNAPSHOT
     BugPattern: AlmostJavadoc
     Stack Trace:
     java.lang.IllegalArgumentException: Multiple entries with same key: 1373=@SuppressWarnings(value = {"unused", "WeakerAccess"})
  public static Dep KOTLIN_STDLIB = Dep.fromLabel("@com_github_jetbrains_kotlin//:kotlin-stdlib") and 1373=@SuppressWarnings(value = {"unused", "WeakerAccess"})
  public static Dep KOTLIN_ANNOTATIONS = Dep.fromLabel("@com_github_jetbrains_kotlin//:annotations")
  	at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:215)
  	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:209)
  	at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:147)
  	at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:110)
  	at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:393)
  	at com.google.errorprone.bugpatterns.javadoc.AlmostJavadoc.getJavadocableTrees(AlmostJavadoc.java:179)
  	at com.google.errorprone.bugpatterns.javadoc.AlmostJavadoc.matchCompilationUnit(AlmostJavadoc.java:76)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:557)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:152)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:56)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:161)
  	at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:115)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1375)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:114)
  	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.fallback(ReducedClasspathJavaLibraryBuilder.java:105)
  	at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:67)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:116)
  	at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:123)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:106)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:68)
  	at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:46)

```

**Comment by nglorioso** [comment]
There are multiple declarations of public members in the same statement:

https://github.com/bazelbuild/rules_kotlin/blob/53cd4b28108694ec11bd64ea3ad5a52ccd363963/src/test/kotlin/io/bazel/kotlin/builder/KotlinJvmTestBuilder.java#L38
