### ISSUE TITLE
NoClassDefFoundError: org/threeten/extra/AmPm

### ISSUE THREAD

**Issue by davidhart82** [google/error-prone#1670]
ErrorProne 2.4, using error_prone_core-2.4.0-with-dependencies.jar, appears not to contain the threeten dependencies for the new FromTemporalAccessor check.

**Comment by omeryounus** [comment]
which JDK are you running on ?

**Comment by davidhart82** [comment]
Using JDK 8.

**Comment by kleinj** [comment]
I'm running into the same problem (on JDK11).

To reproduce:

1. Create new/empty directory, go there and put the ShortSet.java example from http://errorprone.info/ there.
2. Execute the 3 wget commands from the 'Command Line - Java 9, 10, and 11' section of http://errorprone.info/docs/installation
2. Run
 `javac
  -XDcompilePolicy=simple
  -processorpath error_prone_core-2.4.0-with-dependencies.jar:dataflow-shaded-3.1.2.jar:jFormatString-3.0.0.jar
  '-Xplugin:ErrorProne'
  ShortSet.java`

Output:
```
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.4.0
     BugPattern: (see stack trace)
     Stack Trace:
     java.lang.NoClassDefFoundError: org/threeten/extra/AmPm
  	at com.google.errorprone.bugpatterns.time.FromTemporalAccessor.<clinit>(FromTemporalAccessor.java:103)
  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
  	at com.google.errorprone.scanner.ScannerSupplierImpl.instantiateChecker(ScannerSupplierImpl.java:84)
  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
  	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:102)
  	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:40)
  	at com.google.errorprone.ErrorProneAnalyzer.lambda$scansPlugins$0(ErrorProneAnalyzer.java:79)
  	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
  Caused by: java.lang.ClassNotFoundException: org.threeten.extra.AmPm
  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
  	... 26 more
1 error
```

**Comment by kluever** [comment]
This seems like a dependency issue - CC'ing myself.

**Comment by dtomassi** [comment]
@kluever Any updates on this?

**Comment by chenqihong** [comment]
I am having the same problem. Is there any way to fix this problem?

Thank you

**Comment by cushon** [comment]
> I am having the same problem. Is there any way to fix this problem?

This was fixed in #1794, which will be in the next release (#2061).

You could wait for the next release, or add an explicit dependency on `org.threeten:threeten-extra`:

```
    <dependency>
      <groupId>org.threeten</groupId>
      <artifactId>threeten-extra</artifactId>
      <version>1.5.0</version>
    </dependency>
    ```

**Comment by chenqihong** [comment]
I just add this dependency on my local mac, which is in .m2/repository/org/threeten/threeten-extra/1.5.0/threeten-extra-1.5.0.jar. When I run the same command, it still reports the same issue. I am just wondering if I place this dependency in the incorrect location? Thank you.

**Comment by cushon** [comment]
It needs to be on the processorpath when you run Error Prone, e.g. by adding an entry in `<annotationProcessorPaths>` to your `pom.xml` if you're using maven, or adding it to javac's `-processorpath` if you're using the 'command line' instructions in http://errorprone.info/docs/installation.

**Comment by chenqihong** [comment]
@cushon Resolved! Thank you so much!
