### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin.

### ISSUE THREAD

**Issue by pulkitsharva** [google/error-prone#1698]
error-prone version: 2.3.4
     BugPattern: JavaTimeDefaultTimeZone
     Stack Trace:
     `java.lang.LinkageError: com.sun.tools.javac.comp.Resolve.findIdent(com.sun.tools.javac.comp.Env,com.sun.tools.javac.util.Name,com.sun.tools.javac.code.Kinds$KindSelector)
  	at com.google.errorprone.util.FindIdentifiers.findIdent(FindIdentifiers.java:104)
  	at com.google.errorprone.fixes.SuggestedFixes.qualifyType(SuggestedFixes.java:361)
  	at com.google.errorprone.bugpatterns.time.JavaTimeDefaultTimeZone.matchMethodInvocation(JavaTimeDefaultTimeZone.java:117)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:748)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:152)
  	.......
  Caused by: java.lang.NoSuchMethodException: com.sun.tools.javac.comp.Resolve.findIdent(com.sun.tools.javac.comp.Env,com.sun.tools.javac.util.Name,com.sun.tools.javac.code.Kinds$KindSelector)
  	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2553)
  	at com.google.errorprone.util.FindIdentifiers.findIdent(FindIdentifiers.java:98)
  	... 237 more`

**Comment by Stephan202** [comment]
This is a Java 13+ compatibility issue; see [numerous other tickets](https://github.com/google/error-prone/issues?q=%22java.lang.LinkageError%3A+com.sun.tools.javac.comp.Resolve.findIdent%22). Upgrading to version 2.4.0 should fix it.
