### ISSUE TITLE
ClassCastException from PreconditionsExpensiveString

### ISSUE THREAD

**Issue by cushon** [google/error-prone#176]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=176) created by **steven.m.reed** on 2013-08-13 at 07:43 PM_

---

<b>What steps will reproduce the problem?</b>
1. Trigger the PreconditionsExpensiveString pattern by writing a valid line of code similar to:

&nbsp;&nbsp;Preconditions.checkState(foo.isEmpty(), String.format("Foo must be empty, is %s", foo));

2. compile (I was using maven, configured as per the wiki)

<b>What is the expected output? What do you see instead?</b>

I expect the errorprone compiler to warn me against this usage. However, the compiler itself throws a ClassCastException (included below).

<b>What version of the product are you using? On what operating system?</b>

Using 2.3-SNAPSHOT of plexus-compiler-javac and plexus-compiler-javac-errorprone, and 3.1 of maven-compiler-plugin.

<b>Please provide any additional information below.</b>

An exception has occurred in the compiler (1.7.0_25). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.ClassCastException: com.sun.tools.javac.tree.JCTree$JCIdent cannot be cast to com.sun.source.tree.MemberSelectTree
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.bugpatterns.PreconditionsExpensiveString.matchMethodInvocation(PreconditionsExpensiveString.java:83)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:184)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:33)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1333)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:111)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:44)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:240)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1173)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:111)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:44)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:159)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:790)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:111)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:44)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.visitEnhancedForLoop(TreeScanner.java:185)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:915)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:111)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:44)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:159)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:790)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:111)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:44)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:142)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.ErrorProneScanner.visitMethod(ErrorProneScanner.java:258)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.ErrorProneScanner.visitMethod(ErrorProneScanner.java:33)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:690)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:111)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:44)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:80)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.scan(TreeScanner.java:90)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:98)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:132)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.ErrorProneScanner.visitClass(ErrorProneScanner.java:299)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.ErrorProneScanner.visitClass(ErrorProneScanner.java:33)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:618)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:67)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:111)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.google.errorprone.Scanner.scan(Scanner.java:44)

**Comment by cushon** [comment]
Fixed, see #173
