### ISSUE TITLE
Error-Prone needs to be adapted to JDK-8254073 for Java 16 compatibility (JavaTokenizer.reader)

### ISSUE THREAD

**Issue by don-vip** [google/error-prone#1872]
### Description of the problem:

Error-Prone does not work anymore with Java 16-ea (b20+). It fails with this stacktrace:

```
    [javac] /var/lib/jenkins/jobs/Java-EarlyAccess-JOSM/workspace/jdk/JDK16/src/org/openstreetmap/josm/tools/LanguageInfo.java:2: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    [javac] package org.openstreetmap.josm.tools;
    [javac] ^
    [javac]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
    [javac]   
    [javac]      error-prone version: 2.4.0
    [javac]      BugPattern: AlmostJavadoc
    [javac]      Stack Trace:
    [javac]      java.lang.NoSuchFieldError: reader
    [javac]   	at com.google.errorprone.util.ErrorProneTokens$CommentSavingTokenizer.processComment(ErrorProneTokens.java:85)
    [javac]   	at jdk.compiler/com.sun.tools.javac.parser.JavaTokenizer.readToken(JavaTokenizer.java:919)
    [javac]   	at jdk.compiler/com.sun.tools.javac.parser.Scanner.nextToken(Scanner.java:115)
    [javac]   	at com.google.errorprone.util.ErrorProneTokens.getTokens(ErrorProneTokens.java:57)
    [javac]   	at com.google.errorprone.util.ErrorProneTokens.getTokens(ErrorProneTokens.java:74)
    [javac]   	at com.google.errorprone.util.ErrorProneTokens.getTokens(ErrorProneTokens.java:65)
    [javac]   	at com.google.errorprone.bugpatterns.javadoc.AlmostJavadoc.matchCompilationUnit(AlmostJavadoc.java:80)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:451)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:557)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:152)
    [javac]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:603)
    [javac]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
    [javac]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
    [javac]   	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1421)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1368)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
    [javac]   	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
    [javac]   	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

### What's the simplest, easiest way to reproduce this bug?

git clone https://github.com/openstreetmap/josm.git && cd josm && ant

### What version of Error Prone are you using?

2.4.0

###  Have you found anything relevant by searching the web?

The change is caused by:
- https://bugs.openjdk.java.net/browse/JDK-8254073
- https://github.com/openjdk/jdk/commit/4f9a1ffcdd36f8c0cced9eeaa587fd439d4daf7b#diff-9dd71a3938fb726eb0eb9b7b30d8727167dad2402854b38464446c7a63ca1638

**Comment by don-vip** [comment]
@cushon the issue is clearly visible in https://github.com/google/error-prone/runs/1502836649

Java 16 enters [RP1 this week](http://openjdk.java.net/projects/jdk/16/) so its APIs can be considered quite stable already.

**Comment by cushon** [comment]
https://github.com/google/error-prone/commit/29708390e2124c10261a3643f3563a5e7f3f9a9f
