### ISSUE TITLE
NullPointerException in SameNameButDifferent

### ISSUE THREAD

**Issue by sjamesr** [google/error-prone#1990]
I think 09987716fae9b0a3845d6de83a10aa89a2451427 causes NPEs in SameNameButDifferent in certain cases:

```java
        String treeSource = state.getSourceForNode(tree);
        Symbol symbol = getSymbol(tree);
        if (symbol instanceof ClassSymbol) {
          List<TreePath> treePaths = table.get(treeSource, symbol.type.tsym);
          if (treePaths == null) {
            treePaths = new ArrayList<>();
            table.put(treeSource, symbol.type.tsym, treePaths);         // <<---- treeSource is null
          }
          if (state.getEndPosition(tree) != Position.NOPOS) {
            treePaths.add(getCurrentPath());
          }
        }
```

This change also introduced the following code, where it appears "Builder" has a typo:

```java
        if (tree instanceof IdentifierTree
            && ((IdentifierTree) tree).getName().contentEquals("Buiilder")) {  // <<--- should be "Builder" ?
          return;
        }
```

I'm working on steps to reproduce. Here's an excerpt from that patch that I think might be problematic:

```patch
diff --git a/core/src/main/java/com/google/errorprone/bugpatterns/SameNameButDifferent.java b/core/src/main/java/com/google/errorprone/bugpatterns/SameNameButDifferent.java
index ea23d9fbf..9270501b6 100644
--- a/core/src/main/java/com/google/errorprone/bugpatterns/SameNameButDifferent.java
+++ b/core/src/main/java/com/google/errorprone/bugpatterns/SameNameButDifferent.java
@@ -95,15 +95,17 @@ public final class SameNameButDifferent extends BugChecker implements Compilatio
       }
 
       private void handle(Tree tree) {
-        if (tree.toString().equals("Builder")) {
+        if (tree instanceof IdentifierTree
+            && ((IdentifierTree) tree).getName().contentEquals("Buiilder")) {
           return;
         }
+        String treeSource = state.getSourceForNode(tree);
         Symbol symbol = getSymbol(tree);
         if (symbol instanceof ClassSymbol) {
-          List<TreePath> treePaths = table.get(tree.toString(), symbol.type.tsym);
+          List<TreePath> treePaths = table.get(treeSource, symbol.type.tsym);
           if (treePaths == null) {
             treePaths = new ArrayList<>();
-            table.put(tree.toString(), symbol.type.tsym, treePaths);
+            table.put(treeSource, symbol.type.tsym, treePaths);
           }
           if (state.getEndPosition(tree) != Position.NOPOS) {
             treePaths.add(getCurrentPath());

```

**Comment by tbroyer** [comment]
Should be fixed by #1987

**Comment by sjamesr** [comment]
To reproduce:

```
$ git clone https://github.com/google/error-prone.git
$ cd error-prone
$ mvn install -DskipTests    # causes 2.4.1-SNAPSHOT to be installed locally

$ cd ..
$ git clone git@github.com:sjamesr/jfreesane.git
$ cd jfreesane
$ git apply <<EOF
diff --git a/build.gradle b/build.gradle
index fc1e618..4addce2 100644
--- a/build.gradle
+++ b/build.gradle
@@ -22,6 +22,7 @@ jacocoTestReport {
 def releaseVersion = '0.98'
 
 repositories {
+    mavenLocal()
     mavenCentral()
 }
 
@@ -32,8 +33,8 @@ dependencies {
     // Cobertura requires slf4j at runtime
     testRuntime 'org.slf4j:slf4j-api:1.7.10'
 
-    errorprone 'com.google.errorprone:error_prone_core:2.3.3'
-    errorproneJavac 'com.google.errorprone:error_prone_core:2.3.3'
+    errorprone 'com.google.errorprone:error_prone_core:2.4.1-SNAPSHOT'
+    errorproneJavac 'com.google.errorprone:error_prone_core:2.4.1-SNAPSHOT'
 }
 
 wrapper {
EOF

$ ./gradlew check

```

Should yield:

```
.../jfreesane/src/main/java/au/com/southsky/jfreesane/SaneDevice.java:1: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
package au.com.southsky.jfreesane;
^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.4.1-SNAPSHOT
     BugPattern: SameNameButDifferent
     Stack Trace:
     java.lang.NullPointerException
  	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:877)
  	at com.google.common.collect.StandardTable.put(StandardTable.java:145)
  	at com.google.common.collect.HashBasedTable.put(HashBasedTable.java:51)
  	at com.google.errorprone.bugpatterns.SameNameButDifferent$1.handle(SameNameButDifferent.java:108)
  	at com.google.errorprone.bugpatterns.SameNameButDifferent$1.visitMemberSelect(SameNameButDifferent.java:66)
  	at com.google.errorprone.bugpatterns.SameNameButDifferent$1.visitMemberSelect(SameNameButDifferent.java:62)
```

**Comment by sjamesr** [comment]
@tbroyer thank you!

**Comment by sjamesr** [comment]
@tbroyer that patch does resolve the issue
