### ISSUE TITLE
[intellij plugin] ErrorProneIdeaCompiler : Unsupported major.minor version 51.0

### ISSUE THREAD

**Issue by cushon** [google/error-prone#216]
_[Original issue](https://code.google.com/p/error-prone/issues/detail?id=216) created by **jkuhnert** on 2013-11-22 at 12:18 AM_

---

<b>What steps will reproduce the problem?</b>
1. Try to use http://plugins.jetbrains.com/plugin/7349?pr=idea (thanks by the way, high five!)
2. See the complete and total failure of plugin to even be loaded by ide classloader because it is "dirty" 
3. Become sad, investigate where it came from. Get excited it's error-prone Alex works on that project awesmoe!

<b>What is the expected output? What do you see instead?</b>

Need to configure intellij compiler language target for javac of the intellij module of project I think. Like: https://code.google.com/p/error-prone/source/diff?spec=svn7637cad771eccf11de3138cb91f42a690d5d1ef3&r=bc0102dd741ad6de7cedf1631a41bd3c34d35abe&format=side&path=/idea-plugin/idea-plugin.iml

If you had this attribute on your &lt;component&gt; xml element line:
LANGUAGE_LEVEL="JDK_1_6"

Then my java6 runtime apple class loader on osx which intellij is launching from currently will become happy again.

<b>What version of the product are you using? On what operating system?</b>
The version that hates me. And jebus =( 

<b>Please provide any additional information below.</b>

Complete log contents of intellij log file related to error pasted below:

2013-11-21 18:58:12,753 [   6110]   INFO - le.impl.ModuleManagerComponent - 11 module(s) loaded in 552 ms 
2013-11-21 18:58:13,326 [   6683]  ERROR - ellij.project.impl.ProjectImpl - com.intellij.compiler.CompilerConfigurationImpl@7c3b6645 
com.intellij.openapi.extensions.impl.PicoPluginExtensionInitializationException: com/google/errorprone/intellij/ErrorProneIdeaCompiler : Unsupported major.minor version 51.0 [Plugin: Error-prone plugin]
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:98)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:121)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:241)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:185)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:111)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:104)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.compiler.CompilerConfigurationImpl.b(CompilerConfigurationImpl.java:317)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.compiler.CompilerConfigurationImpl.projectOpened(CompilerConfigurationImpl.java:279)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:419)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:77)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:456)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectManagerImpl$2.projectOpened(ProjectManagerImpl.java:155)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:1050)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:415)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:506)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:181)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.RecentProjectsManager.doOpenProject(RecentProjectsManager.java:46)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:350)
&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.reflect.Method.invoke(Method.java:597)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:209)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.proxy.$Proxy38.appStarting(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.idea.IdeaApplication.c(IdeaApplication.java:294)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.idea.IdeaApplication.access$500(IdeaApplication.java:56)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:261)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:346)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue.access$400(EventQueue.java:82)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue$2.run(EventQueue.java:676)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue$2.run(EventQueue.java:674)
&nbsp;&nbsp;&nbsp;&nbsp;at java.security.AccessController.doPrivileged(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:696)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: com.intellij.diagnostic.PluginException: com/google/errorprone/intellij/ErrorProneIdeaCompiler : Unsupported major.minor version 51.0 [Plugin: Error-prone plugin]
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Class.forName0(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Class.forName(Class.java:249)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadClass(ExtensionComponentAdapter.java:158)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:63)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:70)
&nbsp;&nbsp;&nbsp;&nbsp;... 49 more
Caused by: java.lang.UnsupportedClassVersionError: com/google/errorprone/intellij/ErrorProneIdeaCompiler : Unsupported major.minor version 51.0
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.defineClass1(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:189)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:185)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:161)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
&nbsp;&nbsp;&nbsp;&nbsp;... 57 more
Caused by:

com.intellij.diagnostic.PluginException: com/google/errorprone/intellij/ErrorProneIdeaCompiler : Unsupported major.minor version 51.0 [Plugin: Error-prone plugin]
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Class.forName0(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.Class.forName(Class.java:249)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadClass(ExtensionComponentAdapter.java:158)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:63)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:70)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:121)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:241)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:185)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:111)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:104)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.compiler.CompilerConfigurationImpl.b(CompilerConfigurationImpl.java:317)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.compiler.CompilerConfigurationImpl.projectOpened(CompilerConfigurationImpl.java:279)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:419)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:77)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:456)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectManagerImpl$2.projectOpened(ProjectManagerImpl.java:155)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:1050)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:415)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:506)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:181)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.RecentProjectsManager.doOpenProject(RecentProjectsManager.java:46)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:350)
&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
&nbsp;&nbsp;&nbsp;&nbsp;at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.reflect.Method.invoke(Method.java:597)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:209)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
&nbsp;&nbsp;&nbsp;&nbsp;at com.sun.proxy.$Proxy38.appStarting(Unknown Source)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.idea.IdeaApplication.c(IdeaApplication.java:294)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.idea.IdeaApplication.access$500(IdeaApplication.java:56)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:261)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:346)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue.access$400(EventQueue.java:82)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue$2.run(EventQueue.java:676)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue$2.run(EventQueue.java:674)
&nbsp;&nbsp;&nbsp;&nbsp;at java.security.AccessController.doPrivileged(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:696)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
&nbsp;&nbsp;&nbsp;&nbsp;at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: com/google/errorprone/intellij/ErrorProneIdeaCompiler : Unsupported major.minor version 51.0
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.defineClass1(Native Method)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:189)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:185)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:161)
&nbsp;&nbsp;&nbsp;&nbsp;at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
&nbsp;&nbsp;&nbsp;&nbsp;... 57 more
2013-11-21 18:58:13,329 [   6686]  ERROR - ellij.project.impl.ProjectImpl - IntelliJ IDEA (Cardea) IU-133.79  Build #IU-133.79 
2013-11-21 18:58:13,329 [   6686]  ERROR - ellij.project.impl.ProjectImpl - JDK: 1.6.0_65 
2013-11-21 18:58:13,329 [   6686]  ERROR - ellij.project.impl.ProjectImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
2013-11-21 18:58:13,329 [   6686]  ERROR - ellij.project.impl.ProjectImpl - Vendor: Apple Inc. 
2013-11-21 18:58:13,330 [   6687]  ERROR - ellij.project.impl.ProjectImpl - OS: Mac OS X 
2013-11-21 18:58:13,330 [   6687]  ERROR - ellij.project.impl.ProjectImpl - Last Action:

**Comment by cushon** [comment]
I just tested the intellij plugin, and it works with error-prone 2.0.1, JDK8, and intellij 14.

The bug report shows that Apple's JDK 6 was being used, which we aren't going to support: #16
