### ISSUE TITLE
2.5.1 - IllegalAccessError in Ant build with Java 16

### ISSUE THREAD

**Issue by don-vip** [google/error-prone#2195]
### Description of the problem / feature request:

[JOSM ant build](https://josm.openstreetmap.de/browser/josm/trunk/build.xml) works fine with Java 15 but fails with Java 16, even after upgrade to Error-Prone 2.5.1:
```
    [javac] Exception in thread "main" java.lang.IllegalAccessError: class com.google.errorprone.BaseErrorProneJavaCompiler (in unnamed module @0x5204062d) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x5204062d
    [javac] 	at com.google.errorprone.BaseErrorProneJavaCompiler.addTaskListener(BaseErrorProneJavaCompiler.java:94)
    [javac] 	at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:34)
    [javac] 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:255)
    [javac] 	at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:229)
    [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:292)
    [javac] 	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
    [javac] 	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
    [javac] 	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)

BUILD FAILED
/var/lib/jenkins/jobs/Java-EarlyAccess-JOSM/workspace/jdk/JDK16/build.xml:269: Compile failed; see the compiler error output for details.
	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1409)
	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1117)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:827)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

`svn co https://josm.openstreetmap.de/svn/trunk josm && cd josm && ant`

### What version of Error Prone are you using?

2.5.1

###  Have you found anything relevant by searching the web?

No. Build works fine with Java 8, 11, 15. Only 16 fails.

**Comment by cushon** [comment]
https://github.com/google/error-prone/issues/1157#issuecomment-769289564
