### ISSUE TITLE
Error prone crash 2.5.1

### ISSUE THREAD

**Issue by dpcollins-google** [google/error-prone#2264]
```
error-prone version: 2.5.1
     BugPattern: ArgumentSelectionDefectChecker
     Stack Trace:
     java.lang.NoSuchMethodError: com.google.common.base.Splitter.splitToStream(Ljava/lang/CharSequence;)Ljava/util/stream/Stream;
  	at com.google.errorprone.names.NamingConventions.splitToLowercaseTerms(NamingConventions.java:52)
  	at com.google.errorprone.bugpatterns.argumentselectiondefects.Parameter.getArgumentName(Parameter.java:187)
  	at com.google.errorprone.bugpatterns.argumentselectiondefects.Parameter.lambda$createListFromExpressionTrees$1(Parameter.java:97)
  	at com.google.common.collect.Streams$1Splitr.tryAdvance(Streams.java:457)
  	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
  	at com.google.errorprone.bugpatterns.argumentselectiondefects.Parameter.createListFromExpressionTrees(Parameter.java:103)
  	at com.google.errorprone.bugpatterns.argumentselectiondefects.ArgumentChangeFinder.findChanges(ArgumentChangeFinder.java:88)
  	at com.google.errorprone.bugpatterns.argumentselectiondefects.ArgumentSelectionDefectChecker.visitNewClassOrMethodInvocation(ArgumentSelectionDefectChecker.java:113)
  	at com.google.errorprone.bugpatterns.argumentselectiondefects.ArgumentSelectionDefectChecker.matchMethodInvocation(ArgumentSelectionDefectChecker.java:92)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:747)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1650)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:469)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:818)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1554)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:521)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1032)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:741)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:549)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:561)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:57)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:43)
```

**Comment by tbroyer** [comment]
Check the version of Guava you have in the annotation processor path. Most likely you have an old version for some reason (older than 28.2 which introduced `Splitter.splitToStream`).

**Comment by dpcollins-google** [comment]
This was resolved by putting autovalue (1.7.4) after errorprone. You might want to look into getting autovalue to bump their guava version?

**Comment by tbroyer** [comment]
Auto Value 1.7.5 uses Guava 30.1.1-jre: https://search.maven.org/artifact/com.google.auto.value/auto-value/1.7.5/jar

But this is a transitive dependency, so if you have that behavior it probably means that you are using Maven; in which case the problem is Maven's utterly broken/simplistic/idiotic "nearest first" resolution rule: https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html; so the *real fix* is to declare an explicit Guava dependency whose version you choose to meet the other dependencies' constraints.

**Comment by cushon** [comment]
```
     java.lang.NoSuchMethodError: com.google.common.base.Splitter.splitToStream(Ljava/lang/CharSequence;)Ljava/util/stream/Stream;
  	at com.google.errorprone.names.NamingConventions.splitToLowercaseTerms(NamingConventions.java:52)
```

Adding the latest version of guava to the same annotation processor path Error Prone is on should fix this, see also https://github.com/google/error-prone/issues/2138#issuecomment-766314550
