### ISSUE TITLE
Lombok UtilityClass causes NPE from SameNameButDifferent (Java 16)

### ISSUE THREAD

**Issue by piotrekfus91** [google/error-prone#2290]
After upgrading to Java 16 (from 15) and Lombok 1.18.20 (from 1.18.16) compiling class annotated with `@UtilityClass` causes NPE:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project common: Compilation failure
[ERROR] /home/pfus/touk/workspace/[***]/OptionalUtils.java:[1] error: An unhandled exception was thrown by the Error Prone static analysis plugin.
[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[ERROR]
[ERROR]      error-prone version: 2.6.0
[ERROR]      BugPattern: SameNameButDifferent
[ERROR]      Stack Trace:
[ERROR]      java.lang.NullPointerException: Cannot read field "owner" because "owner" is null
[ERROR]         at com.google.errorprone.bugpatterns.SameNameButDifferent.getBetterImport(SameNameButDifferent.java:187)
[ERROR]         at com.google.errorprone.bugpatterns.SameNameButDifferent.matchCompilationUnit(SameNameButDifferent.java:142)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:556)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:151)

```

I use error prone 2.6.0.

Sample code:

```
import lombok.experimental.UtilityClass;
import org.slf4j.MDC;

import java.util.Map;
import java.util.Optional;
import java.util.function.Supplier;

@UtilityClass
public class LoggingContext {
    public void withMdc(Map<String, Object> context, Runnable action) {
        withMdc(context, () -> {
            action.run();
            return null;
        });
    }

    public <T> T withMdc(Map<String, Object> context, Supplier<T> supplier) {
        context.forEach((key, value) -> Optional.ofNullable(value).map(Object::toString).ifPresent(v -> MDC.put(key, v)));
        try {
            return supplier.get();
        } finally {
            context.keySet().forEach(MDC::remove);
        }
    }
}
```

**Comment by biscout24** [comment]
Same happened here after update lombok from `1.18.16` to `1.18.20`
```
     error-prone version: 2.7.1
     BugPattern: SameNameButDifferent
     Stack Trace:
     java.lang.NullPointerException
```
env
```
java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

**Comment by cushon** [comment]
https://github.com/google/error-prone/issues/2273
