### ISSUE TITLE
Nested record causes AssertionError in PrivateConstructorForUtilityClass

### ISSUE THREAD

**Issue by dododge** [google/error-prone#2323]
> ATTENTION! Please read and follow:
> - if this is a _question_ about Error Prone, send it to error-prone-discuss@googlegroups.com
> - if this is a _bug_ or _feature request_, fill the form below as best as you can.

### Description of the problem / feature request:

`PrivateConstructorForUtilityClass` doesn't seem to handle a utility class that has a record inside.

```
     error-prone version: 2.6.0
     BugPattern: PrivateConstructorForUtilityClass
     Stack Trace:
     java.lang.AssertionError: unknown member type:RECORD
  	at com.google.errorprone.bugpatterns.PrivateConstructorForUtilityClass.isInstance(PrivateConstructorForUtilityClass.java:110)
  	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
  	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4820)
  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
  	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
  	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
  	at com.google.errorprone.bugpatterns.PrivateConstructorForUtilityClass.matchClass(PrivateConstructorForUtilityClass.java:76)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:832)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:109)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:117)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:148)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:561)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:603)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1421)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1368)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```
### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

This seems to be enough to trigger the problem:

```java
package example;

public final class ExampleUtilityClass
{
    public record SomeRecord(String value) { }
}
```

### What version of Error Prone are you using?

2.6.0

**Comment by cushon** [comment]
51b5c4d9f2e5917f6e2a877aeb77b5fe8d94d7bc
