### ISSUE TITLE
JDK 17-EA failure

### ISSUE THREAD

**Issue by codylerum** [google/error-prone#2440]
### Description of the problem / feature request:

> Exception when using 2.7.1 with JDK 17-ea in github actions

### Feature requests: what underlying problem are you trying to solve with this feature?

> exception in errorprone run

### Bugs: what's the simplest, easiest way to reproduce this bug? Please provide a minimal example if possible.

> Compile using github actions,  ubuntu-20.04, dist: adopt

### What version of Error Prone are you using?

> 2.7.1

###  Have you found anything relevant by searching the web?

> Similar issue with Gradle and https://github.com/google/error-prone/issues/2400

Same build passes on JDK 15 and 16. Error-Prone is using an older version of java-setup

```
Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.7.1
     BugPattern: JavaLangClash
     Stack Trace:
     java.lang.LinkageError: com.sun.tools.javac.code.Scope.anyMatch(java.util.function.Predicate)
  	at com.google.errorprone.util.ErrorProneScope.getMethodOrDie(ErrorProneScope.java:123)
  	at com.google.errorprone.util.ErrorProneScope.getImpl(ErrorProneScope.java:86)
  	at com.google.errorprone.util.ErrorProneScope.<clinit>(ErrorProneScope.java:68)
  	at com.google.errorprone.util.ASTHelpers.scope(ASTHelpers.java:2180)
  	at com.google.errorprone.bugpatterns.JavaLangClash.check(JavaLangClash.java:66)
  	at com.google.errorprone.bugpatterns.JavaLangClash.matchClass(JavaLangClash.java:53)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:832)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:109)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:117)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:148)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:561)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:603)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1421)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1368)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
  Caused by: java.lang.NoSuchMethodException: com.sun.tools.javac.code.Scope.anyMatch(java.util.function.Predicate)
  	at java.base/java.lang.Class.getMethod(Class.java:2195)
  	at com.google.errorprone.util.ErrorProneScope.getMethodOrDie(ErrorProneScope.java:121)
  	... 30 more
```

**Comment by cushon** [comment]
> Similar issue with Gradle and #2400

Do you have a repro? Can you share the output of a run that passes the JVM flag `-Xlog:class+load=info` when running Error Prone?

**Comment by codylerum** [comment]
Here would be a repo:
https://github.com/codylerum/errorprone_java16

Actions Run:
https://github.com/codylerum/errorprone_java16/runs/3038127483?check_suite_focus=true

**Comment by cushon** [comment]
That GH Actions run is using a fairly old JDK 17 EA version from 2021-1-13:

```
Downloading Java 17.0.0+29.0.202101130348 (Adopt-Hotspot) from https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-2021-01-13-07-01/OpenJDK-jdk_x64_linux_hotspot_2021-01-13-03-30.tar.gz ...
```

The `NoSuchMethodException` is for an API that changed during the development of JDK 17, specifically this commit that was commited on 2021-4-22 released in `jdk-17+20`: https://github.com/openjdk/jdk/commit/657f10393745026c3a593872b8c37403dae3adc1

**Comment by codylerum** [comment]
@cushon Thanks I'm following up with the setup-java action project as others are going to run into this same thing as they start to test 17 in CI.

**Comment by codylerum** [comment]
@cushon Adopt has fixed their side and now everything is building correctly
