### ISSUE TITLE
Error prone threw exception during static analysis

### ISSUE THREAD

**Issue by bigkahuna1uk** [google/error-prone#2504]
Java 1.8_252 
Maven 3.6.0
ErrorProne 2.8.1

```
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration combine.self="override" combine.children="append">
                    <source>1.8</source>
                    <target>1.8</target>
                    <fork>true</fork>
                    <encoding>${maven.compiler.encoding}</encoding>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.google.errorprone</groupId>
                            <artifactId>error_prone_core</artifactId>
                            <version>2.8.1</version>
                        </path>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.20</version>
                        </path>
                    </annotationProcessorPaths>
                    <showWarnings>true</showWarnings>
                    <compilerArgs>
                        <arg>-XDcompilePolicy=simple</arg>
                        <arg>
                            -Xplugin:ErrorProne \
                            -Xep:DeadException:WARN \
                            -Xep:GuardedBy:OFF
                        </arg>
                        <arg>-J-Xbootclasspath/p:${settings.localRepository}/com/google/errorprone/javac/${javac.version}/javac-${javac.version}.jar</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            
         

error: An unhandled exception was thrown by the Error Prone static analysis plugin.
[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[ERROR]   
[ERROR]      error-prone version: 2.8.1
[ERROR]      BugPattern: SameNameButDifferent
[ERROR]      Stack Trace:
[ERROR]      java.lang.NullPointerException
[ERROR]         at com.google.errorprone.bugpatterns.SameNameButDifferent.getBetterImport(SameNameButDifferent.ja
va:187)
[ERROR]         at com.google.errorprone.bugpatterns.SameNameButDifferent.matchCompilationUnit(SameNameButDiffere
nt.java:142)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:55
6)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:15
1)
[ERROR]         at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
[ERROR]         at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]         at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
[ERROR]         at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.
java:43)
[ERROR]         at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
[ERROR]         at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
[ERROR]         at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1404)
[ERROR]         at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1353)
[ERROR]         at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
[ERROR]         at com.sun.tools.javac.main.Main.compile(Main.java:302)
[ERROR]         at com.sun.tools.javac.main.Main.compile(Main.java:162)
[ERROR]         at com.sun.tools.javac.Main.compile(Main.java:57)
[ERROR]         at com.sun.tools.javac.Main.main(Main.java:43)
```

**Comment by bigkahuna1uk** [comment]
using javac version 9+181-r4173-1

**Comment by cushon** [comment]
https://github.com/google/error-prone/issues/2273
