### ISSUE TITLE
Compilation failure: unhandled exception thrown by the Error Prone with maven 3.6.3 on openjdk 17-ea+19-Ubuntu-1ubuntu1

### ISSUE THREAD

**Issue by Echsecutor** [google/error-prone#2539]
Doing as I am told:

```
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.9.0
     BugPattern: JavaLangClash
     Stack Trace:
     java.lang.LinkageError: com.sun.tools.javac.code.Scope.anyMatch(java.util.function.Predicate)
  	at com.google.errorprone.util.ErrorProneScope.getMethodOrDie(ErrorProneScope.java:123)
  	at com.google.errorprone.util.ErrorProneScope.getImpl(ErrorProneScope.java:86)
  	at com.google.errorprone.util.ErrorProneScope.<clinit>(ErrorProneScope.java:68)
  	at com.google.errorprone.util.ASTHelpers.scope(ASTHelpers.java:2210)
  	at com.google.errorprone.bugpatterns.JavaLangClash.check(JavaLangClash.java:66)
  	at com.google.errorprone.bugpatterns.JavaLangClash.matchClass(JavaLangClash.java:53)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:840)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:109)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:117)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:148)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:561)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:611)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1421)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1368)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
  Caused by: java.lang.NoSuchMethodException: com.sun.tools.javac.code.Scope.anyMatch(java.util.function.Predicate)
  	at java.base/java.lang.Class.getMethod(Class.java:2208)
  	at com.google.errorprone.util.ErrorProneScope.getMethodOrDie(ErrorProneScope.java:121)
  	... 30 more
```

**Comment by cushon** [comment]
This could be similar to #2440 and #2400. Which JDK version are you using?

**Comment by Echsecutor** [comment]
```
$ mvn --version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 17-ea, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-31-generic", arch: "amd64", family: "unix"
```

**Comment by cushon** [comment]
> runtime: /usr/lib/jvm/java-17-openjdk-amd64

The issue in the other bugs I linked to involved using an old JDK 17 EA build. Can you try updating to a more recent build of JDK 17? What's the output of `java -fullversion`?

**Comment by Echsecutor** [comment]
```
$ java -fullversion
openjdk full version "17-ea+19-Ubuntu-1ubuntu1"
```

**Comment by Echsecutor** [comment]
yes, its certainly related to the JDK version. Using
```
$ JAVA_HOME=/usr/lib/jvm/java-16-openjdk-amd64/ mvn --version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 16.0.1, vendor: Private Build, runtime: /usr/lib/jvm/java-16-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-31-generic", arch: "amd64", family: "unix"
```
with
```
$ /usr/lib/jvm/java-16-openjdk-amd64/bin/java -fullversion
openjdk full version "16.0.1+9-Ubuntu-1"
```
for the build works. (Well I get the errors that I want to get from the plugin ;) )

**Comment by cushon** [comment]
Ok, thanks! I don't think this is something we're going to be able to fix for older JDK 17 EA builds at this point, since the JDK 17 GA is only a couple of weeks away, and this issue only affects older EA builds.
