### ISSUE TITLE
JDK (java/util/Formatter.java) causes NPE in FallThrough

### ISSUE THREAD

**Issue by iignatev** [google/error-prone#2638]
Hi folks,

while running  error-prone-2.9.0 against openjdk (see iignatev/jdk@b98331b0679a7d2574c3bc725d3b39d7479d3e68), I encounter the following NPE from FallThrough:
```
/Users/iignatye/ws/jdk/open/src/java.base/share/classes/java/util/Formatter.java:3998: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
            switch (c) {
            ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.9.0
     BugPattern: FallThrough
     Stack Trace:
     java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because the return value of "com.sun.source.tree.CaseTree.getStatements()" is null
  	at com.google.errorprone.util.Reachability$CanCompleteNormallyVisitor.lambda$visitSwitch$0(Reachability.java:227)
  	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
  	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1856)
  	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
  	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
  	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
  	at com.google.errorprone.util.Reachability$CanCompleteNormallyVisitor.visitSwitch(Reachability.java:227)
  	at com.google.errorprone.util.Reachability$CanCompleteNormallyVisitor.visitSwitch(Reachability.java:86)
  	at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1304)
  	at com.google.errorprone.util.Reachability$CanCompleteNormallyVisitor.scan(Reachability.java:103)
  	at com.google.errorprone.util.Reachability$CanCompleteNormallyVisitor.scan(Reachability.java:97)
  	at com.google.errorprone.util.Reachability$CanCompleteNormallyVisitor.visitBlock(Reachability.java:126)
  	at com.google.errorprone.util.Reachability$CanCompleteNormallyVisitor.visitBlock(Reachability.java:86)
  	at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
  	at com.google.errorprone.util.Reachability.canCompleteNormally(Reachability.java:66)
  	at com.google.errorprone.bugpatterns.FallThrough.matchSwitch(FallThrough.java:68)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitSwitch(ErrorProneScanner.java:824)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitSwitch(ErrorProneScanner.java:151)
  	at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1304)
  	at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:521)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:151)
  	at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
  	at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:741)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:151)
  	at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:953)
  	at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:549)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:151)
  	at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
  	at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:549)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:151)
  	at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
  	at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
  	at jdk.compiler.interim/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:152)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:561)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:151)
  	at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
  	at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler.interim/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler.interim/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
  	at jdk.compiler.interim/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
  	at jdk.compiler.interim/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
  	at jdk.compiler.interim/com.sun.tools.javac.main.Main.compile(Main.java:317)
  	at jdk.compiler.interim/com.sun.tools.javac.main.Main.compile(Main.java:176)
  	at jdk.compiler.interim/com.sun.tools.javac.Main.compile(Main.java:64)
  	at jdk.compiler.interim/com.sun.tools.javac.Main.main(Main.java:50)```

**Comment by sumitbhagwani** [comment]
Duplicate of https://github.com/google/error-prone/issues/2118 ?

**Comment by Yqwed** [comment]
It happens with 2.15.0.

**Comment by graememorgan** [comment]
I think this was a dupe of #2118, which is now fixed.
