### ISSUE TITLE
JDK 17 : Extend FormatString bug pattern to detect IllegalFormatArgumentIndexException

### ISSUE THREAD

**Issue by davido** [google/error-prone#2791]
This [code](https://gerrit.googlesource.com/gerrit/+/refs/heads/master/java/com/google/gerrit/server/git/MergeUtil.java#308) that is shared between Open Source [GerritCodeReview](https://gerrit.googlesource.com/gerrit) project and apparently internal Google code:

  java/com/google/gerrit/server/git/MergeUtil.java
```java
  String oursNameFormatted =
        String.format(
            "%0$-" + nameLength + "s (%s %s)",
            oursName,
            abbreviateName(ours, NAME_ABBREV_LEN),
            oursMsg.substring(0, Math.min(oursMsg.length(), 60)));
```

is passing all error prone bug patterns on Bazel@HEAD.

However, IllegalFormatArgumentIndexException is thrown by JDK 17 at runtime:

```
   $ bazeldev test --config java17 //javatests/com/google/gerrit/acceptance/rest/revision:RevisionIT
   [...]
   3) cherryPickConflictWithAllowConflicts(com.google.gerrit.acceptance.api.revision.RevisionIT)
java.util.IllegalFormatArgumentIndexException: Illegal format argument index = 0
	at java.base/java.util.Formatter$FormatSpecifier.index(Formatter.java:2808)
	at java.base/java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2879)
	at java.base/java.util.Formatter.parse(Formatter.java:2747)
	at java.base/java.util.Formatter.format(Formatter.java:2671)
	at java.base/java.util.Formatter.format(Formatter.java:2625)
	at java.base/java.lang.String.format(String.java:4140)
	at com.google.gerrit.server.git.MergeUtil.mergeWithConflicts(MergeUtil.java:309)
	at com.google.gerrit.server.git.MergeUtil.createCherryPickFromCommit(MergeUtil.java:275)
	at com.google.gerrit.server.restapi.change.CherryPickChange.cherryPick(CherryPickChange.java:320)
	at com.google.gerrit.server.restapi.change.CherryPickChange.cherryPick(CherryPickChange.java:167)
	at com.google.gerrit.server.restapi.change.CherryPick.apply(CherryPick.java:95)
	at com.google.gerrit.server.api.changes.RevisionApiImpl.cherryPickAsInfo(RevisionApiImpl.java:308)
	at com.google.gerrit.acceptance.api.revision.RevisionIT.cherryPickConflictWithAllowConflicts(RevisionIT.java:637)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at com.google.gerrit.acceptance.AbstractDaemonTest$1$1.evaluate(AbstractDaemonTest.java:252)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at com.google.testing.junit.runner.internal.junit4.CancellableRequestFactory$CancellableRunner.run(CancellableRequestFactory.java:108)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:116)
	at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:159)
	at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:85)
```

As pointed out by Dr. Heinz M. Kabutz: [1] `String.format()` method parsing machinery was optimized by factor 3 in Java 17 release and apparently the check is implemented in stricter way.

As documented in the Java API:

```
  %[argument_index$][flags][width][.precision]conversion
```

`argument_index` must be positive number.

Error prone should follow on this optimization and detect `IllegalFormatArgumentIndexException` at compile time in context of existing `FormatString` bug pattern.

See this upstream issue: [2] and this CL: [3] for more details.

To reproduce, clone recursively [Gerrit](https://gerrit.googlesource.com/gerrit) apply this CL: [4], and run with Bazel@HEAD (at least 5.0.0rc3):

```
  $ bazeldev test --config java17 //javatests/com/google/gerrit/acceptance/rest/revision:RevisionIT
```

Note, in case [3] is already submitted and merged up to main branch then it has to be reverted to reproduce the problem (not detection of `IllegalFormatArgumentIndexException` by error prone).

[1] https://www.javaspecialists.eu/archive/Issue294-String.format-3x-faster-in-Java-17.html
[2] https://crbug.com/gerrit/15500
[3] https://gerrit-review.googlesource.com/c/gerrit/+/327222
[4] https://gerrit-review.googlesource.com/c/gerrit/+/291864

**Comment by cushon** [comment]
This will be fixed in the next release of Error Prone: https://github.com/google/error-prone/commit/4caa8612cde67d325d8469d58d8c1524850ed4ae

**Comment by davido** [comment]
Thanks.
