### ISSUE TITLE
IndexOutOfBoundException when running static analysis

### ISSUE THREAD

**Issue by bcfisher** [google/error-prone#2802]
Recently, while running Error Prone static Analysis, I received the following error:

/Users/a510523/work/pr174519-java-observability-examples/metrics/spring-boot-metrics-example/src/main/java/com/fmr/logging/example/metrics/spring/service/JobSchedulerService.java:8
java: An unhandled exception was thrown by the Error Prone static analysis plugin.
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.9.0
     BugPattern: UnusedVariable
     Stack Trace:
     java.lang.IndexOutOfBoundsException
  	at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:633)
  	at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:41)
  	at com.google.errorprone.VisitorState.getOffsetTokens(VisitorState.java:589)
  	at com.google.errorprone.fixes.SuggestedFixes.replaceIncludingComments(SuggestedFixes.java:1543)
  	at com.google.errorprone.bugpatterns.UnusedVariable.buildUnusedVarFixes(UnusedVariable.java:385)
  	at com.google.errorprone.bugpatterns.UnusedVariable.matchCompilationUnit(UnusedVariable.java:234)
  	at com.google.errorprone.scanner.ErrorProneScanner$$Lambda$488/0x0000000000000000.process(Unknown Source)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:556)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:151)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at com.sun.tools.javac.api.JavacTaskImpl$$Lambda$105/0x0000000000000000.call(Unknown Source)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:238)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:514)
  	at org.jetbrains.jps.incremental.java.JavaBuilder$$Lambda$206/0x0000000000000000.invoke(Unknown Source)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:560)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:512)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:355)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:280)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:234)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1485)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1123)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1268)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1088)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:854)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:441)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:190)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:132)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:318)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:146)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$$Lambda$61/0x0000000000000000.run(Unknown Source)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  	at java.base/java.lang.Thread.run(Thread.java:836)

Contents of the file in question:
/***************************************************************************
* FIDELITY INVESTMENTS CONFIDENTIAL INFORMATION
*
* Copyright (c) 2022 Fidelity Investments. All Rights Reserved. Unauthorized reproduction,
* transmission, or distribution of this software is a violation of applicable laws.
*
****************************************************************************/
package com.fmr.logging.example.metrics.spring.service;

import com.fmr.logging.example.metrics.domain.Job;
import com.fmr.logging.example.metrics.domain.JobStatusType;
import com.fmr.logging.example.metrics.domain.JobType;
import com.fmr.logging.example.metrics.util.JobTypeMatcher;
import lombok.extern.slf4j.Slf4j;
import org.quartz.*;
import org.quartz.impl.matchers.GroupMatcher;
import org.springframework.stereotype.Service;

import java.util.*;

@Service
@Slf4j
public class JobSchedulerService implements IJobSchedulerService {
    private final Scheduler scheduler;
    private final JobTypeMatcher jobTypeMatcher;

    public JobSchedulerService(
            Scheduler scheduler, JobTypeMatcher jobTypeMatcher) {
        this.scheduler = scheduler;
        this.jobTypeMatcher = jobTypeMatcher;
    }

    public boolean pauseJob(JobType jobType) throws JobException {
        TriggerKey triggerKey = jobTypeMatcher.matchTriggerKey(jobType);
        try {
            return scheduler.unscheduleJob(triggerKey);
        } catch (SchedulerException e) {
            throw new JobException(e);
        }
    }

    @Override
    public void resumeJob(JobType jobType) throws JobException {
        try {
            scheduler.resumeJob(jobTypeMatcher.matchJobKey(jobType));
        } catch (SchedulerException e) {
            throw new JobException(e);
        }
    }

    public Set<JobKey> getJobKeys() throws SchedulerException {
        GroupMatcher<JobKey> groupMatcher = GroupMatcher.anyGroup();
        Set<JobKey> jobKeys = scheduler.getJobKeys(groupMatcher);
        return jobKeys;
    }

    @Override
    public List<Job> getJobs() throws JobException {
        try {
            Set<JobKey> jobKeys = getJobKeys();

            // java.lang.IllegalArgumentException: No enum constant
            // com.fmr.logging.example.metrics.domain.JobType.deleteArchivedJobDetail
            List<Job> jobList = new ArrayList<>();
            for (JobKey jobKey : jobKeys) {

                JobType jobType = jobTypeMatcher.matchJobType(jobKey);
                List<Trigger> triggers = (List<Trigger>) scheduler.getTriggersOfJob(jobKey);
                JobStatusType jobStatusType =
                        triggers.size() > 0 ? JobStatusType.ACTIVE : JobStatusType.INACTIVE;
                Job job = new Job(jobType, jobStatusType);
                jobList.add(job);
            }
            return jobList;
        } catch (SchedulerException e) {
            throw new JobException(e);
        }
    }

    public Job getJob(JobType jobType) {
        try {
            JobDetail jobDetail = scheduler.getJobDetail(jobTypeMatcher.matchJobKey(jobType));
            List<Trigger> triggers = (List<Trigger>) scheduler.getTriggersOfJob(jobDetail.getKey());
            JobStatusType jobStatusType =
                    triggers.size() > 0 ? JobStatusType.ACTIVE : JobStatusType.INACTIVE;
            return new Job(jobType, jobStatusType);
        } catch (SchedulerException e) {
            throw new JobException(e);
        }
    }

    @Override
    public Job getJob(String name) {
        try {
            JobDetail jobDetail =
                    scheduler.getJobDetail(jobTypeMatcher.matchJobTypeNameToJobKey(name));
            JobType jobType = jobTypeMatcher.matchJobType(jobDetail.getKey());
            return getJob(jobType);
        } catch (SchedulerException e) {
            throw new JobException(e);
        }
    }
}

**Comment by Stephan202** [comment]
There are a few [similar](https://github.com/google/error-prone/issues?q=HeapCharBuffer.java%3A633) reports; see #1250 for more details.
