### ISSUE TITLE
Ant integration for OpenJDK7 does not work as described

### ISSUE THREAD

**Issue by PhilippWendler** [google/error-prone#292]
The documentation claims that it is sufficient to add a `compilerclasspath` element to the `javac` task in the ant build file for error prone to work (in addition to the `compiler` attribute).

I am using Error-Prone 2.0.1, OpenJDK7 1.7.0_75, and ant 1.9.3 on Linux and I get the following error:
```
build.xml:17: java.lang.LinkageError: Unable to create runner.
        at com.google.errorprone.internal.NonDelegatingClassLoaderRunner.run(NonDelegatingClassLoaderRunner.java:40)
        at com.google.errorprone.ErrorProneAntCompilerAdapter.execute(ErrorProneAntCompilerAdapter.java:39)
        at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1153)
        at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:930)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
Caused by: java.lang.ClassNotFoundException: com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at com.google.errorprone.internal.NonDelegatingClassLoader.loadClass(NonDelegatingClassLoader.java:70)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:274)
        at com.google.errorprone.internal.NonDelegatingClassLoaderRunner.run(NonDelegatingClassLoaderRunner.java:35)
        ... 20 more
```

I can reproduce this with a fresh new project where the content of `build.xml` is exactly this:
```
<?xml version="1.0" encoding="UTF-8"?>
<project name="Test" basedir="." default="build">

    <path id="errorprone">
        <pathelement location="error_prone_ant-2.0.1.jar"/>
    </path>

    <target name="build">
        <mkdir dir="bin"/>
        <javac debug="true"
               destdir="bin"
               source="1.7"
               target="1.7"
               compiler="com.google.errorprone.ErrorProneAntCompilerAdapter"
               includeantruntime="false"
               encoding="UTF-8">
            <src path="src"/>
            <compilerclasspath refid="errorprone"/>
        </javac>
    </target>
</project>
```

It works if I specify the directory of the JAR file with `-lib` on the ant command line, but I would prefer to not need this (that is the solution we currently use, but looking at the recent changes to error-prone I assumed that this should no longer be necessary).

**Comment by cushon** [comment]
Is the claim about `compilerclasspath` in ant documentation, or error-prone documentation?

We have to do some non-standard classloading to make error-prone works with JDK7. Using `compilerclasspath` (instead of putting `error_prone_ant.jar` in `$ANT_HOME/lib` or `~/.ant/lib`) changes how ant loads the classes, and breaks some assumptions we make. Error-prone could be fixed, I'm investigating a different solution that will make the hacky classloading unnecessary. I'd prefer to focus on that. Patches are welcome, though :)

Also, I'm not a big ant user - is `compilerclasspath` generally preferred over adding jars to `$ANT_HOME/lib` or `~/.ant/lib`?

**Comment by PhilippWendler** [comment]
I got the claim from the error-prone documentation: http://errorprone.info/installation
I read this as `compilerclasspath` is an alternative to putting it in the Ant lib directory (because if you do the latter, `compilerclasspath` is not needed anymore).

I am not sure about "generally preferred", but I would certainly prefer a solution using `compilerclasspath` because it is the only solution that works without user interaction.
People could check out our project repository and simply run `ant` and benefit from the error-prone checks (we already retrieve the error-prone jar automatically during build).

The alternative is using `ant -lib lib/build`, but you need to manually specify this on every build.
Using `~/.ant/lib` is even more problematic, because every single developer on our project would need to manually remember to replace the error-prone jar on every update.
Plus it can make compiling old revisions of the project impossible if the old code happens to violate a check of a newer error-prone version, making going back in time for debugging more difficult.

In our practice, requiring external developers to do such manual things does not work well, and ends up in code being checked in that fails to compile with error-prone enabled. Our integration testing would find this, but a fully automatic solution would still be nice of course.

**Comment by cushon** [comment]
Thanks, that makes sense. I agree that tools like error-prone are much less useful if everyone has to set them up manually, and also that declaring and versioning all build dependencies is a Good Idea. Using `compilerclasspath` seems like the way to go.

I'll get it working, hopefully by killing off the hacky classloading. But if that doesn't happen soon I'll try to find a work-around.

**Comment by PhilippWendler** [comment]
I can confirm that 5a1706c fixes the issue. Thank you very much.

**Comment by cushon** [comment]
Thanks for testing, I'll merge that in.

I still plan to remove the hacky classloading, but it may take a bit longer.
