### ISSUE TITLE
ClassCastException when compiling:  com.sun.tools.javac.tree.JCTree$JCNewArray cannot be cast to com.sun.source.tree.ModifiersTree

### ISSUE THREAD

**Issue by nogudnik** [google/error-prone#313]
I was testing out a snapshot build with Ant and received the attached error using:

## Environment

* Snapshot version: `error_prone_ant-2.0.2-20150325.171505-20.jar`
*  /opt/java/1.7/bin//javac -fullversion `javac full version "1.7.0_72-b14"`
* ant -version `Apache Ant(TM) version 1.9.4 compiled on April 29 2014` (using `<compilerclasspath/>` to specify the ErrorProne classpath)
* `Debian GNU/Linux 8.0 (x86_64)`

I'm compiling a source tree of about 2800 files, and I don't see an easy way to narrow down which file (and which code fragment) is actually causing the error. I'd be more than happy to try and isolate this if there is way to do that aside from trial and error.

## Stack Trace

    error: An unhandled exception was thrown by the Error Prone static analysis plugin.
           
      error-prone version: 2.0.2-SNAPSHOT
      Stack Trace:
      java.lang.ClassCastException: com.sun.tools.javac.tree.JCTree$JCNewArray cannot be cast to com.sun.source.tree.ModifiersTree
        at com.google.errorprone.bugpatterns.IncompatibleModifiersChecker.matchAnnotation(IncompatibleModifiersChecker.java:94)
        at com.google.errorprone.scanner.ErrorProneScanner.visitAnnotation(ErrorProneScanner.java:462)
        at com.google.errorprone.scanner.ErrorProneScanner.visitAnnotation(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2532)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitNewArray(TreeScanner.java:542)
        at com.google.errorprone.scanner.ErrorProneScanner.visitNewArray(ErrorProneScanner.java:851)
        at com.google.errorprone.scanner.ErrorProneScanner.visitNewArray(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCNewArray.accept(JCTree.java:1722)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.visitAssignment(TreeScanner.java:586)
        at com.google.errorprone.scanner.ErrorProneScanner.visitAssignment(ErrorProneScanner.java:520)
        at com.google.errorprone.scanner.ErrorProneScanner.visitAssignment(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1849)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitAnnotation(TreeScanner.java:832)
        at com.google.errorprone.scanner.ErrorProneScanner.visitAnnotation(ErrorProneScanner.java:465)
        at com.google.errorprone.scanner.ErrorProneScanner.visitAnnotation(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2532)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.visitModifiers(TreeScanner.java:819)
        at com.google.errorprone.scanner.ErrorProneScanner.visitModifiers(ErrorProneScanner.java:840)
        at com.google.errorprone.scanner.ErrorProneScanner.visitModifiers(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCModifiers.accept(JCTree.java:2562)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.visitVariable(TreeScanner.java:221)
        at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:1008)
        at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:939)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:586)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:779)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:80)
        at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:155)
        at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:126)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.postFlow(ErrorProneJavacJavaCompiler.java:118)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.flow(ErrorProneJavacJavaCompiler.java:92)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1272)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:866)
        at com.sun.tools.javac.main.Main.compile(Main.java:249)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:220)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:158)
        at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:87)
        at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:39)
        at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:36)
        at com.google.errorprone.ErrorProneAntCompilerAdapter.execute(ErrorProneAntCompilerAdapter.java:72)
        at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1159)
        at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:935)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

**Comment by cushon** [comment]
Thanks for the report, I was able to repro. I will fix the brittle assumption the check is making.

I'm guessing the specific crash you saw was caused by a nested annotation like: `@Foos({@Foo, @Foo})`.
