### ISSUE TITLE
NullPointerException for ParameterPackage

### ISSUE THREAD

**Issue by gorset** [google/error-prone#330]
error-prone version: 2.0.3
  Stack Trace:
```
  java.lang.NullPointerException
        at com.google.errorprone.bugpatterns.WrongParameterPackage.matchMethod(WrongParameterPackage.java:62)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:823)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:143)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:869)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:120)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:46)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:587)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:143)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:779)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:81)
        at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:137)
        at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:111)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.postFlow(ErrorProneJavacJavaCompiler.java:118)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.flow(ErrorProneJavacJavaCompiler.java:92)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1272)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:866)
        at com.sun.tools.javac.main.Main.compile(Main.java:249)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:220)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:158)
        at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:87)
        at com.google.errorprone.ErrorProneCompiler.main(ErrorProneCompiler.java:63)
```

**Comment by cushon** [comment]
Is the crash reproducible? If it is, can you share the input that caused the crash?

**Comment by gorset** [comment]
Yes, I took a closer now and managed to reduce and reproduce the problem with the following file:
```
package foo;

public interface Bar {
    void bar();
}
```

The command I ran (using java 1.8.0_40 on a mac):
```
java -cp error_prone_ant-2.0.3.jar com.google.errorprone.ErrorProneCompiler -Xep:ParameterPackage:ERROR foo/Bar.java
```

**Comment by cushon** [comment]
That's for taking the time to put together a repro! I have a fix in progress.
