### ISSUE TITLE
java.lang.NoSuchFieldError: bound

### ISSUE THREAD

**Issue by 1mnbvcxz24** [google/error-prone#3401]
Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.9.0
     BugPattern: Nullsafe
     Stack Trace:
     java.lang.NoSuchFieldError: bound
  	at com.facebook.nullsafe.type.Substitution.substBounds(Substitution.java:155)
  	at com.facebook.nullsafe.type.Substitution$Subst.visitForAll(Substitution.java:123)
  	at com.facebook.nullsafe.type.Substitution$Subst.visitForAll(Substitution.java:48)
  	at jdk.compiler/com.sun.tools.javac.code.Type$ForAll.accept(Type.java:1812)
  	at jdk.compiler/com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4857)
  	at jdk.compiler/com.sun.tools.javac.code.Type.map(Type.java:310)
  	at com.facebook.nullsafe.type.Substitution.subst(Substitution.java:33)
  	at com.facebook.nullsafe.type.Substitution.subst(Substitution.java:27)
  	at com.facebook.nullsafe.type.TypeFactory.lambda$substExecutable$4(TypeFactory.java:239)
  	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
  	at com.facebook.nullsafe.type.TypeFactory.substExecutable(TypeFactory.java:236)
  	at com.facebook.nullsafe.nullability.NullsafeTransferFunction.inferMethodType(NullsafeTransferFunction.java:428)
  	at com.facebook.nullsafe.nullability.NullsafeTransferFunction.visitMethodInvocation(NullsafeTransferFunction.java:481)
  	at com.facebook.nullsafe.nullability.NullsafeTransferFunction.visitMethodInvocation(NullsafeTransferFunction.java:33)
  	at org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:121)
  	at org.checkerframework.dataflow.analysis.AbstractAnalysis.callTransferFunction(AbstractAnalysis.java:357)
  	at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.callTransferFunction(ForwardAnalysisImpl.java:391)
  	at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysisBlock(ForwardAnalysisImpl.java:157)
  	at org.checkerframework.dataflow.analysis.ForwardAnalysisImpl.performAnalysis(ForwardAnalysisImpl.java:110)
  	at com.facebook.nullsafe.nullability.Driver.analyseExecutable(Driver.java:199)
  	at com.facebook.nullsafe.nullability.Driver.fetchAnalysis(Driver.java:209)
  	at com.facebook.nullsafe.nullability.Driver.requireAnalysis(Driver.java:168)
  	at com.facebook.nullsafe.nullability.Driver.getType(Driver.java:92)
  	at com.facebook.nullsafe.NullsafeTreeScanner.requireType(NullsafeTreeScanner.java:94)
  	at com.facebook.nullsafe.nullability.TypeChecker.handleAssignment(TypeChecker.java:689)
  	at com.facebook.nullsafe.nullability.TypeChecker.visitVariable(TypeChecker.java:878)
  	at com.facebook.nullsafe.nullability.TypeChecker.visitVariable(TypeChecker.java:47)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:990)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.facebook.nullsafe.NullsafeTreeScanner.scan(NullsafeTreeScanner.java:236)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  	at com.facebook.nullsafe.NullsafeTreeScanner.visitBlock(NullsafeTreeScanner.java:166)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1048)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.facebook.nullsafe.NullsafeTreeScanner.scan(NullsafeTreeScanner.java:236)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
  	at com.facebook.nullsafe.NullsafeTreeScanner.visitMethod(NullsafeTreeScanner.java:185)
  	at com.facebook.nullsafe.nullability.TypeChecker.visitMethod(TypeChecker.java:348)
  	at com.facebook.nullsafe.nullability.TypeChecker.visitMethod(TypeChecker.java:47)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.facebook.nullsafe.NullsafeTreeScanner.scan(NullsafeTreeScanner.java:236)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.facebook.nullsafe.NullsafeTreeScanner.visitClass(NullsafeTreeScanner.java:192)
  	at com.facebook.nullsafe.nullability.TypeChecker.visitClass(TypeChecker.java:234)
  	at com.facebook.nullsafe.nullability.TypeChecker.visitClass(TypeChecker.java:47)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.facebook.nullsafe.NullsafeTreeScanner.scan(NullsafeTreeScanner.java:236)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.facebook.nullsafe.NullsafeTreeScanner.scan(NullsafeTreeScanner.java:159)
  	at com.facebook.nullsafe.NullsafeTreeScanner.check(NullsafeTreeScanner.java:144)
  	at com.facebook.nullsafe.NullsafeChecker.matchCompilationUnit(NullsafeChecker.java:75)
  	at com.facebook.nullsafe.NullsafeScannerTransformer.scanCompilationUnit(NullsafeScannerTransformer.java:95)
  	at com.facebook.nullsafe.NullsafeScannerTransformer.apply(NullsafeScannerTransformer.java:46)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1414)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1361)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at com.facebook.buck.jvm.java.plugin.adapter.JavacTaskWrapper.call(JavacTaskWrapper.java:100)
  	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTask.call(BuckJavacTask.java:52)
  	at com.facebook.buck.jvm.java.plugin.adapter.BuckJavacTaskProxyImpl.call(BuckJavacTaskProxyImpl.java:134)
  	at com.facebook.buck.jvm.java.Jsr199JavacInvocation$CompilerWorker.runCompilerTask(Jsr199JavacInvocation.java:469)
  	at com.facebook.buck.jvm.java.Jsr199JavacInvocation$CompilerWorker.lambda$startCompiler$2(Jsr199JavacInvocation.java:452)
  	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
  	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
  	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  	at java.base/java.lang.Thread.run(Thread.java:829)
Errors: 1. Warnings: 0.

    When running <javacd>.

**Comment by cushon** [comment]
```
 java.lang.NoSuchFieldError: bound
at com.facebook.nullsafe.type.Substitution.substBounds(Substitution.java:155)
```

This is a bug in `com.facebook.nullsafe.type`, not in core Error Prone.

The fix is probably the same as https://github.com/google/error-prone/commit/3c3c7979c260861e93154a52476df7bc0eb26127, i.e.

```diff
-type.bound
+type. getUpperBound()
```
