### ISSUE TITLE
Development questions

### ISSUE THREAD

**Issue by JeffreyFalgout** [google/error-prone#346]
I'm starting to poke around and I'm thinking about contributing, but I have a few questions.

 - Do you prefer a squashed commit for PRs?
 - I would like to use Eclipse as my IDE, but I've hit a couple snags:
   - tests/.../bugpatterns/testdata is excluded by default. Is there a way to keep it excluded (so the files don't get compiled), but still view it in the project? I would like to view/edit positive/negative test cases in Eclipse, if at all possible
   - Running Eclipse's JUnit runner results in a bunch of exceptions. I'm assuming it's because eclipse's compiler is different? If I run `mvn test` everything works correctly.
````
java.lang.NoSuchFieldError: NATIVE_HEADER_OUTPUT
	at com.sun.tools.javac.file.Locations.initHandlers(Locations.java:689)
	at com.sun.tools.javac.file.Locations.<init>(Locations.java:98)
	at com.sun.tools.javac.util.BaseFileManager.createLocations(BaseFileManager.java:88)
	at com.sun.tools.javac.util.BaseFileManager.<init>(BaseFileManager.java:73)
	at com.sun.tools.javac.nio.JavacPathFileManager.<init>(JavacPathFileManager.java:115)
	at com.google.errorprone.ErrorProneInMemoryFileManager.<init>(ErrorProneInMemoryFileManager.java:70)
	at com.google.errorprone.ErrorProneInMemoryFileManager.<init>(ErrorProneInMemoryFileManager.java:66)
	at com.google.errorprone.CompilationTestHelper.<init>(CompilationTestHelper.java:64)
	at com.google.errorprone.CompilationTestHelper.newInstance(CompilationTestHelper.java:94)
	at com.google.errorprone.bugpatterns.NonnullTest.setUp(NonnullTest.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
````
````
Luna Service Release 1 (4.4.1)
Build id: 20140925-1800
Eclipse Java Development Tools
Version: 3.10.0.v20140925-0400
Build id: M20140925-0400
````
````
$ java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
````
````
$ uname -a
Linux prowl 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
````

**Comment by eaftan** [comment]
Hi Jeffrey,

> Do you prefer a squashed commit for PRs?

Yes, squashed commit please.

> tests/.../bugpatterns/testdata is excluded by default. Is there a way to keep it excluded (so the files don't get compiled), but still view it in the project? I would like to view/edit positive/negative test cases in Eclipse, if at all possible

You should be able to see them as resources.  Try "Open Resource" (Ctrl+Shift+R) to open the Postitive/Negative test case files.  If not, did you do anything that was not the default when you imported the Maven project into Eclipse?  

> Running Eclipse's JUnit runner results in a bunch of exceptions. I'm assuming it's because eclipse's compiler is different? If I run mvn test everything works correctly.

I can repro this on my Mac.  I'll take a look.

**Comment by eaftan** [comment]
> Running Eclipse's JUnit runner results in a bunch of exceptions. I'm assuming it's because eclipse's compiler is different? If I run mvn test everything works correctly.

Figured it out.  Error Prone is built on javac 9, so it requires library classes that are in Java 9. To get around this, we distribute a jar of javac 9 and depend on it for Error Prone.

For the tests to execute correctly, you have to put our javac 9 jar on the bootclasspath when you execute them.  We do this in the maven config here:
https://github.com/google/error-prone/blob/master/core/pom.xml#L220

Eclipse doesn't pick that up and doesn't set up the bootclasspath correctly when executing tests.  To fix it, you can do into the run/debug configuration, select the Classpath tab, and add our javac 9 jar to the Bootstrap Entries.  Our javac 9 jar should be in your maven local repo, at a path like ~/.m2/repository/com/google/errorprone/javac/1.9.0-dev-r2644-1/javac-1.9.0-dev-r2644-1-sources.jar.

Let me know if you're still having trouble.  I'll add this to the setup instructions tomorrow.  And thanks for pointing this out.

**Comment by JeffreyFalgout** [comment]
I added the javac9 jar to the bootstrap classpath but I'm getting the same errors. I tried putting it above and below the JRE and I tried javac-**-sources.jar and the non-sources javac-**.jar

**Comment by don-vip** [comment]
I failed to run unit tests from Eclipse with Java 8 too. The only way I found was to run it with Java 9 (with Eclipse 4.7rc and Java 9 beta support + JVM option `--permit-illegal-access`)
