### ISSUE TITLE
[2.17.0] NonCanonicalType NPE

### ISSUE THREAD

**Issue by ben-manes** [google/error-prone#3639]
```
> Task :caffeine:compileJava FAILED
/Users/ben/projects/caffeine/caffeine/src/main/java/module-info.java:5: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
  requires static com.google.errorprone.annotations;
                                       ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.17.0
     BugPattern: NonCanonicalType
     Stack Trace:
     java.lang.NullPointerException
        at com.google.errorprone.bugpatterns.NonCanonicalType.canonicalName(NonCanonicalType.java:92)
        at com.google.errorprone.bugpatterns.NonCanonicalType.matchMemberSelect(NonCanonicalType.java:53)
        at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:726)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMemberSelect(ErrorProneScanner.java:150)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2138)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitRequires(TreeScanner.java:880)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCRequires.accept(JCTree.java:2873)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitModule(TreeScanner.java:853)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCModuleDecl.accept(JCTree.java:2722)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
```

**Comment by uhafner** [comment]
I can confirm this bug as well:

https://github.com/uhafner/codingstyle/actions/runs/3809734438/jobs/6481297724

**Comment by ben-manes** [comment]
Thanks @cushon!
