### ISSUE TITLE
 java.lang.StringIndexOutOfBoundsException: start > end

### ISSUE THREAD

**Issue by zorzella** [google/error-prone#368]
As requested, here is a bug report for an AssertionError.

I think the error is happening because I remove a method from a class, and then replace the class itself, which I though was ok, but apparently is not properly handled. E.g.:

new Runnable() {
  public void run() {}
}

If I both issue a "delete" on the "run" method node and a replace on the "new Runnable()" node, the tool barfs.

************************************************************************************
java.lang.AssertionError: An unhandled exception was thrown by the Error Prone static analysis plugin.
  Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
  error-prone version: unknown version
  Stack Trace:
  java.lang.StringIndexOutOfBoundsException: start > end
  	at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:828)
  	at java.lang.StringBuilder.replace(StringBuilder.java:262)
  	at com.google.errorprone.fixes.AppliedFix$Applier.apply(AppliedFix.java:68)
  	at com.google.errorprone.JavacErrorDescriptionListener$1.apply(JavacErrorDescriptionListener.java:51)
  	at com.google.errorprone.JavacErrorDescriptionListener$1.apply(JavacErrorDescriptionListener.java:48)
  	at com.google.common.collect.Iterators$9.transform(Iterators.java:857)
  	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
  	at com.google.common.collect.Iterators$8.computeNext(Iterators.java:716)
  	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
  	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
  	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:249)
  	at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:211)
  	at com.google.common.collect.FluentIterable.toList(FluentIterable.java:616)
  	at com.google.errorprone.JavacErrorDescriptionListener.onDescribed(JavacErrorDescriptionListener.java:81)
  	at com.google.errorprone.VisitorState.reportMatch(VisitorState.java:141)
  	at com.google.errorprone.scanner.Scanner.reportMatch(Scanner.java:161)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:855)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1675)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:510)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:825)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1614)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
  	at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:434)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:677)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1424)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:249)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:542)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:996)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:207)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:814)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:586)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:249)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:542)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:996)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:207)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:814)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:586)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:597)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:142)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:70)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:45)
  	at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:160)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:115)
  	at com.google.errorprone.ErrorProneJavacJavaCompiler.postFlow(ErrorProneJavacJavaCompiler.java:123)
  	at com.google.errorprone.ErrorProneJavacJavaCompiler.flow(ErrorProneJavacJavaCompiler.java:97)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1247)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:858)
  	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:97)
  	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
  	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:287)
  	at com.google.errorprone.CompilationTestHelper.compile(CompilationTestHelper.java:275)
  	at com.google.errorprone.CompilationTestHelper.doTest(CompilationTestHelper.java:236)
  	at com.google.devtools.staticanalysis.errorprone.GbmCheckerTest.testPositiveCase(GbmCheckerTest.java:24)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:483)
  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:49)
  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:273)
  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:240)
  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:65)
  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:238)
  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:55)
  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:231)
  	at org.junit.runners.ParentRunner.run(ParentRunner.java:316)
  	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
  	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
  	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
  	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
  	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
  	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
	at org.junit.Assert.fail(Assert.java:88)
	at com.google.errorprone.CompilationTestHelper.doTest(CompilationTestHelper.java:239)
	at com.google.devtools.staticanalysis.errorprone.GbmCheckerTest.testPositiveCase(GbmCheckerTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:49)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:273)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:240)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:65)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:238)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:55)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:231)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:316)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

[... removed content with my test cases from here. Reach out to me if you really need it ...]

	at org.junit.Assert.fail(Assert.java:88)
	at com.google.errorprone.DiagnosticTestHelper.assertHasDiagnosticOnAllMatchingLines(DiagnosticTestHelper.java:344)
	at com.google.errorprone.CompilationTestHelper.doTest(CompilationTestHelper.java:252)
	at com.google.devtools.staticanalysis.errorprone.GbmCheckerTest.testPositiveCase(GbmCheckerTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:49)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:273)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:240)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:65)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:238)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:55)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:231)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:316)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

token.comments.get(0).getSourcePos(0)
	Evaluation failed. Reason(s):
		An exception occurred: java.lang.NullPointerException
	 null
	 
	Evaluation failed. Reason(s):
		The method getText() is undefined for the type Object

token.comments
	 (com.sun.tools.javac.util.List<A>) com.sun.tools.javac.parser.JavadocTokenizer$JavadocComment@df4b72
	 (com.sun.tools.javac.parser.Tokens$Token) com.sun.tools.javac.parser.Tokens$Token@721eb7df

invocation.meth
constructorParams.serviceClasses.
	 (com.sun.tools.javac.tree.JCTree$JCMethodInvocation) Lists.<Class<?>>newArrayList(serviceClass, otherServiceClass)

**Comment by cushon** [comment]
As discussed offline, the delete/replace combo should be fine. The issues here are:

* SuggestedFix doesn't validate its input very well, and allows edits on synthetic default constructors (which are created early enough that they're in the AST when Error Prone runs, sadly)

* getTokensForNode doesn't work with comment tokens

I have fixes out for review.

**Comment by cushon** [comment]
Fixed by bf6387bf622e6e4c08cc3a0d4aa8255b324dda34, aab5bf5573f60949403deb6d04bccf34012ffb7e.
