### ISSUE TITLE
java.lang.NoClassDefFoundError: org/checkerframework/dataflow/analysis/TransferFunction

### ISSUE THREAD

**Issue by ejbartelds** [google/error-prone#374]
From within IntelliJ IDEA 15.0 #IU-143.381:

Error:java: An unhandled exception was thrown by the Error Prone static analysis plugin.
  Please report this at https://code.google.com/p/error-prone/issues/entry and include the following:

  error-prone version: 1.1.3-SNAPSHOT
  Stack Trace:
  java.lang.NoClassDefFoundError: org/checkerframework/dataflow/analysis/TransferFunction
    at com.google.errorprone.bugpatterns.StringEquality.isNonNull(StringEquality.java:143)
    at com.google.errorprone.bugpatterns.StringEquality.access$100(StringEquality.java:53)
    at com.google.errorprone.bugpatterns.StringEquality$3.apply(StringEquality.java:108)
    at com.google.errorprone.bugpatterns.StringEquality$3.apply(StringEquality.java:105)
    at com.google.errorprone.bugpatterns.StringEquality.considerOneOf(StringEquality.java:138)
    at com.google.errorprone.bugpatterns.StringEquality.matchBinary(StringEquality.java:104)
    at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:502)
    at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:138)
    at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1795)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:117)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
    at com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:271)
    at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:803)
    at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:138)
    at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1477)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:117)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
    at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:243)
    at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:655)
    at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:138)
    at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1302)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:117)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
    at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
    at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:516)
    at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:138)
    at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:117)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
    at com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:238)
    at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:688)
    at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:138)
    at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1277)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:117)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
    at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
    at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:516)
    at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:138)
    at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:117)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
    at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:144)
    at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:792)
    at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:138)
    at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:117)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
    at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
    at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
    at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
    at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:560)
    at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:138)
    at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
    at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
    at com.google.errorprone.scanner.Scanner.scan(Scanner.java:78)
    at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:161)
    at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:132)
    at com.google.errorprone.ErrorProneJavacJavaCompiler.postFlow(ErrorProneJavacJavaCompiler.java:126)
    at com.google.errorprone.ErrorProneJavacJavaCompiler.flow(ErrorProneJavacJavaCompiler.java:98)
    at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
    at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
    at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:168)
    at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:385)
    at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:286)
    at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:194)
    at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:166)
    at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1230)
    at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:904)
    at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:976)
    at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:870)
    at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:695)
    at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:386)
    at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:193)
    at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:137)
    at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:294)
    at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
    at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:232)
    at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:42)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
  Caused by: java.lang.ClassNotFoundException: org.checkerframework.dataflow.analysis.TransferFunction
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 102 more

**Comment by cushon** [comment]
Thanks for the report. That's a very old version of Error Prone, so it looks like we need to update the intellij plugin.

**Comment by ejbartelds** [comment]
Liam, thanks for your comment. 

You got me confused, though. Shouldn't Intellij rather than you update their "Error-prone Compiler Integration" plugin?  It came with the new IDE version, out of the box. In my IDEA installation, the installed plugin page reports a version "139.887"

**Comment by simon04** [comment]
@ejbartelds is referring to this plugin https://plugins.jetbrains.com/plugin/7349

is this plugin managed by JetBrains or by Google? Is there an obstacle updating the contained error-prone version?

I looked at the code at https://github.com/google/error-prone/tree/master/idea_plugin and tried to compile the plugin on my own – without immediate success. Is there any documentation how to?

**Comment by cushon** [comment]
I'd forgotten what the status of the plugin was. Here's some of the history: https://groups.google.com/d/topic/error-prone-discuss/p7nqreAhE6M/discussion

The copy in our repo is obsolete, the new(er) code is here: https://github.com/JetBrains/intellij-plugins/tree/master/error-prone
