### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by daemonjax** [google/error-prone#3752]
Using Ant in Netbeans, jdk 17... A simple project that may as well be hello world as far as this thing is concerned.

Output:

Compiling 11 source files to F:\_SOURCE_CODE\Java\FileDiff\build
     error: An unhandled exception was thrown by the Error Prone static analysis plugin.
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.9.0
     BugPattern: (see stack trace)
     Stack Trace:
     java.lang.NoClassDefFoundError: edu/umd/cs/findbugs/formatStringChecker/MissingFormatArgumentException
  	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
  	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
  	at java.base/java.lang.Class.getConstructors(Class.java:2060)
  	at com.google.errorprone.scanner.ScannerSupplierImpl.instantiateChecker(ScannerSupplierImpl.java:69)
  	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
  	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
  	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
  	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
  	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
  	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
  	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:102)
  	at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:40)
  	at com.google.errorprone.ErrorProneAnalyzer.lambda$scansPlugins$0(ErrorProneAnalyzer.java:79)
  	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
  	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
  	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
  	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
  Caused by: java.lang.ClassNotFoundException: edu.umd.cs.findbugs.formatStringChecker.MissingFormatArgumentException
  	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
  	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
  	... 24 more
1 error
printing javac parameters to: F:\_SOURCE_CODE\Java\FileDiff\javac.20230202_124420.args
F:\_SOURCE_CODE\Java\FileDiff\build.xml:80: Compile failed; see the compiler error output for details.

-----------------------------------------------------------------------------------------------------------------------------

Here's the code I added to my project's build.xml as per installation instructions:

```

<path id="processorpath.ref">
      <pathelement location="F:/_SOURCE_CODE/Java/Google Error Prone/error_prone_core-2.9.0-with-dependencies.jar"/>
      <pathelement location="F:/_SOURCE_CODE/Java/Google Error Prone/dataflow-errorprone-3.15.0.jar"/>
</path>

<javac srcdir="src" destdir="build" fork="yes" includeantruntime="no">
      <compilerarg value="-XDcompilePolicy=simple"/>
      <compilerarg value="-processorpath"/>
      <compilerarg pathref="processorpath.ref"/>
      <compilerarg value="-Xplugin:ErrorProne -Xep:DeadException:ERROR" />
      <compilerarg value="-J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED" />
      <compilerarg value="-J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED" />
      <compilerarg value="-J--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED" />
      <compilerarg value="-J--add-exports=jdk.compiler/com.sun.tools.javac.model=ALL-UNNAMED" />
      <compilerarg value="-J--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED" />
      <compilerarg value="-J--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED" />
      <compilerarg value="-J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED" />
      <compilerarg value="-J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED" />
      <compilerarg value="-J--add-opens=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED" />
      <compilerarg value="-J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED" />
</javac>

```

**Comment by cushon** [comment]
You're missing a dependency on jFormatString, which was mentioned in [old versions of the installation instructions](https://github.com/google/error-prone/commit/5c1a43a9c44c77b92fc72059bed681db5be3fc91?short_path=8b042e3#diff-8b042e3f94ca5c59a7cd990b950aec0073ea84fe811e7b22be51158d7b180d56).

Error Prone 2.9.0 is an old release, that dependency isn't needed for newer versions. I recommend upgrading to the latest version.
