### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin.

### ISSUE THREAD

**Issue by cjanes-interval** [google/error-prone#3758]
We've encountered the following error when running Error Prone against our codebase for the first time.

```
error-prone version: 2.8.1
   BugPattern: UnusedVariable
   Stack Trace:
   java.lang.IndexOutOfBoundsException
 at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:611)
 at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:41)
 at com.google.errorprone.VisitorState.getOffsetTokens(VisitorState.java:589)
 at com.google.errorprone.fixes.SuggestedFixes.replaceIncludingComments(SuggestedFixes.java:1543)
 at com.google.errorprone.bugpatterns.UnusedVariable.buildUnusedVarFixes(UnusedVariable.java:385)
 at com.google.errorprone.bugpatterns.UnusedVariable.matchCompilationUnit(UnusedVariable.java:234)
 at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:450)
 at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:556)
 at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:151)
 at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
 at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
 at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
 at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
 at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
 at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
 at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
 at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
 at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
 at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
 at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
 at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
 at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
 at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:237)
 at org.jetbrains.jps.incremental.java.JavaBuilder.lambda$compileJava$2(JavaBuilder.java:524)
 at org.jetbrains.jps.incremental.java.JavaBuilder.invokeJavac(JavaBuilder.java:587)
 at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:522)
 at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:365)
 at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:290)
 at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:244)
 at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1523)
 at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:1153)
 at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1303)
 at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:1118)
 at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:889)
 at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:471)
 at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:197)
 at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:150)
 at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:357)
 at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:179)
 at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:218)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

**Comment by Stephan202** [comment]
@cjanes-interval this looks like a [duplicate](https://github.com/google/error-prone/search?q=HeapCharBuffer.java%3A611&type=issues) of a few other issues. The issue might be due to Lombok. Regardless: version 2.8.1 is 1.5 years old; consider upgrading to the latest release (2.18.0 at the time of writing).

**Comment by cjanes-interval** [comment]
Thanks @Stephan202 - I just downloaded the 'Error Prone Compiler' plug-in form Jetbrains which must be using an older version. I'll upgrade and try again.
