### ISSUE TITLE
StatementSwitchToExpressionSwitch jdk17 IllegalAccessError

### ISSUE THREAD

**Issue by delanym** [google/error-prone#3781]
Take the reproducer in #3780 and change the Maven compiler release version to 17. Run `.\mvnw` and you'll get this 

``` 
An exception has occurred in the compiler (17.0.5). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java 
compiler in your report. Thank you.
java.lang.IllegalAccessError: class com.google.errorprone.BaseErrorProneJavaCompiler (in unnamed module @0x7be1ce6a) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x7be1ce6a
        at com.google.errorprone.BaseErrorProneJavaCompiler.addTaskListener(BaseErrorProneJavaCompiler.java:95)
        at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:34)
        at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:255)
```

**Comment by delanym** [comment]
Yip
