### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: start > end

### ISSUE THREAD

**Issue by koozz** [google/error-prone#383]
Could it be that this error is caused by this maven module's lack of src/main/java files? It only has src/test/java.

```
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ cucumber ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 92 source files to /Users/jan/projects/cucumber/target/test-classes
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
  Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
  error-prone version: 2.0.1
  Stack Trace:
  java.lang.StringIndexOutOfBoundsException: start > end
        at java.lang.AbstractStringBuilder.replace(AbstractStringBuilder.java:828)
        at java.lang.StringBuilder.replace(StringBuilder.java:262)
        at com.google.errorprone.fixes.AppliedFix$Applier.apply(AppliedFix.java:68)
        at com.google.errorprone.JavacErrorDescriptionListener$1.apply(JavacErrorDescriptionListener.java:51)
        at com.google.errorprone.JavacErrorDescriptionListener$1.apply(JavacErrorDescriptionListener.java:48)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:268)
        at com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:226)
        at com.google.common.collect.FluentIterable.toList(FluentIterable.java:373)
        at com.google.errorprone.JavacErrorDescriptionListener.onDescribed(JavacErrorDescriptionListener.java:77)
        at com.google.errorprone.VisitorState.reportMatch(VisitorState.java:113)
        at com.google.errorprone.scanner.Scanner.reportMatch(Scanner.java:153)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:528)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1795)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.visitConditionalExpression(TreeScanner.java:229)
        at com.google.errorprone.scanner.ErrorProneScanner.visitConditionalExpression(ErrorProneScanner.java:624)
        at com.google.errorprone.scanner.ErrorProneScanner.visitConditionalExpression(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCConditional.accept(JCTree.java:1245)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:255)
        at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:909)
        at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1390)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:162)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:542)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:918)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
        at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:144)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:818)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
        at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:586)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:119)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:81)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
        at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:586)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:80)
        at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:152)
        at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:123)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.postFlow(ErrorProneJavacJavaCompiler.java:118)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.flow(ErrorProneJavacJavaCompiler.java:92)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1296)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.main.Main.compile(Main.java:381)
        at com.sun.tools.javac.main.Main.compile(Main.java:370)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:220)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:158)
        at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:87)
        at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:825)
        at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:153)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
1 error
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by cushon** [comment]
2.0.1 is an old release, does it repro with 2.0.7?

You can override the version of Error Prone that the maven plugins uses:

```xml
<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <version>3.1</version>
      <configuration>
        <compilerId>javac-with-errorprone</compilerId>
        <forceJavacCompilerUse>true</forceJavacCompilerUse>
      </configuration>
      <dependencies>
        <dependency>
          <groupId>org.codehaus.plexus</groupId>
          <artifactId>plexus-compiler-javac-errorprone</artifactId>
          <version>2.5</version>
        </dependency>
        <!-- override plexus-compiler-javac-errorprone's dependency on
             Error Prone with the latest version -->
        <dependency>
          <groupId>com.google.errorprone</groupId>
          <artifactId>error_prone_core</artifactId>
          <version>2.0.7</version>
        </dependency>
      </dependencies>
    </plugin>
  </plugins>
</build>
```

**Comment by koozz** [comment]
That did the trick for this issue. The dependency override was not in the docs where I grabbed the example from, maybe the docs can be update to prevent 'old' issues from being reported.

Thanks for the quick response and the feedback that made me post an issue.

**Comment by cushon** [comment]
I'm glad that worked. I fixed the instructions in the README and at http://errorprone.info/docs/installation. Did you use one of those examples, or are there more docs to update?
