### ISSUE TITLE
bogus NoSuchMethodError throw by NullnessPropagationTransfer for valid call to guava ImmutableSet.of

### ISSUE THREAD

**Issue by ispringer** [google/error-prone#386]
The below exception is thrown by errorprone 2.0.8 for the following valid line of code:

```
public static final ImmutableSet<String> PARAMS =
            ImmutableSet.of(PARAM1, PARAM2, PARAM3, PARAM4, PARAM5, PARAM6);
```

The exception is only thrown when I use maven-compiler-plugin 3.5. When I switch to maven-compiler-plugin 3.3, the exception does not occur. So I'm not sure if it's a but in errorprone or the maven-compiler-plugin.

```
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableSet.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Lcom/google/common/collect/ImmutableSet;
    at com.google.errorprone.dataflow.nullnesspropagation.NullnessPropagationTransfer$ReturnValueIsNonNull.<clinit>(NullnessPropagationTransfer.java:152) ~[na:na]
    at com.google.errorprone.dataflow.nullnesspropagation.NullnessPropagationTransfer.<init>(NullnessPropagationTransfer.java:227) ~[na:na]
    at com.google.errorprone.dataflow.nullnesspropagation.NullnessAnalysis.<init>(NullnessAnalysis.java:50) ~[na:na]
    at com.google.errorprone.bugpatterns.OptionalEquality.<init>(OptionalEquality.java:54) ~[na:na]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_71]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_71]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_71]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_71]
    at java.lang.Class.newInstance(Class.java:442) ~[na:1.8.0_71]
    at com.google.errorprone.scanner.ScannerSupplierImpl$1.apply(ScannerSupplierImpl.java:58) ~[na:na]
    at com.google.errorprone.scanner.ScannerSupplierImpl$1.apply(ScannerSupplierImpl.java:54) ~[na:na]
    at com.google.common.collect.Iterators$8.next(Iterators.java:697) ~[guava-18.0.jar:na]
    at com.google.errorprone.scanner.ErrorProneScanner.<init>(ErrorProneScanner.java:184) ~[na:na]
    at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:68) ~[na:na]
    at com.google.errorprone.scanner.ScannerSupplierImpl.get(ScannerSupplierImpl.java:38) ~[na:na]
    at com.google.errorprone.ErrorProneCompiler.prepareCompilation(ErrorProneCompiler.java:230) ~[na:na]
    at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:242) ~[na:na]
    at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:159) ~[na:na]
    at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:88) ~[na:na]
    at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219) ~[na:na]
    ... 29 common frames omitted
```

**Comment by cushon** [comment]
Thanks for the report. Can you provide a full repro?

**Comment by cushon** [comment]
(I tried using the OptionalEquality check at `2.0.8` and didn't see a crash.)

**Comment by ispringer** [comment]
It looks like it's actually this line in NullnessPropagationTransfer.java that's causing the exception:
```
 private static final ImmutableSet<String> CLASSES_WITH_NON_NULLABLE_RETURNS =
        ImmutableSet.of(
            Optional.class.getName(),
            Preconditions.class.getName(),
            Verify.class.getName(),
            String.class.getName(),
            BigInteger.class.getName(),
            BigDecimal.class.getName(),
            UnsignedInteger.class.getName(),
            UnsignedLong.class.getName());
```
Unfortunately, I haven't been able to reproduce the exception with a stripped down test case. I will attach my test case anyway in case you can think of anything to change that might cause the exception.

**Comment by eaftan** [comment]
I'm suspicious that we've got multiple versions of Guava on the classpath.  In ancient versions of Guava (<=2.0), there was no `ImmutableSet.of` method with parameters `E, E, E, E, E, E, E...`.  Instead, there was a single varargs version:

```java
public static <E> ImmutableSet<E> of(E... elements);
```

**Comment by ispringer** [comment]
I should also note that I built errorprone 2.0.8 myself, in case it's relevant. I checked out the v2.0.8 tag then ran mvn install. I'm using Oracle JDK8 on Max OS X.

**Comment by cushon** [comment]
Any chance your project depends somehow on guava <= 2.0, and that's getting onto the compiler's classpath? Does `mvn dependency:tree -Dverbose -Dincludes=com.google.guava` show anything interesting?

**Comment by ispringer** [comment]
The module where I saw the error has no other guava deps besides our project's guava 18.0 dep (which is under dependency management). But the exception occurs within errorprone itself, which is running within a plugin classloader scope, not my project's scope. Perhaps the compiler plugin scope is somehow getting polluted.

**Comment by cushon** [comment]
I'm closing this as obsolete, but if anyone reading this is still experiencing the issue please re-open and provide a repro.
