### ISSUE TITLE
JDK 21 compatibility issue

### ISSUE THREAD

**Issue by wendigo** [google/error-prone#3926]
```
error-prone version: 2.19.1
Error:       BugPattern: (see stack trace)
Error:       Stack Trace:
Error:       java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree$JCExpression com.sun.tools.javac.tree.TreeMaker.Select(com.sun.tools.javac.tree.JCTree$JCExpression, com.sun.tools.javac.code.Symbol)'
Error:    	at org.checkerframework.errorprone.javacutil.trees.TreeBuilder.buildIteratorMethodAccess(TreeBuilder.java:122)
Error:    	at org.checkerframework.errorprone.dataflow.cfg.builder.CFGTranslationPhaseOne.visitEnhancedForLoop(CFGTranslationPhaseOne.java:2728)
Error:    	at org.checkerframework.errorprone.dataflow.cfg.builder.CFGTranslationPhaseOne.visitEnhancedForLoop(CFGTranslationPhaseOne.java:197)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1248)
Error:    	at org.checkerframework.errorprone.dataflow.cfg.builder.CFGTranslationPhaseOne.scan(CFGTranslationPhaseOne.java:550)
Error:    	at org.checkerframework.errorprone.dataflow.cfg.builder.CFGTranslationPhaseOne.visitBlock(CFGTranslationPhaseOne.java:2206)
Error:    	at org.checkerframework.errorprone.dataflow.cfg.builder.CFGTranslationPhaseOne.visitBlock(CFGTranslationPhaseOne.java:197)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1100)
Error:    	at org.checkerframework.errorprone.dataflow.cfg.builder.CFGTranslationPhaseOne.scan(CFGTranslationPhaseOne.java:550)
Error:    	at org.checkerframework.errorprone.dataflow.cfg.builder.CFGTranslationPhaseOne.process(CFGTranslationPhaseOne.java:447)
Error:    	at org.checkerframework.errorprone.dataflow.cfg.builder.CFGTranslationPhaseOne.process(CFGTranslationPhaseOne.java:498)
Error:    	at org.checkerframework.errorprone.dataflow.cfg.builder.CFGBuilder.build(CFGBuilder.java:70)
Error:    	at com.google.errorprone.dataflow.DataFlow$2.load(DataFlow.java:125)
Error:    	at com.google.errorprone.dataflow.DataFlow$2.load(DataFlow.java:93)
Error:    	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:197)
Error:    	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2451)
Error:    	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
Error:    	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2449)
Error:    	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2432)
Error:    	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:107)
Error:    	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:57)
Error:    	at com.google.errorprone.dataflow.DataFlow.methodDataflow(DataFlow.java:172)
Error:    	at com.google.errorprone.dataflow.DataFlow.expressionDataflow(DataFlow.java:229)
Error:    	at com.google.errorprone.dataflow.nullnesspropagation.NullnessAnalysis.getNullness(NullnessAnalysis.java:59)
Error:    	at com.google.errorprone.bugpatterns.AbstractReferenceEquality.getNullness(AbstractReferenceEquality.java:224)
Error:    	at com.google.errorprone.bugpatterns.AbstractReferenceEquality.addFixes(AbstractReferenceEquality.java:128)
Error:    	at com.google.errorprone.bugpatterns.AbstractReferenceEquality.matchBinary(AbstractReferenceEquality.java:83)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:512)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2186)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitBinary(TreeScanner.java:721)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:513)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2186)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitBinary(TreeScanner.java:721)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:513)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:2186)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitParenthesized(TreeScanner.java:661)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitParenthesized(ErrorProneScanner.java:799)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitParenthesized(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:2042)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:485)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:654)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1585)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1100)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:740)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:944)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:851)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:152)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:619)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:66)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
Error:    	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
Error:    	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:156)
Error:    	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:133)
Error:    	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1412)
Error:    	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1359)
Error:    	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:951)
Error:    	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
Error:    	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
Error:    	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
Error:    	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
Error:    	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:136)
Error:    	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:183)
Error:    	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1140)
Error:    	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:193)
Error:    	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
Error:    	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
Error:    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
Error:    	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:193)
Error:    	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:180)
Error:    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Error:    	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
Error:    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
Error:    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
Error:    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:[642](https://github.com/trinodb/trino/actions/runs/5000975710/jobs/8959063923?pr=17520#step:5:643))
Error:    	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by cushon** [comment]
https://github.com/google/error-prone/issues/3843
