### ISSUE TITLE
IllegalAccessError with no bug pattern or module name

### ISSUE THREAD

**Issue by yougogirl** [google/error-prone#4041]
```
 error-prone version: 2.20.0
     BugPattern: (see stack trace)
     Stack Trace:
     java.lang.IllegalAccessError: class com.google.errorprone.VisitorState$SharedState (in unnamed module @0x7dfb98b7) cannot access class com.sun.tools.javac.comp.Modules (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.comp to unnamed module @0x7dfb98b7
  	at com.google.errorprone.VisitorState$SharedState.<init>(VisitorState.java:762)
  	at com.google.errorprone.VisitorState.<init>(VisitorState.java:205)
  	at com.google.errorprone.VisitorState.createConfiguredForCompilation(VisitorState.java:126)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.createVisitorState(ErrorProneScannerTransformer.java:54)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:156)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:239)
  	at org.jetbrains.jps.javac.ExternalJavacProcess.compile(ExternalJavacProcess.java:189)
  	at org.jetbrains.jps.javac.ExternalJavacProcess.access$400(ExternalJavacProcess.java:28)
  	at org.jetbrains.jps.javac.ExternalJavacProcess$CompilationRequestsHandler$1.run(ExternalJavacProcess.java:262)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  	at java.base/java.lang.Thread.run(Thread.java:833)
```

```
  	IntelliJ IDEA 2023.1.4 (Ultimate Edition)
  	Build #IU-231.9225.16, built on July 11, 2023
```

**Comment by cushon** [comment]
That error should be resolved by passing the `--add-opens=` and `--add-exports=` flags documented in https://errorprone.info/docs/installation

**Comment by yougogirl** [comment]
I had them added in my pom properly. The intellij plugin for errorprone was not installed properly.
