### ISSUE TITLE
 An unhandled exception was thrown by the Error Prone static analysis plugin

### ISSUE THREAD

**Issue by rjh-yext** [google/error-prone#4052]
```
error-prone version: 2.11.0
19:37:31        BugPattern: MustBeClosedChecker
19:37:31        Stack Trace:
19:37:31        java.lang.reflect.InaccessibleObjectException: Unable to make com.sun.tools.javac.code.Symbol com.sun.tools.javac.comp.Resolve.findIdent(com.sun.tools.javac.util.JCDiagnostic$DiagnosticPosition,com.sun.tools.javac.comp.Env,com.sun.tools.javac.util.Name,com.sun.tools.javac.code.Kinds$KindSelector) accessible: module jdk.compiler does not "opens com.sun.tools.javac.comp" to unnamed module @192ffefb
19:37:31       at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
19:37:31       at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
19:37:31       at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
19:37:31       at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
19:37:31       at com.google.errorprone.util.FindIdentifiers.findIdent(FindIdentifiers.java:119)
19:37:31       at com.google.errorprone.util.FindIdentifiers.findIdent(FindIdentifiers.java:104)
19:37:31       at com.google.errorprone.fixes.SuggestedFixes.qualifyType(SuggestedFixes.java:332)
19:37:31       at com.google.errorprone.fixes.SuggestedFixes$2.visitDeclared(SuggestedFixes.java:387)
19:37:31       at com.google.errorprone.fixes.SuggestedFixes$2.visitDeclared(SuggestedFixes.java:374)
19:37:31       at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1169)
19:37:31       at com.google.errorprone.fixes.SuggestedFixes.qualifyType(SuggestedFixes.java:373)
19:37:31       at com.google.errorprone.bugpatterns.AbstractMustBeClosedChecker.introduceSingleStatementTry(AbstractMustBeClosedChecker.java:346)
19:37:31       at com.google.errorprone.bugpatterns.AbstractMustBeClosedChecker.chooseFixType(AbstractMustBeClosedChecker.java:309)
19:37:31       at com.google.errorprone.bugpatterns.AbstractMustBeClosedChecker.addFix(AbstractMustBeClosedChecker.java:323)
19:37:31       at com.google.errorprone.bugpatterns.AbstractMustBeClosedChecker.checkClosed(AbstractMustBeClosedChecker.java:211)
19:37:31       at com.google.errorprone.bugpatterns.AbstractMustBeClosedChecker.matchNewClassOrMethodInvocation(AbstractMustBeClosedChecker.java:125)
19:37:31       at com.google.errorprone.bugpatterns.MustBeClosedChecker.matchNewClassOrMethodInvocation(MustBeClosedChecker.java:155)
19:37:31       at com.google.errorprone.bugpatterns.MustBeClosedChecker.matchMethodInvocation(MustBeClosedChecker.java:134)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
19:37:31       at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1813)
19:37:31       at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:590)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:751)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
19:37:31       at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1813)
19:37:31       at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:502)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:633)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:150)
19:37:31       at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1592)
19:37:31       at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
19:37:31       at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
19:37:31       at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:740)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:150)
19:37:31       at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:953)
19:37:31       at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
19:37:31       at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
19:37:31       at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
19:37:31       at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:152)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
19:37:31       at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
19:37:31       at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
19:37:31       at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
19:37:31       at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
19:37:31       at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
19:37:31       at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
19:37:31       at com.google.devtools.build.buildjar.javac.plugins.errorprone.ErrorPronePlugin.postFlow(ErrorPronePlugin.java:116)
19:37:31       at com.google.devtools.build.buildjar.javac.BlazeJavaCompiler.flow(BlazeJavaCompiler.java:115)
19:37:31       at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
19:37:31       at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
19:37:31       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
19:37:31       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
19:37:31       at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
19:37:31       at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:137)
19:37:31       at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.fallback(ReducedClasspathJavaLibraryBuilder.java:105)
19:37:31       at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:67)
19:37:31       at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:110)
19:37:31       at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:118)
19:37:31       at com.google.devtools.build.buildjar.BazelJavaBuilder.build(BazelJavaBuilder.java:105)
19:37:31       at com.google.devtools.build.buildjar.BazelJavaBuilder.parseAndBuild(BazelJavaBuilder.java:85)
19:37:31       at com.google.devtools.build.lib.worker.WorkRequestHandler$WorkRequestHandlerBuilder.lambda$new$0(WorkRequestHandler.java:264)
19:37:31       at com.google.devtools.build.lib.worker.WorkRequestHandler$WorkRequestCallback.apply(WorkRequestHandler.java:230)
19:37:31       at com.google.devtools.build.lib.worker.WorkRequestHandler.respondToRequest(WorkRequestHandler.java:424)
19:37:31       at com.google.devtools.build.lib.worker.WorkRequestHandler.lambda$startResponseThread$1(WorkRequestHandler.java:381)
19:37:31       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by rickie** [comment]
The errors shows Error Prone 2.11.0 while 2.21.1 is already out. I recommend upgrading Error Prone.

However, based on the error, I would also take a look at the [installation docs](http://errorprone.info/docs/installation) that mention the JVM flags (see the part that mentions `--add-exports and add-opens`). These flags are most likely missing.

**Comment by tbroyer** [comment]
@rickie This is using Bazel though, where it's supposed to take care of everything (including the version of Error Prone being used IIRC). So maybe upgrade Bazel then?

**Comment by rickie** [comment]
Ahh I missed that part, good one @tbroyer!

**Comment by cushon** [comment]
That latest versions of Bazel are using 2.20.0: https://github.com/bazelbuild/bazel/blob/7e0df68aa4d11307dff8571ebce11d37c79c170c/WORKSPACE#L376-L380

I agree the best option is to try to use a newer version of Bazel, if that isn't an option you could disable the check as a workaround.
