### ISSUE TITLE
NumericEquality fails with parenthesized expression

### ISSUE THREAD

**Issue by andrewgaul** [google/error-prone#415]
Consider the following code:

```java
final Long constValue = new Long(1000L);
Long assignedValue;
boolean retVal = ((assignedValue = new Long(1000L)) != constValue);
```

error-prone fails with:

```
     java.lang.NullPointerException
        at com.google.errorprone.bugpatterns.NumericEquality.isFinal(NumericEquality.java:63)
        at com.google.errorprone.bugpatterns.NumericEquality.matchArgument(NumericEquality.java:55)
        at com.google.errorprone.bugpatterns.AbstractReferenceEquality.matchBinary(AbstractReferenceEquality.java:57)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:532)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBinary(ErrorProneScanner.java:146)
        at com.sun.tools.javac.tree.JCTree$JCBinary.accept(JCTree.java:1958)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
```

**Comment by cushon** [comment]
Thanks, on it.

**Comment by andrewgaul** [comment]
Confirmed fixed.
