### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin.

### ISSUE THREAD

**Issue by zhang-lucy** [google/error-prone#4192]
error: An unhandled exception was thrown by the Error Prone static analysis plugin.

     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.23.0
     BugPattern: ParameterName
     Stack Trace:
     java.lang.IndexOutOfBoundsException: Range [20126, 20141) out of bounds for length 20113
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromToIndex(Preconditions.java:76)
        at java.base/jdk.internal.util.Preconditions.checkFromToIndex(Preconditions.java:313)
        at java.base/java.util.Objects.checkFromToIndex(Objects.java:387)
        at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:664)
        at java.base/java.nio.HeapCharBuffer.subSequence(HeapCharBuffer.java:44)
        at com.google.errorprone.bugpatterns.ParameterName.processArgument(ParameterName.java:160)
        at com.google.errorprone.bugpatterns.ParameterName.checkArguments(ParameterName.java:130)
        at com.google.errorprone.bugpatterns.ParameterName.matchMethodInvocation(ParameterName.java:84)
        at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1813)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:590)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:751)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1813)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:502)
        at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:633)
        at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:150)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1592)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:486)
        at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:654)
        at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:150)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1565)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
        at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
        at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
        at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
        at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)

**Comment by sz-liva** [comment]
This ticket is open a year and a half. Is there any workaround?

**Comment by sz-liva** [comment]
Steps to reproduce:
1. Create `StreamUtil.java` class
```java
@UtilityClass
public final class StreamUtil {

    public static <T> boolean isEmpty(Stream<T> self) {
        return self.findAny().isEmpty();
    }

}
```
2. Create another class ```TestLombok.java` annotated with `@ExtensionMethod`
```java
@ExtensionMethod(StreamUtil.class)
public class TestLombok {

    public void test() {
        Stream.of("a", "b", "c").isEmpty();
    }

}
```
3. ErrorProne will fail when processing a call to `isEmpty()`.

**Comment by sz-liva** [comment]
@cushon Are there any plans to fix this issue? It makes it practically impossible to use ErrorProne together with the `@ExtensionMethod` annotation from Lombok.

**Comment by sz-liva** [comment]
> [@sz-liva](https://github.com/sz-liva) Can't you turn the ParameterName check off?

Thank you, this workaround worked.

**Comment by nealeu** [comment]
Our set of workarounds for Lombok currently look like this
```groovy
tasks.withType(JavaCompile).configureEach {
  options.errorprone {
    check("NullAway", net.ltgt.gradle.errorprone.CheckSeverity.ERROR)
    option("NullAway:OnlyNullMarked", "true")
    option("NullAway:ExcludedClassAnnotations","lombok.Builder,lombok.Data") // To avoid [NullAway] initializer method does not guarantee @NonNull
    disable("ParameterName") // see https://github.com/google/error-prone/issues/4192
    disable("NullablePrimitive") // see https://github.com/google/error-prone/issues/4053
  }
}
```
