### ISSUE TITLE
NullArgumentForNonNullParameter thrown by Error Prone

### ISSUE THREAD

**Issue by caitlinshk** [google/error-prone#4225]
Hi there,

I'm running my project's local server (https://github.com/civiform/civiform/wiki/Getting-started#running-a-local-server), and I ran into this issue. It asked me to report it, so here I am :)
```
play.sbt.PlayExceptions$CompilationException: Compilation error[An unhandled exception was thrown by the Error Prone static analysis plugin.
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.23.0
     BugPattern: NullArgumentForNonNullParameter
     Stack Trace:
     java.lang.NullPointerException
  	at com.google.errorprone.util.ASTHelpers.enclosingClass(ASTHelpers.java:1207)
  	at com.google.errorprone.bugpatterns.nullness.NullnessUtils.hasExtraParameterForEnclosingInstance(NullnessUtils.java:263)
  	at com.google.errorprone.bugpatterns.nullness.NullArgumentForNonNullParameter.match(NullArgumentForNonNullParameter.java:102)
  	at com.google.errorprone.bugpatterns.nullness.NullArgumentForNonNullParameter.matchNewClass(NullArgumentForNonNullParameter.java:97)
  	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:773)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1727)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:469)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:817)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1570)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1048)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:740)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
  	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:156)
  	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1414)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1361)
  	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:960)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:147)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
  	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
  	at sbt.internal.inc.javac.LocalJavaCompiler.run(LocalJava.scala:345)
  	at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$12(AnalyzingJavaCompiler.scala:172)
  	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  	at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:262)
  	at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:161)
  	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2(MixedAnalyzingCompiler.scala:103)
  	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$2$adapted(MixedAnalyzingCompiler.scala:91)
  	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
  	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compileJava$1(MixedAnalyzingCompiler.scala:91)
  	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
  	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava(MixedAnalyzingCompiler.scala:61)
  	at sbt.internal.inc.MixedAnalyzingCompiler.compileJava0$1(MixedAnalyzingCompiler.scala:198)
  	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
  	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
  	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
  	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:180)
  	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:178)
  	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:464)
  	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
  	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
  	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
  	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
  	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:419)
  	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
  	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:406)
  	at sbt.internal.inc.Incremental$.apply(Incremental.scala:172)
  	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
  	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
  	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
  	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
  	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
  	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2371)
  	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2321)
  	at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:31)
  	at sbt.internal.io.Retry$.apply(Retry.scala:47)
  	at sbt.internal.io.Retry$.apply(Retry.scala:29)
  	at sbt.internal.io.Retry$.apply(Retry.scala:24)
  	at sbt.internal.server.BspCompileTask$.compute(BspCompileTask.scala:31)
  	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:2319)
  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
  	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
  	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
  	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
  	at sbt.Execute.work(Execute.scala:292)
  	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
  	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
  	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  	at java.base/java.lang.Thread.run(Thread.java:829)]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
	at scala.Option.map(Option.scala:230)
	at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$8(PlayReload.scala:127)
	at scala.Option.map(Option.scala:230)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:100)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:38)
	at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:152)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:152)
```

**Comment by cpovirk** [comment]
Thanks. Most of the actual Error Prone team is OOO this week, but I wrote this check, so I'm seeing how easily I can have a look.

Given how much Google's security policies discourage the use of Docker, I've been trying to see if there's a shorter path to reproducing this. I've managed to install scala and sbt, kick off `sbt` from within `server`, and run `build`. That built successfully. Do you see the failure you posted at head (e9f8449aaa13f6402ad41fb3acc14a8b33ad8eff in my clone), or does it appear only with local changes?

**Comment by cpovirk** [comment]
In any case, this whole failure is interesting:

- https://github.com/google/error-prone/blob/v2.23.0/core/src/main/java/com/google/errorprone/bugpatterns/nullness/NullArgumentForNonNullParameter.java#L102
- https://github.com/google/error-prone/blob/v2.23.0/core/src/main/java/com/google/errorprone/bugpatterns/nullness/NullnessUtils.java#L263
- https://github.com/google/error-prone/blob/v2.23.0/check_api/src/main/java/com/google/errorprone/util/ASTHelpers.java#L1207

It looks to me like we have a symbol for which `isConstructor` is `true` but for which `enclosingClass` returns `null`. At least under JDK11 (which might be what `sbt` is using on my machine?), I don't see how we could have a `MethodSymbol` with a null `owner` (which is what `enclosingClass` returns) without getting an NPE in the `MethodSymbol` constructor... unless somehow it gets overwritten later?

As an aside, I'm not sure that my `enclosingClass(constructedClass)` check could possibly work: If I'm reading it right, that should call `constructedClass.enclClass()`, which should return `constructedClass` itself....

**Comment by cpovirk** [comment]
(`isContructor()` is implemented as a check against the name `<init>`. I suppose it's possible that something uses that as a name for a non-constructor? Do you have Scala deps? That still seems like a long shot. I'm probably missing something obvious.)

**Comment by caitlinshk** [comment]
I realized I misspoke in my original report: The error happens when running browser tests locally, *not* when running the server. https://github.com/civiform/civiform/wiki/Testing#functional-browser-tests are our browser test directions (specifically `bin/run-browser-test-env`).

But, it actually looks like I can no longer reproduce the error. Earlier today, I was working on a few different local PRs (https://github.com/civiform/civiform/pull/6254, then https://github.com/civiform/civiform/pull/6272 which is stacked on top) and I had one of those PR branches checked out when I started seeing the error. What I just did was:

1) Checkout main
2) run `bin/run-browser-test-env` -- works fine.
3) Checkout https://github.com/civiform/civiform/pull/6254.
2) run `bin/run-browser-test-env` -- works fine.
3) Checkout https://github.com/civiform/civiform/pull/6272.
2) run `bin/run-browser-test-env` -- works fine.

It seems like something got temporarily mangled, but checking out main un-mangled it somehow?

Since I can't repro and don't have good repro steps, feel free to close as not reproducible.

**Comment by cpovirk** [comment]
Thanks. I'll see if the aforementioned real Error Prone team has any thoughts upon their return. It does seem believable that some file got mangled or something.

In any case, I am going to look more into this whole "I'm not sure that my `enclosingClass(constructedClass)` check could possibly work" concern. So we will get something out of this one way or another :)

**Comment by cpovirk** [comment]
Oh, I'm wrong: It works fine because the call to `enclClass()` is made on `sym.owner`, not on `sym`. (It's possible that `ASTHelpers.enclosingClass()` was implementing the same unfortunate behavior as `enclClass()` up until cl/153079032, when cushon@ gave it the behavior that I need.)

I should probably still have a test for this.

And this is a reminder that it's nice not to have to deal with enclosing classes at all.... Really, the more checking that we can do just based on questions like "Is the target type here a primitive type?" (like https://errorprone.info/bugpattern/NullTernary), the better. Probably `NullArgumentForNonNullParameter` should handle primitive types differently or leave that to another future checker. Anyway, I digress.

**Comment by cushon** [comment]
I don't have any theories about how that NPE could have happened. I don't know much about the interaction between sbt and javac. My current best idea is to add a more descriptive assertion that would catch that NPE, and see if it happens again.

**Comment by cushon** [comment]
@caitlinshk I added an assertion that should print more information if this happens again and released that change as `v2.24.1`, can you try updating your build to use the latest version and let us know if you see this crash again?

**Comment by caitlinshk** [comment]
Yes definitely! It wasn't super reproducible but I'll let you know if I see it again.

**Comment by caitlinshk** [comment]
Just FYI I still haven't seen this error again, so feel free to close.

**Comment by cushon** [comment]
Thanks for following up!
