### ISSUE TITLE
EmptyTopLevelDeclaration throws IllegalArgumentException

### ISSUE THREAD

**Issue by asheldon** [google/error-prone#4245]
This repro Java file crashes Error Prone 2.23.0 and 2.24.1.

```
package errorpronecrash;
;
public class ReproFile {}
```

Stack trace:

```
    [javac] package errorpronecrash;
    [javac] ^
    [javac]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
    [javac]   
    [javac]      error-prone version: 2.23.0
    [javac]      BugPattern: EmptyTopLevelDeclaration
    [javac]      Stack Trace:
    [javac]      java.lang.IllegalArgumentException: invalid replacement: [25, 24) ()
    [javac]   	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:463)
    [javac]   	at com.google.errorprone.fixes.Replacement.create(Replacement.java:37)
    [javac]   	at com.google.errorprone.fixes.SuggestedFix$ReplacementFix.getReplacement(SuggestedFix.java:439)
    [javac]   	at com.google.errorprone.fixes.SuggestedFix.getReplacements(SuggestedFix.java:95)
    [javac]   	at com.google.errorprone.fixes.AppliedFix$Applier.apply(AppliedFix.java:69)
    [javac]   	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1228)
    [javac]   	at com.google.errorprone.JavacErrorDescriptionListener.lambda$new$1(JavacErrorDescriptionListener.java:94)
    [javac]   	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
    [javac]   	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
    [javac]   	at java.base/java.util.Collections$2.tryAdvance(Collections.java:5073)
    [javac]   	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:5081)
    [javac]   	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
    [javac]   	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
    [javac]   	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
    [javac]   	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    [javac]   	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
    [javac]   	at com.google.errorprone.JavacErrorDescriptionListener.onDescribed(JavacErrorDescriptionListener.java:107)
    [javac]   	at com.google.errorprone.ErrorProneAnalyzer.lambda$finished$1(ErrorProneAnalyzer.java:141)
    [javac]   	at com.google.errorprone.VisitorState.reportMatch(VisitorState.java:301)
    [javac]   	at com.google.errorprone.scanner.Scanner.reportMatch(Scanner.java:127)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:448)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:555)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
    [javac]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:623)
    [javac]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:66)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
    [javac]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:156)
    [javac]   	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:133)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1436)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1383)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:963)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:319)
    [javac]   	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:178)
    [javac]   	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
    [javac]   	at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

**Comment by cushon** [comment]
Thanks for the report! I can reproduce this on JDK 21 but not earlier versions, I wonder if it is related to the changes for https://bugs.openjdk.org/browse/JDK-8305671. It looks like the start and end positions for the empty statement are incorrect.
