### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by regrog** [google/error-prone#425]
Hi,
I just used error-prone to check my code and as soon as I run my build it fails and error-prone ask me to submit the stack trace below.
I'm using java 8 update 91 and my ant version is 1.9.6.v201510161327 .
My build envinronment is and eclipse Neon, in case you need that info.
Thanks

```
    [javac] /home/myuser/myworkspace/logging/src/logging/Log4jLoggerProvider.java:15: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    [javac] 	public Log4jLoggerProvider() {
    [javac] 	       ^
    [javac]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
    [javac]   
    [javac]      error-prone version: 2.0.9
    [javac]      Stack Trace:
    [javac]      java.lang.NoSuchMethodError: com.sun.tools.javac.code.Symbol$TypeSymbol.members()Lcom/sun/tools/javac/code/Scope$WriteableScope;
    [javac]   	at com.google.errorprone.util.ASTHelpers.findSuperMethods(ASTHelpers.java:395)
    [javac]   	at com.google.errorprone.bugpatterns.Overrides.matchMethod(Overrides.java:58)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:815)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:146)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:800)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
    [javac]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
    [javac]   	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:133)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:590)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:720)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:68)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
    [javac]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:91)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:99)
    [javac]   	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:120)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:601)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:550)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:50)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:70)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1036)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:45)
    [javac]   	at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:172)
    [javac]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:115)
    [javac]   	at com.google.errorprone.ErrorProneJavacJavaCompiler.postFlow(ErrorProneJavacJavaCompiler.java:109)
    [javac]   	at com.google.errorprone.ErrorProneJavacJavaCompiler.flow(ErrorProneJavacJavaCompiler.java:93)
    [javac]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1286)
    [javac]   	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:894)
    [javac]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
    [javac]   	at com.sun.tools.javac.main.Main.compile(Main.java:523)
    [javac]   	at com.sun.tools.javac.main.Main.compile(Main.java:381)
    [javac]   	at com.sun.tools.javac.main.Main.compile(Main.java:370)
    [javac]   	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:253)
    [javac]   	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:163)
    [javac]   	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:92)
    [javac]   	at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:39)
    [javac]   	at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:36)
    [javac]   	at com.google.errorprone.ErrorProneAntCompilerAdapter.execute(ErrorProneAntCompilerAdapter.java:72)
    [javac]   	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1160)
    [javac]   	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:936)
    [javac]   	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   	at java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   	at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   	at org.apache.tools.ant.Target.execute(Target.java:435)
    [javac]   	at org.apache.tools.ant.Target.performTasks(Target.java:456)
    [javac]   	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    [javac]   	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    [javac]   	at org.eclipse.ant.internal.launching.remote.EclipseSingleCheckExecutor.executeTargets(EclipseSingleCheckExecutor.java:34)
    [javac]   	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    [javac]   	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    [javac]   	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:309)
    [javac]   	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:224)
    [javac]   	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   	at java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   	at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   	at org.apache.tools.ant.Target.execute(Target.java:435)
    [javac]   	at org.apache.tools.ant.Target.performTasks(Target.java:456)
    [javac]   	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    [javac]   	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
    [javac]   	at org.eclipse.ant.internal.launching.remote.EclipseSingleCheckExecutor.executeTargets(EclipseSingleCheckExecutor.java:34)
    [javac]   	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    [javac]   	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
    [javac]   	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:309)
    [javac]   	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:224)
    [javac]   	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   	at java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   	at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   	at org.apache.tools.ant.Target.execute(Target.java:435)
    [javac]   	at org.apache.tools.ant.Target.performTasks(Target.java:456)
    [javac]   	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    [javac]   	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    [javac]   	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    [javac]   	at org.eclipse.ant.internal.launching.remote.EclipseDefaultExecutor.executeTargets(EclipseDefaultExecutor.java:36)
    [javac]   	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    [javac]   	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.run(InternalAntRunner.java:453)
    [javac]   	at org.eclipse.ant.internal.launching.remote.InternalAntRunner.main(InternalAntRunner.java:140)
```

**Comment by cushon** [comment]
The missing `TypeSymbol.members()WriteableScope` method is present in the javac packaged with Error Prone: https://github.com/google/error-prone-javac/blob/master/src/jdk.compiler/share/classes/com/sun/tools/javac/code/Symbol.java#L382

That method was added in JDK9 by [JDK-8031569](https://bugs.openjdk.java.net/browse/JDK-8031569), so I suspect Error Prone is running against the javac 8u91 on your machine. The ant plugin is supposed to make sure Error Prone always uses its javac, though.

Do you have a repro?

**Comment by regrog** [comment]
I'm trying to investigate what are you saying.
Unfortunately I can't provide you a repro, I'm working to produce a small example to test this situation.
It should takes time because I can't focus too much on this, I'll answer again ASAP.
Thanks

**Comment by regrog** [comment]
Fixed!
I downloaded new Ant version 1.9.7 (eclipse by default has 1.9.6.v201510161327).
This seems to fix the problem!

**Comment by bobtiernay-okta** [comment]
Is there a document that describes how the compiler may aftect the bytecode of the resulting classes? I hit a similar issue: https://groups.google.com/forum/m/?utm_medium=email&utm_source=footer#!topic/error-prone-discuss/2qxJ6iYXOgQ

Now I’m concerned that Error Prone may be modifying the bytecode in unknown ways. Thanks.

**Comment by bobtiernay-okta** [comment]
Another example here:

https://github.com/google/error-prone/issues/347

**Comment by eaftan** [comment]
@bobtiernay-okta As mentioned in that error-prone-discuss thread, Error Prone uses a different (newer?) version of javac than whatever is installed on your machine.  This may result in different bytecode generated, for example, the enhanced try-with-resources codegen that is in javac 9.  

We have also made some patches to our javac that fix bugs that have bitten us internally.  For example, 
our javac includes fixes for https://bugs.openjdk.java.net/browse/JDK-8144185 and https://bugs.openjdk.java.net/browse/JDK-8177486.

You can see our javac repo here to find the exact revision we use, and any patches we have applied:
https://github.com/google/error-prone-javac/tree/9+181-r4173-1
This is the production compiler for Google's Java compiles, and we are confident in its results.
