### ISSUE TITLE
mvn package  for dspace error

### ISSUE THREAD

**Issue by glarbi** [google/error-prone#4255]
error-prone version: 2.10.0
     BugPattern: ReferenceEquality
     Stack Trace:
     com.google.common.util.concurrent.ExecutionError: java.lang.NoSuchMethodError: 'com.sun.tools.javac.tree.JCTree$JCExpression com.sun.tools.javac.tree.TreeMaker.Select(com.sun.tools.javac.tree.JCTree$JCExpression, com.sun.tools.javac.code.Symbol)'
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4935)

**Comment by Stephan202** [comment]
Hey @glarbi! This issue looks like a [duplicate](https://github.com/google/error-prone/issues?q=%22com.sun.tools.javac.tree.TreeMaker.Select%22) of other reported issues related to JDK 21 compatibility. Version 2.10.0 is quite old; please upgrade to the latest version.
