### ISSUE TITLE
 2.26.1: An unhandled exception was thrown by the Error Prone static analysis plugin. BugPattern: JUnitIncompatibleType

### ISSUE THREAD

**Issue by mdlnr** [google/error-prone#4374]
```
Error: [ERROR]   
Error: [ERROR]      error-prone version: 2.26.1
Error:       BugPattern: JUnitIncompatibleType
Error:       Stack Trace:
Error:       java.lang.ClassCastException: class com.sun.tools.javac.code.Type$ClassType cannot be cast to class com.sun.tools.javac.code.Type$ArrayType (com.sun.tools.javac.code.Type$ClassType and com.sun.tools.javac.code.Type$ArrayType are in module jdk.compiler of loader 'app')
Error:    	at com.google.errorprone.bugpatterns.collectionincompatibletype.JUnitIncompatibleType.matchMethodInvocation(JUnitIncompatibleType.java:86)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1813)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:502)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:633)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1592)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:740)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:953)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
Error:    	at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:152)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
Error:    	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
Error:    	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
Error:    	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
Error:    	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
Error:    	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
Error:    	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:156)
Error:    	at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
Error:    	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1394)
Error:    	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1341)
Error:    	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
Error:    	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
Error:    	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
Error:    	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
Error:    	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
Error:    	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
Error:    	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:214)
Error:    	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1228)
Error:    	at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:[208]XXXX
Error:    	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
Error:    	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
Error:    	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
Error:    	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:[210]XXXXXXX
Error:    	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:195)
Error:    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Error:    	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
Error:    	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Error:    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
Error:    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
Error:    	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by cushon** [comment]
This is the same issue as https://github.com/google/error-prone/issues/4291, it'll be fixed in the next release.
