### ISSUE TITLE
`JUnitIncompatibleType` on 2.27.0 throws `ClassCastException` for `com.sun.tools.javac.code.Type$TypeVar` around `assertArrayEquals`

### ISSUE THREAD

**Issue by XN137** [google/error-prone#4377]
thanks for dealing with https://github.com/google/error-prone/issues/4291 but sadly even after that fix in 2.27.0 our code base still hits a compile error in this check:

```
[ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[ERROR]   
[ERROR]      error-prone version: 2.27.0
[ERROR]      BugPattern: JUnitIncompatibleType
[ERROR]      Stack Trace:
[ERROR]      java.lang.ClassCastException: class com.sun.tools.javac.code.Type$TypeVar cannot be cast to class com.sun.tools.javac.code.Type$ArrayType (com.sun.tools.javac.code.Type$TypeVar and com.sun.tools.javac.code.Type$ArrayType are in module jdk.compiler of loader 'app')
[ERROR]   	at com.google.errorprone.bugpatterns.collectionincompatibletype.JUnitIncompatibleType.matchMethodInvocation(JUnitIncompatibleType.java:79)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1666)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
```

problematic [code](https://github.com/dremio/dremio-oss/blob/12d7a954966ee5782921a4fbe32cc4568cbf631b/services/datastore/src/test/java/com/dremio/datastore/TestByteSerializerFactoryJson.java#L37) snippet:
```
  protected <T> void runCircularTest(Format<T> format, T original) throws IOException {
    final Serializer<T, byte[]> serializer = getSerializer(format);

    final String outJson = serializer.toJson(original);
    final T backJson = serializer.fromJson(outJson);

    if (original instanceof byte[]) {
      assertArrayEquals((byte[]) original, (byte[]) backJson);  // <-- error happens here
    } else {
      assertEquals(original, backJson);
    }
  }
```

**Comment by XN137** [comment]
another related error:

```
An unhandled exception was thrown by the Error Prone static analysis plugin.

[2024-04-26T19:32:48.796Z] [ERROR]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
[2024-04-26T19:32:48.796Z] [ERROR]   
[2024-04-26T19:32:48.796Z] [ERROR]      error-prone version: 2.27.0
[2024-04-26T19:32:48.796Z] [ERROR]      BugPattern: JUnitIncompatibleType
[2024-04-26T19:32:48.796Z] [ERROR]      Stack Trace:
[2024-04-26T19:32:48.796Z] [ERROR]      java.lang.ClassCastException: class com.sun.tools.javac.code.Type$JCPrimitiveType$2 cannot be cast to class com.sun.tools.javac.code.Type$ArrayType (com.sun.tools.javac.code.Type$JCPrimitiveType$2 and com.sun.tools.javac.code.Type$ArrayType are in module jdk.compiler of loader 'app')
[2024-04-26T19:32:48.796Z] [ERROR]   	at com.google.errorprone.bugpatterns.collectionincompatibletype.JUnitIncompatibleType.matchMethodInvocation(JUnitIncompatibleType.java:80)
[2024-04-26T19:32:48.796Z] [ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
[2024-04-26T19:32:48.796Z] [ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
[2024-04-26T19:32:48.796Z] [ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
```

code:
```
protected void assertArraysEquals(String message, Object expected, Object actual) {
    (...)

    } else if (expected instanceof float[] && actual instanceof float[]) {
      assertArrayEquals(message, (float[]) expected, (float[]) actual, DELTA);  // <-- error happens here
    }
```
