### ISSUE TITLE
Symbol$CompletionFailure regression on 2.0.10+

### ISSUE THREAD

**Issue by mattnelson** [google/error-prone#441]
I upgraded error-prone to 2.0.11 and discovered a compile failure, stepped back down to 2.09 and discovered it was introduced in 2.0.10. Verified that the class was transitively in the dependency tree. Was able to resolve this error by explicitly adding the dependency as a compile dependency. But then that causes the dependency plugin to fail because the dependency is declared but unused. Any ideas on next steps?

2.0.11
```
<my class>: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
            singletons.add(new EurekaServerContextBinder());
                           ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.0.11
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.glassfish.hk2.utilities.binding.AbstractBinder not found
```

2.0.10
```
     error-prone version: 2.0.10
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.glassfish.hk2.utilities.binding.AbstractBinder not found
```

Other information about my environment.
```
org.apache.maven.plugins:maven-compiler-plugin:3.5.1
Java(TM) SE Runtime Environment (build 1.8.0_102-b14)
Apache Maven 3.3.9
```

**Comment by cushon** [comment]
Can you try again with `-XDdev` and share the stack trace you get?

(It's a compiler flag, so you can add it to e.g. `<compilerArgs>` for the maven compiler plugin or `options.compilerArgs` for gradle.)

**Comment by mattnelson** [comment]
Here you go.

```
An exception has occurred in the compiler (1.9.0-internal). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the database for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.google.errorprone.ErrorProneError:
<my class>: BoxedPrimitiveConstructor: An exception was thrown by Error Prone: class file for org.glassfish.hk2.utilities.binding.AbstractBinder not found
            singletons.add(new EurekaServerContextBinder());
                           ^

Caused by: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.glassfish.hk2.utilities.binding.AbstractBinder not found
	at com.sun.tools.javac.code.ClassFinder.newCompletionFailure(ClassFinder.java:374)
	at com.sun.tools.javac.code.ClassFinder.classFileNotFound(ClassFinder.java:362)
	at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:355)
	at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:279)
	at com.sun.tools.javac.code.ClassFinder.access$000(ClassFinder.java:72)
	at com.sun.tools.javac.code.ClassFinder$1.complete(ClassFinder.java:159)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:579)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1074)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.getSuperclass(Symbol.java:1100)
	at com.sun.tools.javac.code.Types$15.visitClassType(Types.java:2276)
	at com.sun.tools.javac.code.Types$15.visitClassType(Types.java:2265)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:978)
	at com.sun.tools.javac.code.Types$UnaryVisitor.visit(Types.java:4574)
	at com.sun.tools.javac.code.Types.supertype(Types.java:2262)
	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1927)
	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1916)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:978)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4495)
	at com.sun.tools.javac.code.Types.asSuper(Types.java:1913)
	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1929)
	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1916)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:978)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4495)
	at com.sun.tools.javac.code.Types.asSuper(Types.java:1913)
	at com.sun.tools.javac.code.Types.unboxedType(Types.java:3922)
	at com.sun.tools.javac.code.Types.unboxedTypeOrType(Types.java:3932)
	at com.google.errorprone.bugpatterns.BoxedPrimitiveConstructor.matchNewClass(BoxedPrimitiveConstructor.java:72)
	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:999)
	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:146)
	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1675)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
	at com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:510)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:960)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:146)
	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1614)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
	at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:434)
	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:760)
	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:146)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1424)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:249)
	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:577)
	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:996)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:207)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:945)
	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:146)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:637)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:637)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:652)
	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:70)
	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:45)
	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:125)
	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:113)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1303)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1247)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:858)
	at com.sun.tools.javac.main.Main.compile(Main.java:253)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:190)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:101)
	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:131)
	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:73)
	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:886)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by cushon** [comment]
Thanks! This is a bug in BoxedPrimitiveConstructor:

```
    at com.sun.tools.javac.code.Types.unboxedTypeOrType(Types.java:3932)
    at com.google.errorprone.bugpatterns.BoxedPrimitiveConstructor.matchNewClass(BoxedPrimitiveConstructor.java:72)
```

It should be an easy fix.

If you want a work-around until the fix is released, `-Xep:BoxedPrimitiveConstructor:OFF` will disable just that check.

**Comment by mattnelson** [comment]
Verified that the workaround fixed the compile failure.
