### ISSUE TITLE
YodaCondition crashes on call to "equals(foo)", i.e., without explicit object given

### ISSUE THREAD

**Issue by PhilippWendler** [google/error-prone#4488]
In Error Prone 2.29.2, the following code produces a crash if the `YodaCondition` check is enabled:

```java
import com.google.common.base.Objects;

public class Test {

  @Override
  public boolean equals(Object other) {
    return Objects.equal(this, other);
  }

  public boolean foo(Object other) {
    return equals(other);
  }
}
```
The crash is avoided if `this.equals(other)` is used.

Stacktrace:
```
    [javac] src/Test.java:11: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    [javac]     return equals(other);
    [javac]                  ^
    [javac]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
    [javac]   
    [javac]      error-prone version: 2.29.2
    [javac]      BugPattern: YodaCondition
    [javac]      Stack Trace:
    [javac]      java.lang.NullPointerException: Cannot invoke "com.sun.source.tree.Tree.getKind()" because "tree" is null
    [javac]     at com.google.errorprone.bugpatterns.YodaCondition.seemsConstant(YodaCondition.java:142)
    [javac]     at com.google.errorprone.bugpatterns.YodaCondition.yodaCondition(YodaCondition.java:120)
    [javac]     at com.google.errorprone.bugpatterns.YodaCondition.fix(YodaCondition.java:98)
    [javac]     at com.google.errorprone.bugpatterns.YodaCondition.matchMethodInvocation(YodaCondition.java:82)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:449)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:746)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:150)
    [javac]     at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1813)
    [javac]     at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:544)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:817)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:150)
    [javac]     at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1717)
    [javac]     at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:272)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:520)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:150)
    [javac]     at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1103)
    [javac]     at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:224)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:740)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:150)
    [javac]     at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:953)
    [javac]     at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:96)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:203)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:548)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:150)
    [javac]     at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:860)
    [javac]     at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:86)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:111)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:119)
    [javac]     at jdk.compiler/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:152)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:560)
    [javac]     at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:150)
    [javac]     at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:614)
    [javac]     at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:60)
    [javac]     at com.google.errorprone.scanner.Scanner.scan(Scanner.java:58)
    [javac]     at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
    [javac]     at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:227)
    [javac]     at jdk.compiler/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
    [javac]     at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1397)
    [javac]     at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1344)
    [javac]     at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:933)
    [javac]     at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:317)
    [javac]     at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:176)
    [javac]     at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
    [javac]     at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
```

**Comment by cushon** [comment]
Thanks for the report, Error Prone shouldn't crash on this.

That particular example would result in an infinite loop if it was executed. Out of curiosity did the code where you encountered this have a similar bug, or was it correct working code that was different than the repro?

**Comment by PhilippWendler** [comment]
Sorry for the confusing example, this was just because I wanted to create a minimal example without writing something like `return true` into `equals()`. The original code had a properly working method.

Thanks for the quick fix!
