### ISSUE TITLE
Error-prone has no @CanIgnoreReturnValue annotation

### ISSUE THREAD

**Issue by lionell** [google/error-prone#461]
I was trying to check:
assertThat(someSet).containsExactly("a", "b"); // without inOrder()
and that gave me this error

error-prone version: 2.0.9-SNAPSHOT
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.errorprone.annotations.CanIgnoreReturnValue not found

**Comment by dinowernli** [comment]
+1, seeing this as well


```
Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.0.9-SNAPSHOT
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.errorprone.annotations.CanIgnoreReturnValue not found

```

**Comment by brendandouglas** [comment]
I'm seeing this as well, and it's causing a bazel build to fail (as error-prone is bundled with bazel).

Java compilation in rule '//base:unit_test_utils' failed: namespace-sandbox failed: An unhandled exception was thrown by the Error Prone static analysis plugin.

**Comment by cushon** [comment]
@brendandouglas gave me a stack trace:

```
     error-prone version: 2.0.9-SNAPSHOT
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.errorprone.annotations.CanIgnoreReturnValue not found
  	at com.sun.tools.javac.code.ClassFinder.newCompletionFailure(ClassFinder.java:374)
  	at com.sun.tools.javac.code.ClassFinder.classFileNotFound(ClassFinder.java:362)
  	at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:355)
  	at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:279)
  	at com.sun.tools.javac.code.ClassFinder.access$000(ClassFinder.java:72)
  	at com.sun.tools.javac.code.ClassFinder$1.complete(ClassFinder.java:159)
  	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:579)
  	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1074)
  	at com.sun.tools.javac.code.Symbol$ClassSymbol.members(Symbol.java:1013)
  	at com.sun.tools.javac.model.AnnotationProxyMaker.getAllValues(AnnotationProxyMaker.java:124)
  	at com.sun.tools.javac.model.AnnotationProxyMaker.getAllReflectedValues(AnnotationProxyMaker.java:102)
  	at com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation(AnnotationProxyMaker.java:90)
  	at com.sun.tools.javac.model.AnnotationProxyMaker.generateAnnotation(AnnotationProxyMaker.java:81)
  	at com.sun.tools.javac.code.AnnoConstruct.getAnnotation(AnnoConstruct.java:184)
  	at com.google.errorprone.util.ASTHelpers.getAnnotation(ASTHelpers.java:519)
  	at com.google.errorprone.util.ASTHelpers.hasAnnotation(ASTHelpers.java:488)
  	at com.google.errorprone.bugpatterns.CheckReturnValue.shouldCheckReturnValue(CheckReturnValue.java:69)
  	at com.google.errorprone.bugpatterns.CheckReturnValue.access$100(CheckReturnValue.java:65)
  	at com.google.errorprone.bugpatterns.CheckReturnValue$1.matches(CheckReturnValue.java:122)
  	at com.google.errorprone.bugpatterns.CheckReturnValue$1.matches(CheckReturnValue.java:95)
```

2.0.9 is an old version, I think this was fixed by 750321c82d36fdd91142afa68f281eb52a2099c4.

I'll get the Bazel version updated. If you're using another build system make sure you're on the latest version of Error Prone (currently 2.0.13).

**Comment by cushon** [comment]
Hmm, Bazel is supposed to be using 2.0.11 now: https://bazel-review.googlesource.com/#/c/4121/. I'll still get it updated to 2.0.13, but there's some other problem that's causing that build to use 2.0.9.

**Comment by brendandouglas** [comment]
In my case it was user error -- rebuilding bazel fixed it.
