### ISSUE TITLE
MissingCasesInEnumSwitch:  Cannot invoke "com.sun.tools.javac.code.Symbol.getSimpleName()"

### ISSUE THREAD

**Issue by wendigo** [google/error-prone#4684]
```
ERROR]      error-prone version: 2.36.0
[ERROR]      BugPattern: MissingCasesInEnumSwitch
[ERROR]      Stack Trace:
[ERROR]      java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Symbol.getSimpleName()" because the return value of "com.google.errorprone.util.ASTHelpers.getSymbol(com.sun.source.tree.Tree)" is null
[ERROR]   	at com.google.errorprone.bugpatterns.MissingCasesInEnumSwitch.lambda$matchSwitch$2(MissingCasesInEnumSwitch.java:63)
[ERROR]   	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:215)
[ERROR]   	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[ERROR]   	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
[ERROR]   	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:807)
[ERROR]   	at java.base/java.util.stream.ReferencePipeline$7$1FlatMap.accept(ReferencePipeline.java:294)
[ERROR]   	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[ERROR]   	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
[ERROR]   	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:570)
[ERROR]   	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560)
[ERROR]   	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
[ERROR]   	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265)
[ERROR]   	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727)
[ERROR]   	at com.google.errorprone.bugpatterns.MissingCasesInEnumSwitch.matchSwitch(MissingCasesInEnumSwitch.java:64)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.processMatchers(ErrorProneScanner.java:509)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitSwitch(ErrorProneScanner.java:948)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitSwitch(ErrorProneScanner.java:170)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCSwitch.accept(JCTree.java:1350)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:110)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:271)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:591)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:170)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1145)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:95)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitCase(TreeScanner.java:403)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCase(ErrorProneScanner.java:605)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCase(ErrorProneScanner.java:170)
[ERROR]   	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCCase.accept(JCTree.java:1415)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:92)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:74)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:48)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scan(TreeScanner.java:110)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:118)
[ERROR]   	at jdk.compiler/com.sun.source.util.TreeScanner.visitSwitch(TreeScanner.java:367)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitSwitch(ErrorProneScanner.java:949)
```

**Comment by wendigo** [comment]
Here's the simplest repro:

```
public class ErrorProneBug
{
    enum A {
        A1, A2, A3
    }

    public static void main(String[] args) {
        A a = null;

        switch (a) {
            case null -> {
                System.out.println("null");
            }
            case A1 -> {
                System.out.println("A1");
            }
            case A2 -> {
                System.out.println("A2");
            }
            case A3 -> {
                System.out.println("A3");
            }
        }
    }
}
```

**Comment by wendigo** [comment]
Removing case null make this repro work
