### ISSUE TITLE
Upgrade to ErrorProne 2.36.0 causes `InvalidCommandLineOptionException`: --should-stop=ifError policy (INIT) is not supported by Error Prone

### ISSUE THREAD

**Issue by uhafner** [google/error-prone#4705]
An upgrade of  ErrorProne 2.35.1 to 2.36.0 causes an `InvalidCommandLineOptionException`:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project codingstyle: Compilation failure
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:232)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:294)
[ERROR]         at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:178)
[ERROR]         at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
[ERROR]         at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
[ERROR] Caused by: com.google.errorprone.InvalidCommandLineOptionException: The default --should-stop=ifError policy (INIT) is not supported by Error Prone, pass --should-stop=ifError=FLOW instead
[ERROR]         at com.google.errorprone.BaseErrorProneJavaCompiler.checkShouldStopIfErrorPolicy(BaseErrorProneJavaCompiler.java:197)
[ERROR]         at com.google.errorprone.BaseErrorProneJavaCompiler.addTaskListener(BaseErrorProneJavaCompiler.java:87)
[ERROR]         at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:34)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:256)
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:230)
```

I have no idea how to change the command line on my side. Here is the debug output of Maven:

```
[INFO] --- compiler:3.13.0:compile (default-compile) @ codingstyle ---
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=33547, ConflictMarker.markTime=16680, ConflictMarker.nodeCount=22, ConflictIdSorter.graphTime=9274, ConflictIdSorter.topsortTime=13372, ConflictIdSorter.conflictIdCount=14, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=226735, ConflictResolver.conflictItemCount=22, DfDependencyCollector.collectTime=32496833, DfDependencyCollector.transformTime=314348}
[DEBUG] org.apache.maven.plugins:maven-compiler-plugin:jar:3.13.0
[DEBUG]    org.apache.maven.shared:maven-shared-utils:jar:3.4.2:compile
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.36:compile
[DEBUG]       commons-io:commons-io:jar:2.11.0:compile
[DEBUG]    org.apache.maven.shared:maven-shared-incremental:jar:1.1:compile
[DEBUG]    org.codehaus.plexus:plexus-java:jar:1.2.0:compile
[DEBUG]       org.ow2.asm:asm:jar:9.6:compile
[DEBUG]       com.thoughtworks.qdox:qdox:jar:2.0.3:compile
[DEBUG]    org.codehaus.plexus:plexus-compiler-api:jar:2.15.0:compile
[DEBUG]    org.codehaus.plexus:plexus-compiler-manager:jar:2.15.0:compile
[DEBUG]       javax.inject:javax.inject:jar:1:compile
[DEBUG]       org.codehaus.plexus:plexus-xml:jar:3.0.0:compile (version managed from default)
[DEBUG]    org.codehaus.plexus:plexus-compiler-javac:jar:2.15.0:runtime
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:4.0.0:compile
[DEBUG] Created new class realm plugin>org.apache.maven.plugins:maven-compiler-plugin:3.13.0
[DEBUG] Importing foreign packages into class realm plugin>org.apache.maven.plugins:maven-compiler-plugin:3.13.0
[DEBUG]   Imported:  < project>edu.hm.hafner:codingstyle:5.3.0-SNAPSHOT
[DEBUG] Populating class realm plugin>org.apache.maven.plugins:maven-compiler-plugin:3.13.0
[DEBUG]   Included: org.apache.maven.plugins:maven-compiler-plugin:jar:3.13.0
[DEBUG]   Included: org.apache.maven.shared:maven-shared-utils:jar:3.4.2
[DEBUG]   Included: commons-io:commons-io:jar:2.11.0
[DEBUG]   Included: org.apache.maven.shared:maven-shared-incremental:jar:1.1
[DEBUG]   Included: org.codehaus.plexus:plexus-java:jar:1.2.0
[DEBUG]   Included: org.ow2.asm:asm:jar:9.6
[DEBUG]   Included: com.thoughtworks.qdox:qdox:jar:2.0.3
[DEBUG]   Included: org.codehaus.plexus:plexus-compiler-api:jar:2.15.0
[DEBUG]   Included: org.codehaus.plexus:plexus-compiler-manager:jar:2.15.0
[DEBUG]   Included: org.codehaus.plexus:plexus-xml:jar:3.0.0
[DEBUG]   Included: org.codehaus.plexus:plexus-compiler-javac:jar:2.15.0
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:4.0.0
[DEBUG] Loading mojo org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile from plugin realm ClassRealm[plugin>org.apache.maven.plugins:maven-compiler-plugin:3.13.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@63c12fb0]
[DEBUG] Configuring mojo execution 'org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile:default-compile' with basic configurator -->
[DEBUG]   (s) groupId = com.google.errorprone
[DEBUG]   (s) artifactId = error_prone_core
[DEBUG]   (s) version = 2.36.0
[DEBUG]   (s) groupId = com.uber.nullaway
[DEBUG]   (s) artifactId = nullaway
[DEBUG]   (s) version = 0.12.1
[DEBUG]   (s) groupId = org.mockito
[DEBUG]   (s) artifactId = mockito-errorprone
[DEBUG]   (s) version = 5.14.2
[DEBUG]   (f) annotationProcessorPaths = [com.google.errorprone:error_prone_core:2.36.0.jar, com.uber.nullaway:nullaway:0.12.1.jar, org.mockito:mockito-errorprone:5.14.2.jar]
[DEBUG]   (f) annotationProcessorPathsUseDepMgmt = false
[DEBUG]   (f) basedir = /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle
[DEBUG]   (f) buildDirectory = /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target
[DEBUG]   (f) compilePath = [/Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/classes, /Users/hafner/.m2/repository/com/github/spotbugs/spotbugs-annotations/4.8.6/spotbugs-annotations-4.8.6.jar, /Users/hafner/.m2/repository/com/google/errorprone/error_prone_annotations/2.36.0/error_prone_annotations-2.36.0.jar, /Users/hafner/.m2/repository/org/apache/commons/commons-lang3/3.17.0/commons-lang3-3.17.0.jar, /Users/hafner/.m2/repository/commons-io/commons-io/2.17.0/commons-io-2.17.0.jar]
[DEBUG]   (f) compileSourceRoots = [/Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java]
[DEBUG]   (f) compilerArgs = [-Xlint:-varargs, -J--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, -J--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, -J--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED, -J--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, -J--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED, -J--add-exports=jdk.compiler/com.sun.tools.javac.processing=ALL-UNNAMED, -J--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, -J--add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED, -J--add-opens=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED, -Xplugin:ErrorProne  -XepExcludedPaths:.*/generated-test-sources/.*  -XepAllDisabledChecksAsWarnings  -XepIgnoreUnknownCheckNames  -XepDisableWarningsInGeneratedCode  -XepAllErrorsAsWarnings  -Xep:NullAway:WARN  -XepOpt:NullAway:AnnotatedPackages=edu.hm.hafner  -Xep:PreferredInterfaceType:OFF  -Xep:YodaCondition:OFF  -Xep:ReturnMissingNullable:OFF  -Xep:CannotMockFinalMethod:OFF  -Xep:Java8ApiChecker:OFF  -Xep:ImmutableMemberCollection:OFF  -Xep:PreferJavaTimeOverload:OFF  -Xep:EqualsGetClass:OFF  -Xep:AndroidJdkLibsChecker:OFF  -Xep:Java7ApiChecker:OFF  -Xep:Var:OFF  -Xep:PrivateConstructorForUtilityClass:OFF  -Xep:MethodCanBeStatic:OFF  -Xep:WildcardImport:OFF  -Xep:ThrowsUncheckedException:OFF  -Xep:UnusedMethod:OFF  -Xep:BooleanParameter:OFF  -Xep:UnnecessaryFinal:OFF  -Xep:NullableDereference:OFF, -XDcompilePolicy=simple]
[DEBUG]   (f) compilerId = javac
[DEBUG]   (f) createMissingPackageInfoClass = true
[DEBUG]   (f) debug = true
[DEBUG]   (f) debugFileName = javac
[DEBUG]   (f) enablePreview = false
[DEBUG]   (f) encoding = UTF-8
[DEBUG]   (f) failOnError = true
[DEBUG]   (f) failOnWarning = false
[DEBUG]   (f) fileExtensions = [jar, class]
[DEBUG]   (f) forceJavacCompilerUse = false
[DEBUG]   (f) forceLegacyJavacApi = false
[DEBUG]   (f) fork = true
[DEBUG]   (f) generatedSourcesDirectory = /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/generated-sources/annotations
[DEBUG]   (f) mojoExecution = org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile {execution: default-compile}
[DEBUG]   (f) optimize = false
[DEBUG]   (f) outputDirectory = /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/classes
[DEBUG]   (f) parameters = false
[DEBUG]   (f) project = MavenProject: edu.hm.hafner:codingstyle:5.3.0-SNAPSHOT @ /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/pom.xml
[DEBUG]   (f) projectArtifact = edu.hm.hafner:codingstyle:jar:5.3.0-SNAPSHOT
[DEBUG]   (s) release = 17
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@5261ec9
[DEBUG]   (f) showCompilationChanges = false
[DEBUG]   (f) showDeprecation = false
[DEBUG]   (f) showWarnings = true
[DEBUG]   (f) skipMultiThreadWarning = false
[DEBUG]   (f) source = 1.8
[DEBUG]   (f) staleMillis = 0
[DEBUG]   (s) target = 1.8
[DEBUG]   (f) useIncrementalCompilation = true
[DEBUG]   (f) verbose = false
[DEBUG] -- end configuration --
[DEBUG] Using compiler 'javac'.
[DEBUG] Adding /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/generated-sources/annotations to compile source roots:
  /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java
[DEBUG] New compile source roots:
  /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java
  /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/generated-sources/annotations
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=83192, ConflictMarker.markTime=33542, ConflictMarker.nodeCount=98, ConflictIdSorter.graphTime=50430, ConflictIdSorter.topsortTime=17065, ConflictIdSorter.conflictIdCount=32, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=568799, ConflictResolver.conflictItemCount=46, DfDependencyCollector.collectTime=108504970, DfDependencyCollector.transformTime=770243}
[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/TreeString.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/SecureXmlParserFactory.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/Generated.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PackageDetectorFactory.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PrefixLogger.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/KotlinPackageDetector.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/ResourceExtractor.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/LineRange.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/module-info.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/LineRangeList.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PackageDetector.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/LookaheadStream.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/JavaPackageDetector.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PathUtil.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/Ensure.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/package-info.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PackageDetectorRunner.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/CSharpNamespaceDetector.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/TreeStringBuilder.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/FilteredLog.java
[INFO]  Stale source detected: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/VisibleForTesting.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/CSharpNamespaceDetector.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/Ensure.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/FilteredLog.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/Generated.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/JavaPackageDetector.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/KotlinPackageDetector.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/LineRange.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/LineRangeList.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/LookaheadStream.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PackageDetector.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PackageDetectorFactory.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PackageDetectorRunner.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PathUtil.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PrefixLogger.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/ResourceExtractor.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/SecureXmlParserFactory.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/TreeString.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/TreeStringBuilder.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/VisibleForTesting.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/package-info.java
[INFO]  Input tree files (+): /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/module-info.java
[INFO] Recompiling the module because of changed source code.
[DEBUG] Classpath:
[DEBUG]  /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/classes
[DEBUG] Modulepath:
[DEBUG]  /Users/hafner/.m2/repository/com/github/spotbugs/spotbugs-annotations/4.8.6/spotbugs-annotations-4.8.6.jar
[DEBUG]  /Users/hafner/.m2/repository/com/google/errorprone/error_prone_annotations/2.36.0/error_prone_annotations-2.36.0.jar
[DEBUG]  /Users/hafner/.m2/repository/org/apache/commons/commons-lang3/3.17.0/commons-lang3-3.17.0.jar
[DEBUG]  /Users/hafner/.m2/repository/commons-io/commons-io/2.17.0/commons-io-2.17.0.jar
[DEBUG] Source roots:
[DEBUG]  /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java
[DEBUG]  /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/generated-sources/annotations
[DEBUG] Command line options:
[DEBUG] -d /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/classes -classpath /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/classes: --module-path /Users/hafner/.m2/repository/com/github/spotbugs/spotbugs-annotations/4.8.6/spotbugs-annotations-4.8.6.jar:/Users/hafner/.m2/repository/com/google/errorprone/error_prone_annotations/2.36.0/error_prone_annotations-2.36.0.jar:/Users/hafner/.m2/repository/org/apache/commons/commons-lang3/3.17.0/commons-lang3-3.17.0.jar:/Users/hafner/.m2/repository/commons-io/commons-io/2.17.0/commons-io-2.17.0.jar: -sourcepath /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java:/Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/generated-sources/annotations: /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/CSharpNamespaceDetector.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/Ensure.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/FilteredLog.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/Generated.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/JavaPackageDetector.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/KotlinPackageDetector.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/LineRange.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/LineRangeList.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/LookaheadStream.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PackageDetector.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PackageDetectorFactory.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PackageDetectorRunner.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PathUtil.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/PrefixLogger.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/ResourceExtractor.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/SecureXmlParserFactory.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/TreeString.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/TreeStringBuilder.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/VisibleForTesting.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/edu/hm/hafner/util/package-info.java /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/src/main/java/module-info.java -s /Users/hafner/git/warnings-ng-plugin-devenv/codingstyle/target/generated-sources/annotations -processorpath /Users/hafner/.m2/repository/com/google/errorprone/error_prone_core/2.36.0/error_prone_core-2.36.0.jar:/Users/hafner/.m2/repository/com/google/errorprone/error_prone_annotation/2.36.0/error_prone_annotation-2.36.0.jar:/Users/hafner/.m2/repository/com/google/errorprone/error_prone_type_annotations/2.36.0/error_prone_type_annotations-2.36.0.jar:/Users/hafner/.m2/repository/com/google/errorprone/error_prone_check_api/2.36.0/error_prone_check_api-2.36.0.jar:/Users/hafner/.m2/repository/io/github/java-diff-utils/java-diff-utils/4.12/java-diff-utils-4.12.jar:/Users/hafner/.m2/repository/com/github/kevinstern/software-and-algorithms/1.0/software-and-algorithms-1.0.jar:/Users/hafner/.m2/repository/com/github/ben-manes/caffeine/caffeine/3.0.5/caffeine-3.0.5.jar:/Users/hafner/.m2/repository/com/google/googlejavaformat/google-java-format/1.19.1/google-java-format-1.19.1.jar:/Users/hafner/.m2/repository/org/pcollections/pcollections/4.0.1/pcollections-4.0.1.jar:/Users/hafner/.m2/repository/com/google/guava/guava/32.1.1-jre/guava-32.1.1-jre.jar:/Users/hafner/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/Users/hafner/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/hafner/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/Users/hafner/.m2/repository/org/checkerframework/checker-qual/3.33.0/checker-qual-3.33.0.jar:/Users/hafner/.m2/repository/com/google/j2objc/j2objc-annotations/2.8/j2objc-annotations-2.8.jar:/Users/hafner/.m2/repository/com/google/auto/auto-common/1.2.2/auto-common-1.2.2.jar:/Users/hafner/.m2/repository/io/github/eisop/dataflow-errorprone/3.41.0-eisop1/dataflow-errorprone-3.41.0-eisop1.jar:/Users/hafner/.m2/repository/com/google/auto/value/auto-value-annotations/1.9/auto-value-annotations-1.9.jar:/Users/hafner/.m2/repository/com/google/errorprone/error_prone_annotations/2.36.0/error_prone_annotations-2.36.0.jar:/Users/hafner/.m2/repository/com/google/protobuf/protobuf-java/3.25.5/protobuf-java-3.25.5.jar:/Users/hafner/.m2/repository/com/google/auto/service/auto-service-annotations/1.0.1/auto-service-annotations-1.0.1.jar:/Users/hafner/.m2/repository/org/jspecify/jspecify/1.0.0/jspecify-1.0.0.jar:/Users/hafner/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/Users/hafner/.m2/repository/com/uber/nullaway/nullaway/0.12.1/nullaway-0.12.1.jar:/Users/hafner/.m2/repository/org/checkerframework/dataflow-nullaway/3.48.0/dataflow-nullaway-3.48.0.jar:/Users/hafner/.m2/repository/org/mockito/mockito-errorprone/5.14.2/mockito-errorprone-5.14.2.jar:/Users/hafner/.m2/repository/org/mockito/mockito-core/5.14.2/mockito-core-5.14.2.jar:/Users/hafner/.m2/repository/net/bytebuddy/byte-buddy/1.15.4/byte-buddy-1.15.4.jar:/Users/hafner/.m2/repository/net/bytebuddy/byte-buddy-agent/1.15.4/byte-buddy-agent-1.15.4.jar:/Users/hafner/.m2/repository/org/objenesis/objenesis/3.3/objenesis-3.3.jar: -g --release 17 -encoding UTF-8 -Xlint:-varargs -Xplugin:ErrorProne  -XepExcludedPaths:.*/generated-test-sources/.*  -XepAllDisabledChecksAsWarnings  -XepIgnoreUnknownCheckNames  -XepDisableWarningsInGeneratedCode  -XepAllErrorsAsWarnings  -Xep:NullAway:WARN  -XepOpt:NullAway:AnnotatedPackages=edu.hm.hafner  -Xep:PreferredInterfaceType:OFF  -Xep:YodaCondition:OFF  -Xep:ReturnMissingNullable:OFF  -Xep:CannotMockFinalMethod:OFF  -Xep:Java8ApiChecker:OFF  -Xep:ImmutableMemberCollection:OFF  -Xep:PreferJavaTimeOverload:OFF  -Xep:EqualsGetClass:OFF  -Xep:AndroidJdkLibsChecker:OFF  -Xep:Java7ApiChecker:OFF  -Xep:Var:OFF  -Xep:PrivateConstructorForUtilityClass:OFF  -Xep:MethodCanBeStatic:OFF  -Xep:WildcardImport:OFF  -Xep:ThrowsUncheckedException:OFF  -Xep:UnusedMethod:OFF  -Xep:BooleanParameter:OFF  -Xep:UnnecessaryFinal:OFF  -Xep:NullableDereference:OFF -XDcompilePolicy=simple --module-version 5.3.0-SNAPSHOT
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 21 source files with javac [forked debug release 17 module-path] to target/classes
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR]         at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:232)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:294)
        at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:178)
        at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:64)
        at jdk.compiler/com.sun.tools.javac.Main.main(Main.java:50)
Caused by: com.google.errorprone.InvalidCommandLineOptionException: The default --should-stop=ifError policy (INIT) is not supported by Error Prone, pass --should-stop=ifError=FLOW instead
        at com.google.errorprone.BaseErrorProneJavaCompiler.checkShouldStopIfErrorPolicy(BaseErrorProneJavaCompiler.java:197)
        at com.google.errorprone.BaseErrorProneJavaCompiler.addTaskListener(BaseErrorProneJavaCompiler.java:87)
        at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:34)
        at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:256)
        at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:230)
        ... 4 more

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.842 s
[INFO] Finished at: 2024-11-27T11:13:37+01:00
[INFO] ------------------------------------------------------------------------
```

The corresponding dependabot PR can be found at: https://github.com/uhafner/codingstyle/pull/1238
The CI failure is visible here: https://github.com/uhafner/codingstyle/actions/runs/12047294734/job/33589530685?pr=1238
My configuration is here: https://github.com/uhafner/codingstyle/blob/83f679ba6bc53b30cb59087881af6b44c6df3b87/pom.xml#L566-L670

**Comment by Stephan202** [comment]
Hey @uhafner! You can add this flag using [`<compilerArgs>`](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#compilerArgs). See the [Error Prone installation documentation](https://errorprone.info/docs/installation#maven) for an example.

**Comment by bluemods** [comment]
For anyone looking at this who is using the Gradle plugin (https://github.com/tbroyer/gradle-errorprone-plugin) you can fix it by adding the following to your `build.gradle`:

```groovy
tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << "--should-stop=ifError=FLOW"
}
```

**Comment by tbroyer** [comment]
Or "just" update to version 4.1.0: https://github.com/tbroyer/gradle-errorprone-plugin/releases/tag/v4.1.0
