### ISSUE TITLE
Version 2.0.14: error: An unhandled exception was thrown by the Error Prone static analysis plugin

### ISSUE THREAD

**Issue by bananetomate** [google/error-prone#473]
This morning, with the latest 2.0.14 version, we started having unhandled exceptions with ErrorProne when compiling using the Gradle plugin. The exact error is:
```
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
public class OpenIDConnectDIConfig extends WebSecurityConfigurerAdapter {
       ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.0.14
     Stack Trace:
```
I cannot find the stacktrace, even using --debug ...

Here is a stripped version of an example of a file for which the error occurred:
```
package com.company.plt.security.mitreid;

import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

// @cs-: ClassDataAbstractionCoupling
@Configuration
@EnableWebSecurity
public class OpenIDConnectDIConfig extends WebSecurityConfigurerAdapter {


}
```
Note: If I remove the extends, error prone successfully compiles.

Reverting back to 2.0.13 fixed the problem.

**Comment by bananetomate** [comment]
Forgot: Spring security config version is 4.1.1-RELEASE

**Comment by cushon** [comment]
Can you try adding this to your gradle config? It should enable stack traces for the crash:

```
tasks.withType(JavaCompile) {
  options.compilerArgs += [ '-XDdev' ]
}
```

If I build your example with the following deps, I can repro a crash. Adding `spring-web` to the classpath works around it. We can fix error prone to handle the missing symbol better, but I'm curious if this is the same issue you encountered?

```
  compile 'org.springframework:spring-core:4.1.1.RELEASE'
  compile 'org.springframework:spring-context:4.1.1.RELEASE'
  compile 'org.springframework.security:spring-security-config:4.1.1.RELEASE'
  compile 'javax.servlet:javax.servlet-api:3.0.1'
```

```
public class OpenIDConnectDIConfig extends WebSecurityConfigurerAdapter {
       ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.0.14
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.springframework.web.accept.ContentNegotiationStrategy not found
        at com.sun.tools.javac.code.ClassFinder.newCompletionFailure(ClassFinder.java:374)
        at com.sun.tools.javac.code.ClassFinder.classFileNotFound(ClassFinder.java:362)
...
        at com.sun.tools.javac.code.Types.isFunctionalInterface(Types.java:592)
        at com.google.errorprone.bugpatterns.FunctionalInterfaceClash$$Lambda$63/1655397987.test(Unknown Source)
...
        at com.google.errorprone.bugpatterns.FunctionalInterfaceClash.matchClass(FunctionalInterfaceClash.java:64)
```

**Comment by ghenkes** [comment]
I'm seeing something similar. Here's the output using the `-XDdev` compiler arg

```
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
public class AlvaJNDIConfiguration extends JNDIConfiguration {
       ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.0.14
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.apache.commons.logging.Log not found
  	at com.sun.tools.javac.code.ClassFinder.newCompletionFailure(ClassFinder.java:374)
  	at com.sun.tools.javac.code.ClassFinder.classFileNotFound(ClassFinder.java:362)
  	at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:355)
  	at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:279)
  	at com.sun.tools.javac.code.ClassFinder.access$000(ClassFinder.java:72)
  	at com.sun.tools.javac.code.ClassFinder$1.complete(ClassFinder.java:159)
  	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:579)
  	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1074)
  	at com.sun.tools.javac.code.Symbol$ClassSymbol.getInterfaces(Symbol.java:1085)
  	at com.sun.tools.javac.code.Types$16.visitClassType(Types.java:2344)
  	at com.sun.tools.javac.code.Types$16.visitClassType(Types.java:2335)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:978)
  	at com.sun.tools.javac.code.Types$UnaryVisitor.visit(Types.java:4574)
  	at com.sun.tools.javac.code.Types.interfaces(Types.java:2332)
  	at com.sun.tools.javac.code.Types$MembersClosureCache.visitClassType(Types.java:2722)
  	at com.sun.tools.javac.code.Types$MembersClosureCache.visitClassType(Types.java:2662)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:978)
  	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4495)
  	at com.sun.tools.javac.code.Types.membersClosure(Types.java:2745)
  	at com.sun.tools.javac.code.Types$DescriptorCache.get(Types.java:396)
  	at com.sun.tools.javac.code.Types.findDescriptorType(Types.java:575)
  	at com.sun.tools.javac.code.Types.isFunctionalInterface(Types.java:592)
  	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
  	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
  	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
  	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
  	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
  	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
  	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
  	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
  	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
  	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
  	at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:459)
  	at com.google.errorprone.bugpatterns.FunctionalInterfaceClash.matchClass(FunctionalInterfaceClash.java:64)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:629)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:113)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1303)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1247)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:858)
  	at com.sun.tools.javac.main.Main.compile(Main.java:253)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:214)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:106)
  	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
  	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:943)
  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:137)
  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
1 error
An exception has occurred in the compiler (1.9.0-internal). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the database for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.google.errorprone.ErrorProneError:
FunctionalInterfaceClash: An exception was thrown by Error Prone: class file for org.apache.commons.logging.Log not found
public class AlvaJNDIConfiguration extends JNDIConfiguration {
^

Caused by: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.apache.commons.logging.Log not found
	at com.sun.tools.javac.code.ClassFinder.newCompletionFailure(ClassFinder.java:374)
	at com.sun.tools.javac.code.ClassFinder.classFileNotFound(ClassFinder.java:362)
	at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:355)
	at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:279)
	at com.sun.tools.javac.code.ClassFinder.access$000(ClassFinder.java:72)
	at com.sun.tools.javac.code.ClassFinder$1.complete(ClassFinder.java:159)
	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:579)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1074)
	at com.sun.tools.javac.code.Symbol$ClassSymbol.getInterfaces(Symbol.java:1085)
	at com.sun.tools.javac.code.Types$16.visitClassType(Types.java:2344)
	at com.sun.tools.javac.code.Types$16.visitClassType(Types.java:2335)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:978)
	at com.sun.tools.javac.code.Types$UnaryVisitor.visit(Types.java:4574)
	at com.sun.tools.javac.code.Types.interfaces(Types.java:2332)
	at com.sun.tools.javac.code.Types$MembersClosureCache.visitClassType(Types.java:2722)
	at com.sun.tools.javac.code.Types$MembersClosureCache.visitClassType(Types.java:2662)
	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:978)
	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4495)
	at com.sun.tools.javac.code.Types.membersClosure(Types.java:2745)
	at com.sun.tools.javac.code.Types$DescriptorCache.get(Types.java:396)
	at com.sun.tools.javac.code.Types.findDescriptorType(Types.java:575)
	at com.sun.tools.javac.code.Types.isFunctionalInterface(Types.java:592)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:459)
	at com.google.errorprone.bugpatterns.FunctionalInterfaceClash.matchClass(FunctionalInterfaceClash.java:64)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:629)
	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:113)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1303)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1247)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:858)
	at com.sun.tools.javac.main.Main.compile(Main.java:253)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:214)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:106)
	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:943)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:137)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by Stephan202** [comment]
In our project we saw a variation on the `class file for org.apache.commons.logging.Log not found` message, just with another class (`com.fasterxml.jackson.databind.ObjectMapper`). We resolved it by changing the scope of the Maven dependency containing the class from `test` to `provided`, which was arguably more correct. (In this particular module the class was only explicitly referenced by test code, but the main source code does rely on said class being provided at runtime.)

**Comment by bananetomate** [comment]
Sorry for the delay. The error I get with the extra XDdev argument is
```
1 error
An exception has occurred in the compiler (1.9.0-internal). Please file a bug at the Java Bug Database (http://bugreport.java.com/bugreport/) after checking the database for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.google.errorprone.ErrorProneError:
C:\Dev\sources\company\project\module-api\src\main\java\com\company\plt\security\mitreid\OpenIDConnectDIConfig.java:36: FunctionalInterfaceClash: An exception was thrown by Error Prone: class file for org.springframework.web.accept.ContentNegotiationStrategy not found
@Configuration
^

Caused by: com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.springframework.web.accept.ContentNegotiationStrategy not found
        at com.sun.tools.javac.code.ClassFinder.newCompletionFailure(ClassFinder.java:374)
        at com.sun.tools.javac.code.ClassFinder.classFileNotFound(ClassFinder.java:362)
        at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:355)
        at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:279)
        at com.sun.tools.javac.code.ClassFinder.access$000(ClassFinder.java:72)
        at com.sun.tools.javac.code.ClassFinder$1.complete(ClassFinder.java:159)
        at com.sun.tools.javac.code.Symbol.complete(Symbol.java:579)
        at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1074)
        at com.sun.tools.javac.code.Symbol$ClassSymbol.getInterfaces(Symbol.java:1085)
        at com.sun.tools.javac.code.Types$16.visitClassType(Types.java:2344)
        at com.sun.tools.javac.code.Types$16.visitClassType(Types.java:2335)
        at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:978)
        at com.sun.tools.javac.code.Types$UnaryVisitor.visit(Types.java:4574)
        at com.sun.tools.javac.code.Types.interfaces(Types.java:2332)
        at com.sun.tools.javac.code.Types$MembersClosureCache.visitClassType(Types.java:2722)
        at com.sun.tools.javac.code.Types$MembersClosureCache.visitClassType(Types.java:2662)
        at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:978)
        at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4495)
        at com.sun.tools.javac.code.Types.membersClosure(Types.java:2745)
        at com.sun.tools.javac.code.Types$DescriptorCache.get(Types.java:396)
        at com.sun.tools.javac.code.Types.findDescriptorType(Types.java:575)
        at com.sun.tools.javac.code.Types.isFunctionalInterface(Types.java:592)
        at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
        at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.noneMatch(ReferencePipeline.java:459)
        at com.google.errorprone.bugpatterns.FunctionalInterfaceClash.matchClass(FunctionalInterfaceClash.java:64)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:629)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
        at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
        at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
        at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:113)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1303)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1247)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:858)
        at com.sun.tools.javac.main.Main.compile(Main.java:253)
        at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:214)
        at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:106)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
        at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:57)
        at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:25)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:127)
        at sun.reflect.GeneratedMethodAccessor536.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```
