### ISSUE TITLE
ArgumentParameterSwap causes exception

### ISSUE THREAD

**Issue by krisztiankocsis** [google/error-prone#485]
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
  {
  ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.0.14
     Stack Trace:
     java.lang.ArrayIndexOutOfBoundsException: 0
        at com.google.errorprone.bugpatterns.ArgumentParameterSwap.findSwaps(ArgumentParameterSwap.java:125)
        at com.google.errorprone.bugpatterns.ArgumentParameterSwap.matchMethodInvocation(ArgumentParameterSwap.java:111)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:952)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:144)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1614)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
        at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:434)
        at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:758)
        at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:144)
        at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1424)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:249)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:575)
        at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:144)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:996)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:207)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:943)
        at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:144)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:635)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
        at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
        at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
        at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
        at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
        at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:113)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1303)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1247)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:858)
        at com.sun.tools.javac.main.Main.compile(Main.java:253)
        at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:214)
        at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:106)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
        at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:57)
        at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:25)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
        at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:188)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:146)
        at sun.reflect.GeneratedMethodAccessor684.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Stephan202** [comment]
This particular exception was resolved in #453, but the fix introduced another failure; see [this comment](https://github.com/google/error-prone/issues/453#issuecomment-259391821).
