### ISSUE TITLE
NullPointerException in InjectAssistedInjectAndInjectOnConstructors.matchAnnotation (with v2.0.5)

### ISSUE THREAD

**Issue by aledsage** [google/error-prone#493]
When compiling my project, I got the output shown below (which failed the build, obviously):

```
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
  Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
  error-prone version: 2.0.5
  Stack Trace:
  java.lang.NullPointerException
        at com.google.errorprone.bugpatterns.InjectAssistedInjectAndInjectOnConstructors.matchAnnotation(InjectAssistedInjectAndInjectOnConstructors.java:83)
        at com.google.errorprone.scanner.ErrorProneScanner.visitAnnotation(ErrorProneScanner.java:462)
        at com.google.errorprone.scanner.ErrorProneScanner.visitAnnotation(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2532)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
        at com.sun.source.util.TreeScanner.visitPackage(TreeScanner.java:158)
        at com.sun.tools.javac.tree.JCTree$JCPackageDecl.accept(JCTree.java:600)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:45)
        at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:143)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:597)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:142)
        at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:563)
        at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:70)
        at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:45)
        at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:147)
        at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:115)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.postFlow(ErrorProneJavacJavaCompiler.java:123)
        at com.google.errorprone.ErrorProneJavacJavaCompiler.flow(ErrorProneJavacJavaCompiler.java:97)
        at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1262)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:859)
        at com.sun.tools.javac.main.Main.compile(Main.java:249)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:249)
        at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:159)
        at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:88)
        at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
1 error
```

**Comment by nglorioso** [comment]
Hello! This check has undergone a large amount of fixing since 2.0.5 (ex https://github.com/google/error-prone/commit/5946d0a6e3fbfaa4d567bbaf8b84ccfb9a478d13#diff-9a0d57d1b8cdbbdfe2fa1233162041fd)

Can you please try the newest version (2.0.15, or at least 2.0.13)?

**Comment by aledsage** [comment]
@nglorioso Unfortunately upgrading beyond 2.0.5 is tricky because of the need for Java 7 support [1] in jclouds [2]. Testing with 2.0.15 and Java 8, I did not get this `NullPointerException`.

With 2.0.5, we worked around it by removing `-Xep:AssistedInjectAndInjectOnConstructors:ERROR`.

[1] https://github.com/tbroyer/gradle-errorprone-plugin/issues/18
[2] jclouds.apache.org

**Comment by cushon** [comment]
That sounds like a good workaround.
