### ISSUE TITLE
ArrayIndexOutOfBoundsException at com.google.common.collect.RegularImmutableList.get

### ISSUE THREAD

**Issue by dpursehouse** [google/error-prone#494]
```
/Users/dpursehouse/git/gerrit/gerrit-httpd/src/main/java/com/google/gerrit/httpd/plugins/LfsPluginServlet.java:54: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
public class LfsPluginServlet extends HttpServlet
       ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:

     error-prone version: 2.0.15
     Stack Trace:
     java.lang.ArrayIndexOutOfBoundsException: 0
       	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:58)
       	at com.google.errorprone.bugpatterns.inject.guice.AssistedInjectScoping$1.matches(AssistedInjectScoping.java:95)
       	at com.google.errorprone.bugpatterns.inject.guice.AssistedInjectScoping$1.matches(AssistedInjectScoping.java:88)
       	at com.google.errorprone.matchers.Matchers$4.matches(Matchers.java:131)
       	at com.google.errorprone.bugpatterns.inject.guice.AssistedInjectScoping.matchClass(AssistedInjectScoping.java:107)
       	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:629)
       	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
       	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
       	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
       	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
       	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
       	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
       	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
       	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
       	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
       	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
       	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
       	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
       	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
       	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
       	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
       	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:113)
       	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1303)
       	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1257)
       	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:865)
       	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:97)
       	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
       	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
       	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
       	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
       	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:280)
       	at com.facebook.buck.jvm.java.Jsr199Javac.buildWithClasspath(Jsr199Javac.java:155)
       	at com.facebook.buck.jvm.java.JavacStep.tryBuildWithFirstOrderDeps(JavacStep.java:187)
       	at com.facebook.buck.jvm.java.JavacStep.execute(JavacStep.java:146)
       	at com.facebook.buck.jvm.java.JavacDirectToJarStep.execute(JavacDirectToJarStep.java:91)
       	at com.facebook.buck.step.DefaultStepRunner.runStepForBuildTarget(DefaultStepRunner.java:54)
       	at com.facebook.buck.rules.CachingBuildEngine.executeCommandsNowThatDepsAreBuilt(CachingBuildEngine.java:1399)
       	at com.facebook.buck.rules.CachingBuildEngine.lambda$11(CachingBuildEngine.java:340)
       	at com.facebook.buck.util.concurrent.WeightedListeningExecutorService.lambda$0(WeightedListeningExecutorService.java:77)
       	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1442)
       	at com.google.common.util.concurrent.Futures$AsyncChainingFuture.doTransform(Futures.java:1433)
       	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
       	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       	at java.lang.Thread.run(Thread.java:745)
```

**Comment by eaftan** [comment]
Could you provide repro instructions?

**Comment by nglorioso** [comment]
Hello! Thanks for reporting.

Do you get this consistently for every compile, or is it on occasion? I suspect https://github.com/google/error-prone/blob/master/core/src/main/java/com/google/errorprone/bugpatterns/inject/guice/AssistedInjectScoping.java#L95 (a static field with mutable state from multiple threads), but if it reproduces for every compile, that'd be more interesting.

**Comment by dpursehouse** [comment]
@eaftan @nglorioso It happened when I was building Gerrit Code Review for the first time with buck and error-prone enabled [using this change](https://gerrit-review.googlesource.com/#/c/92919/).  I got the stack trace and reported it here as requested. It hasn't happened again since then.
