### ISSUE TITLE
IllegalStateException encountered when apply StringIsEmpty sample refaster template 

### ISSUE THREAD

**Issue by sammyhk** [google/error-prone#520]
We are using 2.0.16-SNAPSHOT to try to apply custom refaster template. When follow the example `StringIsEmpty` template in http://errorprone.info/docs/refaster, and apply to a source code which contains the following pattern:
```
str.equals("")
```
The compiler fail and throw IllegalStateException as following:
```
An exception has occurred in the compiler (9-internal). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.lang.IllegalStateException: No binding for Key{identifier=string}
	at com.google.errorprone.refaster.Inliner.getBinding(Inliner.java:178)
	at com.google.errorprone.refaster.UFreeIdent.inline(UFreeIdent.java:56)
	at com.google.errorprone.refaster.UFreeIdent.inline(UFreeIdent.java:35)
	at com.google.errorprone.refaster.UMemberSelect.inline(UMemberSelect.java:88)
	at com.google.errorprone.refaster.UMemberSelect.inline(UMemberSelect.java:34)
	at com.google.errorprone.refaster.UMethodInvocation.inline(UMethodInvocation.java:78)
	at com.google.errorprone.refaster.UMethodInvocation.inline(UMethodInvocation.java:35)
	at com.google.errorprone.refaster.ExpressionTemplate.replace(ExpressionTemplate.java:194)
	at com.google.errorprone.refaster.ExpressionTemplate.replace(ExpressionTemplate.java:64)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:107)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:52)
	at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:433)
	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1424)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:86)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:113)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:52)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:996)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:86)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:113)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:52)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
	at com.google.errorprone.refaster.RefasterScanner.visitClass(RefasterScanner.java:73)
	at com.google.errorprone.refaster.RefasterScanner.visitClass(RefasterScanner.java:52)
	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:86)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:113)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:52)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:86)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:113)
	at com.google.errorprone.refaster.RefasterScanner.scan(RefasterScanner.java:52)
	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
	at com.google.errorprone.refaster.RefasterRule.apply(RefasterRule.java:105)
	at com.google.errorprone.CompositeCodeTransformer.apply(CompositeCodeTransformer.java:47)
	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1277)
	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1226)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:840)
	at com.sun.tools.javac.main.Main.compile(Main.java:257)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:229)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:107)
	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:785)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by nglorioso** [comment]
Hello! Upon consultation with @lowasser, it looks like I messed up the template. The parameter names need to match, so instead of 's', it should be 'string' to match the @AfterTemplate version.

Fixing it now!

**Comment by Bananeweizen** [comment]
This one seems to be fixed already, the documentation looks good.

**Comment by eaftan** [comment]
Thanks, closing this one.
