### ISSUE TITLE
Tolerate missing symbols in `URLEqualsHashCode`

### ISSUE THREAD

**Issue by Stephan202** [google/error-prone#542]
We have a Maven module in which a Spring bean of type `org.springframework.validation.beanvalidation.LocalValidatorFactoryBean` is declared, while `javax.validation.Validator` is not on the classpath. (Dependants of this module _do_ provide a validator, if applicable.) In code:

* `pom.xml` excerpt:
    ```xml
    <dependencies>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
    </dependencies>
    ```
* Spring configuration (trimmed):
    ```java
	@Configuration
	public class DummyConfig {
	    @Bean
	    LocalValidatorFactoryBean validatorFactory() {
	        return new LocalValidatorFactoryBean();
	    }
	}
    ```

When the `URLEqualsHashCode` analyzer is enabled, compilation fails. Output with `-XDdev`:
```
/some/path/to/DummyConfig.java:11: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
        return new LocalValidatorFactoryBean();
               ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.0.17
     Stack Trace:
     com.sun.tools.javac.code.Symbol$CompletionFailure: class file for javax.validation.Validator not found
  	at com.sun.tools.javac.code.ClassFinder.newCompletionFailure(ClassFinder.java:382)
  	at com.sun.tools.javac.code.ClassFinder.classFileNotFound(ClassFinder.java:370)
  	at com.sun.tools.javac.code.ClassFinder.fillIn(ClassFinder.java:363)
  	at com.sun.tools.javac.code.ClassFinder.complete(ClassFinder.java:286)
  	at com.sun.tools.javac.code.ClassFinder.access$000(ClassFinder.java:73)
  	at com.sun.tools.javac.code.ClassFinder$1.complete(ClassFinder.java:165)
  	at com.sun.tools.javac.code.Symbol.complete(Symbol.java:590)
  	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1085)
  	at com.sun.tools.javac.code.Symbol$ClassSymbol.getSuperclass(Symbol.java:1111)
  	at com.sun.tools.javac.code.Types$15.visitClassType(Types.java:2304)
  	at com.sun.tools.javac.code.Types$15.visitClassType(Types.java:2293)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1003)
  	at com.sun.tools.javac.code.Types$UnaryVisitor.visit(Types.java:4620)
  	at com.sun.tools.javac.code.Types.supertype(Types.java:2290)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1949)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1938)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1003)
  	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4541)
  	at com.sun.tools.javac.code.Types.asSuper(Types.java:1935)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1958)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1938)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1003)
  	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4541)
  	at com.sun.tools.javac.code.Types.asSuper(Types.java:1935)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1951)
  	at com.sun.tools.javac.code.Types$12.visitClassType(Types.java:1938)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1003)
  	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4541)
  	at com.sun.tools.javac.code.Types.asSuper(Types.java:1935)
  	at com.sun.tools.javac.code.Types$4.visitClassType(Types.java:930)
  	at com.sun.tools.javac.code.Types$4.visitClassType(Types.java:851)
  	at com.sun.tools.javac.code.Type$ClassType.accept(Type.java:1003)
  	at com.sun.tools.javac.code.Types$DefaultTypeVisitor.visit(Types.java:4541)
  	at com.sun.tools.javac.code.Types.isSubtype(Types.java:847)
  	at com.sun.tools.javac.code.Types.isSubtype(Types.java:818)
  	at com.google.errorprone.util.ASTHelpers.isSubtype(ASTHelpers.java:722)
  	at com.google.errorprone.bugpatterns.URLEqualsHashCode$URLTypeArgumentMatcher.matches(URLEqualsHashCode.java:84)
  	at com.google.errorprone.matchers.Matchers$5.matches(Matchers.java:148)
  	at com.google.errorprone.bugpatterns.URLEqualsHashCode.matchNewClass(URLEqualsHashCode.java:62)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:997)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1675)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:71)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:469)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:1066)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1518)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:71)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:575)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:996)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:71)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:943)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:71)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:635)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:71)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:52)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1277)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1226)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:840)
  	at com.sun.tools.javac.main.Main.compile(Main.java:257)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:229)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:107)
  	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
  	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:219)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:498)
  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:943)
  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:137)
  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:185)
  	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:181)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Stephan202** [comment]
For others hitting this issue: you can declare a `provided`-scope dependency on whatever library provides the missing class. This avoids the error without the workaround leaking to dependant libraries.

**Comment by Stephan202** [comment]
@cushon, following the closure of PR #790, how should this issue best be dealt with instead? Maybe Error Prone can log a more informative message, informing the user that their classpath is incomplete, lacking some type _X_?

**Comment by cushon** [comment]
We should be catching and logging `CompletionFailure`s. If you're still getting stack traces for these with the `-Xplugin:` integration and without passing `-XDdev`, please re-open.
