### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by KathyApplebaum** [google/error-prone#558]
Intellij 2016.3 on OS X Sierra, Java 8 (1.8.0_111)

Error:(204, 19) java: An unhandled exception was thrown by the Error Prone static analysis plugin.
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.0.9
     Stack Trace:
     java.lang.OutOfMemoryError: GC overhead limit exceeded
  	at com.sun.tools.javac.code.Scope$ScopeImpl.<init>(Scope.java:292)
  	at com.sun.tools.javac.code.Scope$ErrorScope.<init>(Scope.java:1050)
  	at com.sun.tools.javac.code.Type$ErrorType.<init>(Type.java:2153)
  	at com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1078)
  	at com.sun.tools.javac.code.ClassFinder.loadClass(ClassFinder.java:397)
  	at com.sun.tools.javac.comp.Resolve.loadClass(Resolve.java:1882)
  	at com.sun.tools.javac.comp.Resolve.findIdentInPackage(Resolve.java:2112)
  	at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:353)
  	at com.sun.tools.javac.comp.Attr$IdentAttributer.visitMemberSelect(Attr.java:344)
  	at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:2077)
  	at com.sun.tools.javac.comp.Attr.attribIdent(Attr.java:340)
  	at com.sun.tools.javac.main.JavaCompiler.resolveIdent(JavaCompiler.java:672)
  	at com.google.errorprone.VisitorState.getTypeFromString(VisitorState.java:169)
  	at com.google.errorprone.suppliers.Suppliers$5.get(Suppliers.java:120)
  	at com.google.errorprone.suppliers.Suppliers$5.get(Suppliers.java:117)
  	at com.google.errorprone.predicates.type.Exact.apply(Exact.java:37)
  	at com.google.errorprone.matchers.method.ConstructorClassMatcherImpl.matchResult(ConstructorClassMatcherImpl.java:38)
  	at com.google.errorprone.matchers.method.ConstructorClassMatcherImpl.matchResult(ConstructorClassMatcherImpl.java:30)
  	at com.google.errorprone.matchers.method.AbstractChainedMatcher.matchResult(AbstractChainedMatcher.java:40)
  	at com.google.errorprone.matchers.method.AbstractChainedMatcher.matchResult(AbstractChainedMatcher.java:38)
  	at com.google.errorprone.matchers.method.AbstractSimpleMatcher.matches(AbstractSimpleMatcher.java:31)
  	at com.google.errorprone.matchers.method.AbstractSimpleMatcher.matches(AbstractSimpleMatcher.java:26)
  	at com.google.errorprone.matchers.Matchers$5.matches(Matchers.java:148)
  	at com.google.errorprone.bugpatterns.MisusedWeekYear.matchNewClass(MisusedWeekYear.java:121)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:859)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1675)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)

**Comment by cushon** [comment]
Which build system / integrate are you using? You may just need to set a larger heap size.

**Comment by KathyApplebaum** [comment]
Larger heap did the trick. Might be a good idea to change the error to suggest that first, since otherwise I would have done it first. :)

**Comment by cushon** [comment]
Good point. Perhaps the "please file a bug" handling should just ignore OOMs.
