### ISSUE TITLE
An unhandled exception was thrown by the Error Prone

### ISSUE THREAD

**Issue by liutikas** [google/error-prone#566]
frameworks/support/fragment/java/android/support/v4/app/Fragment.java:186: error:  static analysis plugin.
public class Fragment implements ComponentCallbacks, OnCreateContextMenuListener {
       ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.0.18
     Stack Trace:
     java.lang.NullPointerException
  	at com.sun.tools.javac.comp.Resolve$AbstractMethodCheck.treeForDiagnostics(Resolve.java:764)
  	at com.sun.tools.javac.comp.Resolve$AbstractMethodCheck.argumentsAcceptable(Resolve.java:724)
  	at com.sun.tools.javac.comp.Resolve$4.argumentsAcceptable(Resolve.java:848)
  	at com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:582)
  	at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1503)
  	at com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1684)
  	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1753)
  	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1727)
  	at com.sun.tools.javac.comp.Resolve$9.doLookup(Resolve.java:2433)
  	at com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3041)
  	at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3291)
  	at com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2430)
  	at com.sun.tools.javac.comp.Resolve.resolveInternalMethod(Resolve.java:2500)
  	at com.google.errorprone.util.ASTHelpers.resolveExistingMethod(ASTHelpers.java:907)
  	at com.google.errorprone.bugpatterns.EqualsHashCode.matchClass(EqualsHashCode.java:90)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:629)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:71)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:89)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:43)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:650)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:144)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:52)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:68)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1277)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1226)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:840)
  	at com.sun.tools.javac.main.Main.compile(Main.java:257)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:230)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:108)
  	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:128)
  	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:70)
  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:497)
  	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:63)
  	at net.ltgt.gradle.errorprone.ErrorProneCompiler.execute(ErrorProneCompiler.java:25)
  	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
  	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
  	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
  	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
  	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
  	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:206)
  	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:187)
  	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:130)
  	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
  	at sun.reflect.GeneratedMethodAccessor608.invoke(Unknown Source)
  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.lang.reflect.Method.invoke(Method.java:497)
  	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:163)
  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
  	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
  	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
  	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
  	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
  	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
  	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
  	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
  	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
  	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
  	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
  	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
  	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
  	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
  	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
  	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
  	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
  	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  	at java.lang.Thread.run(Thread.java:745)
1 error

**Comment by eaftan** [comment]
@nglorioso, the stack trace implicates EqualsHashCode.  Have you seen this before?

@liutikas, could you provide repro instructions?

**Comment by reggert** [comment]
I'm seeing the same problem with ErrorProne 2.0.15 and 2.0.19, using OpenJDK 1.8.0_121. The only workaround I've come up with so far is to disable ErrorProne altogether, as it is preventing the build from proceeding.

**Comment by cushon** [comment]
Do you have code you can share that reproduces the crash?

**Comment by reggert** [comment]
None that I can share.
I don't know if it's relevant, but the exception is occurring while processing a generic class with two type parameters that is used as a base class for two other classes. The base class implements `hashCode` and `equals`, but the subclasses do not override them (they add no fields, so the base class behavior, which includes checking the classes, is sufficient).

**Comment by cushon** [comment]
> The only workaround I've come up with so far is to disable ErrorProne altogether

It should be possible to disable just the check that is crashing with `-Xep:EqualsHashCode:OFF`.

And if you're able to create a minimal redacted example of code that causes that crash, that would be very helpful.

**Comment by reggert** [comment]
Unfortunately, the code in question is very complex, with multiple nested classes, some of which are passed as type parameters to each other. I haven't been able to reproduce the problem in simplified form.

**Comment by iignatev** [comment]
I see similar NPE running error-prone for OpenJDK 12:
```
src/java.base/share/classes/java/security/BasicPermission.java:68: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
public abstract class BasicPermission extends Permission
                ^
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.3.2-SNAPSHOT
     BugPattern: EqualsHashCode
     Stack Trace:
     java.lang.NullPointerException
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve$AbstractMethodCheck.treeForDiagnostics(Resolve.java:798)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve$AbstractMethodCheck.argumentsAcceptable(Resolve.java:758)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve$4.argumentsAcceptable(Resolve.java:894)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:616)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1561)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1731)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1800)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1774)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve$10.doLookup(Resolve.java:2652)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3291)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3541)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve.resolveQualifiedMethod(Resolve.java:2649)
        at jdk.compiler.interim/com.sun.tools.javac.comp.Resolve.resolveInternalMethod(Resolve.java:2731)
        at com.google.errorprone.util.ASTHelpers.resolveExistingMethod(ASTHelpers.java:1070)
        at com.google.errorprone.bugpatterns.EqualsHashCode.matchClass(EqualsHashCode.java:102)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:582)
        at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
        at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
        at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
        at jdk.compiler.interim/com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
        at jdk.compiler.interim/com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
        at jdk.compiler.interim/com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:603)
        at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
        at jdk.compiler.interim/com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
        at jdk.compiler.interim/com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
        at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
        at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:43)
        at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:152)
        at jdk.compiler.interim/com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:132)
        at jdk.compiler.interim/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1418)
        at jdk.compiler.interim/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1365)
        at jdk.compiler.interim/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:966)
        at jdk.compiler.interim/com.sun.tools.javac.main.Main.compile(Main.java:311)
        at jdk.compiler.interim/com.sun.tools.javac.main.Main.compile(Main.java:170)
        at jdk.compiler.interim/com.sun.tools.javac.Main.compile(Main.java:57)
        at jdk.compiler.interim/com.sun.tools.javac.Main.main(Main.java:43)
1 error
```

**Comment by cushon** [comment]
@iignatev does passing `-XDcompilePolicy=simple` to javac make a difference?

If not, is it possible to share a self-contained repro?

**Comment by iignatev** [comment]
I ain't able to reproduce this NPE w/ `-XDcompilePolicy=simple`

**Comment by cushon** [comment]
> I ain't able to reproduce this NPE w/ `-XDcompilePolicy=simple`.

Thanks for checking. That indicates the crash is related to [`JDK-8155674`](https://bugs.openjdk.java.net/browse/JDK-8155674). Error Prone expects to run over compilation units after they are analyzed and prior to any desugaring, and the bug prevents that from happening when using the 'by-file' policy in certain situations.

Using `-XDcompilePolicy=simple` is probably a fine work-around. It might slightly increase javac's memory usage, though.

**Comment by cushon** [comment]
(See also google/error-prone#781)

**Comment by cushon** [comment]
Ah, OK. I hadn't looked at the performance of `-XDcompilePolicy=simple` carefully. We're using a fix for the bug I mentioned so we can use the `by-file` policy, and we also aren't that sensitive to how much memory javac uses. This is a good reminder that I should upstream that fix.

**Comment by iignatev** [comment]
It appears to be a memory leak in javac —
https://bugs.openjdk.java.net/browse/JDK-8209055

Cheers,
- Igor
