### ISSUE TITLE
Cannot use output directories ending in `.java` with 2.0.19

### ISSUE THREAD

**Issue by cheister** [google/error-prone#583]
The new [command line parsing code in 2.0.19](https://github.com/google/error-prone/blob/master/check_api/src/main/java/com/google/errorprone/BaseErrorProneCompiler.java#L101) doesn't work if the directory your running in happens to end with `.java` because the path given to the `-d` argument is interpreted as a java file to be compiled.

We fixed this by renaming the problem directory but I thought it was worth filing an issue in case there is a more robust way to parse the arguments.

The stacktrace for the error was

```
java.lang.IllegalArgumentException: directories not supported
  at com.sun.tools.javac.file.PathFileObject.<init>(PathFileObject.java:336)
  at com.sun.tools.javac.file.PathFileObject$SimpleFileObject.<init>(PathFileObject.java:280)
  at com.sun.tools.javac.file.PathFileObject$SimpleFileObject.<init>(PathFileObject.java:277)
  at com.sun.tools.javac.file.PathFileObject.forSimplePath(PathFileObject.java:274)
  at com.sun.tools.javac.file.JavacFileManager.getJavaFileObjectsFromPaths(JavacFileManager.java:879)
  at com.sun.tools.javac.file.JavacFileManager.getJavaFileObjectsFromStrings(JavacFileManager.java:196)
  at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:111)
  at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:119)
  at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:66)
  at com.google.errorprone.ErrorProneCompiler.main(ErrorProneCompiler.java:45)
```

**Comment by trejkaz** [comment]
Out of pure curiosity, how on earth did you discover this?

**Comment by cushon** [comment]
The stack trace is using `BaseErrorProneCompiler`--with the new preferred `-Xplugin:` integration (see http://errorprone.info/installation) Error Prone doesn't change javac's handling of `-d`, you should be able to use whatever style of output directories `javac` supports.
