### ISSUE TITLE
It looks like lombok component annotation not supported

### ISSUE THREAD

**Issue by sophea** [google/error-prone#589]
`:appengineDownloadSdk
:compileJava
java.lang.ClassCastException: lombok.javac.apt.Javac7BaseFileObjectWrapper cannot be cast to javax.tools.FileObject
> Buildiat javax.tools.ForwardingFileObject.<init>(ForwardingFileObject.java:57)
	at com.sun.tools.javac.processing.JavacFiler$FilerOutputFileObject.<init>(JavacFiler.java:120)
	at com.sun.tools.javac.processing.JavacFiler$FilerOutputJavaFileObject.<init>(JavacFiler.java:165)
	at com.sun.tools.javac.processing.JavacFiler.createSourceOrClassFile(JavacFiler.java:426)
	at com.sun.tools.javac.processing.JavacFiler.createSourceFile(JavacFiler.java:388)
	at lombok.javac.apt.LombokProcessor.forceNewRound(LombokProcessor.java:291)
	at lombok.javac.apt.LombokProcessor.process(LombokProcessor.java:281)
	at lombok.core.AnnotationProcessor$JavacDescriptor.process(AnnotationProcessor.java:115)
	at lombok.core.AnnotationProcessor.process(AnnotationProcessor.java:165)
	at lombok.launch.AnnotationProcessorHider$AnnotationProcessor.process(AnnotationProcessor.java:58)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:826)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:742)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2000(JavacProcessingEnvironment.java:100)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Ro`

**Comment by cushon** [comment]
Which versions of Error Prone and Lombok are you using?

Do you have a self-contained example that demonstrates the problem?

**Comment by sophea** [comment]
classpath 'net.ltgt.gradle:gradle-errorprone-plugin:0.0.8'

configurations.errorprone {
    resolutionStrategy.force(
        'com.google.errorprone:error_prone_core:2.0.19'
   )
}

Here is my Domain java object. We use fully lombox jar @Getter/@Setter annotation
``
import java.util.Date;

import javax.persistence.Basic;

import lombok.Getter;
import lombok.Setter;

import com.fasterxml.jackson.annotation.JsonIgnore;
@Getter
@Setter
public class DArchiveImageProfile extends AbstractLongDomainEntity {
    
    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private Long id;
    private Long userId;
    private String imageUrlProfile;
    /**transient, just view only it is default image profile or not*/
    private Boolean defaultImage;
    /**created date*/
    @Basic
    @JsonIgnore
    private Date createdDate;
    
    public String getImageUrlProfile() {
        return imageUrlProfile != null && imageUrlProfile.startsWith("http://") ? imageUrlProfile.replace("http:", "https:") : imageUrlProfile;
    }
}
``

**Comment by sophea** [comment]
lombok {
    version = "1.16.8"
    sha256 = "fe32b29b7b33eb2b19866cbc5345c59c9984a6036cc396856a04c0d09f99ea68"
}

**Comment by davidburstromspotify** [comment]
It appears that simply having Lombok on the classpath causes the same problem. Tried with Lombok 1.16.12 and ErrorProne 2.1.1.

**Comment by nallar** [comment]
@davidburstromspotify Is it still broken with lombok 1.16.18?

[lombok's release notes indicate that it now works with error-prone](https://github.com/rzwitserloot/lombok/blob/master/doc/changelog.markdown#v11618-july-3rd-2017), so this issue may be fixed.

**Comment by davidburstromspotify** [comment]
Unfortunately I do not have sample code in which I can test that hypothesis, but it does indeed look promising.

**Comment by cushon** [comment]
There are still known issues with the interaction between lombok and error prone, but the issue reported in this bug should be fixed.
