### ISSUE TITLE
unhandled exception error_prone

### ISSUE THREAD

**Issue by daniv** [google/error-prone#622]
`
Error:(261, 107) java: incompatible types: java.util.concurrent.atomic.AtomicReference<java.lang.Object> cannot be converted to org.joda.time.ReadablePeriod

Error:(261, 105) java: An unhandled exception was thrown by the Error Prone static analysis plugin.
     Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
     error-prone version: 2.0.9
     Stack Trace:
     java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$ClassSymbol cannot be cast to com.sun.tools.javac.code.Symbol$MethodSymbol
  	at com.google.errorprone.bugpatterns.CompileTimeConstantChecker.matchMethodInvocation(CompileTimeConstantChecker.java:170)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:826)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1614)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitNewClass(TreeScanner.java:526)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:862)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitNewClass(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1675)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitMethodInvocation(TreeScanner.java:510)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:829)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1614)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
  	at com.sun.source.util.TreeScanner.visitReturn(TreeScanner.java:470)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:909)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitReturn(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1518)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:249)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:546)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:996)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:207)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:818)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:868)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:91)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:188)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:590)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:778)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:72)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:91)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1050)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:146)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:106)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:114)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:145)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:601)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:561)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:53)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:70)
  	at com.google.errorprone.scanner.ErrorProneScanner.scan(ErrorProneScanner.java:1036)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:45)
  	at com.google.errorprone.ErrorProneAnalyzer.reportReadyForAnalysis(ErrorProneAnalyzer.java:172)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:115)
  	at com.google.errorprone.ErrorProneJavacJavaCompiler.postFlow(ErrorProneJavacJavaCompiler.java:109)
  	at com.google.errorprone.ErrorProneJavacJavaCompiler.flow(ErrorProneJavacJavaCompiler.java:93)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1257)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:865)
  	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:97)
  	at com.sun.tools.javac.api.JavacTaskImpl$1.call(JavacTaskImpl.java:93)
  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:128)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:93)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:87)
  	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:185)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:475)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:331)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:249)
  	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:213)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1263)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:940)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:1012)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:903)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:736)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:384)
  	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:192)
  	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:138)
  	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:295)
  	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:125)
  	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler.lambda$channelRead0$0(BuildMain.java:236)
  	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl.lambda$executeOnPooledThread$0(SharedThreadPoolImpl.java:42)
  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  	at java.lang.Thread.run(Thread.java:745)
`

not using any AtomicReference but just JodaTimeFuntions:

```
long uptime = ManagementFactory.getRuntimeMXBean().getUptime();
long now = System.currentTimeMillis();
org.joda.time.Period period = new Period( uptime );
String s = org.joda.time.format.PeriodFormat.wordBased().print( period )
```

**Comment by cushon** [comment]
This is fixed in version 2.0.13, see #459.

**Comment by daniv** [comment]
wow...fast response!!
however i am using 
 <com.google.errorprone.version>2.0.19</com.google.errorprone.version>
which is the latest version......

**Comment by JakeWharton** [comment]
The trace indicates 2.0.9 not .19

**Comment by daniv** [comment]
you defiantly right.
but something very interesting:
accidentally i included in my pom 
`<artifactId>error_prone_annotations</artifactId>`
`<version>2.0.19</version>`

and i didn't include the  <artifactId>error_prone_core</artifactId> core wich also brings annotations.
i could not find core on my classpath, so is a mysterious now, that it was working and no warnings. also don't know why my IDEA picked that specific version ( maybe the Error-prone compiler integration plugin? )

in my Compiler -> Java Compiler the compiler option is = Javac with error prone.

anyway, after fixed my pom setting ( core instead of annotations ) the issue didn't come back.

thanx
