### ISSUE TITLE
NoSuchElementException - NamedParameterChecker.matchNewClassOrMethodInvocation

### ISSUE THREAD

**Issue by don-vip** [google/error-prone#633]
error_prone_ant 2.0.20-20170524.215422-21

```
compile:
    [javac] Compiling 376 source files to /var/lib/jenkins/jobs/JOSM/workspace/jdk/JDK8/build
    [javac] Note: /var/lib/jenkins/jobs/JOSM/workspace/jdk/JDK8/src/oauth/signpost/AbstractOAuthProvider.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] Compiling 54 source files to /var/lib/jenkins/jobs/JOSM/workspace/jdk/JDK8/build
    [javac] Compiling 1493 source files to /var/lib/jenkins/jobs/JOSM/workspace/jdk/JDK8/build
    [javac] /var/lib/jenkins/jobs/JOSM/workspace/jdk/JDK8/src/org/openstreetmap/josm/gui/layer/OsmDataLayer.java:1070: warning: [NamedParameters] Parameters with incorrectly labelled arguments: title (missing name label)
    [javac]             ExtendedDialog dialog = new ExtendedDialog(
    [javac]                                     ^
    [javac]     (see http://errorprone.info/bugpattern/NamedParameters)
    [javac]   Did you mean '/*title=*/'?
    [javac] /var/lib/jenkins/jobs/JOSM/workspace/jdk/JDK8/src/org/openstreetmap/josm/data/UndoRedoHandler.java:164: warning: [deprecation] fireSelectionChanged() in DataSet has been deprecated
    [javac]             ds.fireSelectionChanged();
    [javac]               ^
    [javac] /var/lib/jenkins/jobs/JOSM/workspace/jdk/JDK8/src/org/openstreetmap/josm/gui/MainMenu.java:367: warning: [NamedParameters] Parameters with incorrectly labelled arguments: name (missing name label)
    [javac]     public final ImageryMenu imageryMenu = addMenu(new ImageryMenu(imagerySubMenu), /* untranslated name */ "Imagery", KeyEvent.VK_I, 8, ht("/Menu/Imagery"));
    [javac]                                                   ^
    [javac]     (see http://errorprone.info/bugpattern/NamedParameters)
    [javac]   Did you mean 'public final ImageryMenu imageryMenu = addMenu(new ImageryMenu(imagerySubMenu), /*name=*/ "Imagery", KeyEvent.VK_I, 8, ht("/Menu/Imagery"));'?
    [javac] /var/lib/jenkins/jobs/JOSM/workspace/jdk/JDK8/src/org/openstreetmap/josm/tools/Shortcut.java:459: error: An unhandled exception was thrown by the Error Prone static analysis plugin.
    [javac]             sc.setLongText(longText); // or set by the platformHook, in this case the original longText doesn't match the real action
    [javac]                           ^
    [javac]      Please report this at https://github.com/google/error-prone/issues/new and include the following:
    [javac]   
    [javac]      error-prone version: 2.0.20-SNAPSHOT
    [javac]      Stack Trace:
    [javac]      java.util.NoSuchElementException: No value present
    [javac]   	at java.util.Optional.get(Optional.java:135)
    [javac]   	at com.google.errorprone.bugpatterns.argumentselectiondefects.NamedParameterChecker.matchNewClassOrMethodInvocation(NamedParameterChecker.java:139)
    [javac]   	at com.google.errorprone.bugpatterns.argumentselectiondefects.NamedParameterChecker.matchMethodInvocation(NamedParameterChecker.java:76)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:904)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:145)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1644)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
    [javac]   	at com.sun.source.util.TreeScanner.visitExpressionStatement(TreeScanner.java:433)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:710)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitExpressionStatement(ErrorProneScanner.java:145)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1454)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
    [javac]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
    [javac]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:527)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:145)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
    [javac]   	at com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:419)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:755)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:145)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1427)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
    [javac]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
    [javac]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:527)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:145)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
    [javac]   	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:895)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:145)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
    [javac]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
    [javac]   	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:587)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:145)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
    [javac]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
    [javac]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
    [javac]   	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:602)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:145)
    [javac]   	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
    [javac]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
    [javac]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
    [javac]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:41)
    [javac]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
    [javac]   	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
    [javac]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1425)
    [javac]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1374)
    [javac]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
    [javac]   	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
    [javac]   	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
    [javac]   	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
    [javac]   	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
    [javac]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:137)
    [javac]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:108)
    [javac]   	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:118)
    [javac]   	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:65)
    [javac]   	at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:39)
    [javac]   	at com.google.errorprone.ErrorProneAntCompilerAdapter$AntRunner.apply(ErrorProneAntCompilerAdapter.java:36)
    [javac]   	at com.google.errorprone.ErrorProneAntCompilerAdapter.execute(ErrorProneAntCompilerAdapter.java:73)
    [javac]   	at org.apache.tools.ant.taskdefs.Javac.compile(Javac.java:1344)
    [javac]   	at org.apache.tools.ant.taskdefs.Javac.execute(Javac.java:1070)
    [javac]   	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
    [javac]   	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    [javac]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [javac]   	at java.lang.reflect.Method.invoke(Method.java:498)
    [javac]   	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
    [javac]   	at org.apache.tools.ant.Task.perform(Task.java:348)
    [javac]   	at org.apache.tools.ant.Target.execute(Target.java:435)
    [javac]   	at org.apache.tools.ant.Target.performTasks(Target.java:456)
    [javac]   	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1405)
    [javac]   	at org.apache.tools.ant.Project.executeTarget(Project.java:1376)
    [javac]   	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
    [javac]   	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
    [javac]   	at org.apache.tools.ant.Main.runBuild(Main.java:854)
    [javac]   	at org.apache.tools.ant.Main.startAnt(Main.java:236)
    [javac]   	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:285)
    [javac]   	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:112)
    [javac] 1 error
```

**Comment by don-vip** [comment]
The error no longer occurs with 2.0.21. Seems to have been fixed by one of these two commits:
https://github.com/google/error-prone/commit/96f1ed68df4d9085f60f62214008dfe67df92089
https://github.com/google/error-prone/commit/77714225f5a7db282c75751dee91eabc2606c203

**Comment by eaftan** [comment]
Thanks for looking into this.

**Comment by don-vip** [comment]
You're welcome. I'm not sure about #634, if the test I suggested is worth to add, or if the new tests cover my original use case.
