### ISSUE TITLE
running ant jar fails with java.lang.NoSuchFieldError on master and 2.0.20

### ISSUE THREAD

**Issue by msridhar** [google/error-prone#653]
I built master from source, and then tried using the ant jar to compile a trivial class:

```
java -cp ant/target/error_prone_ant-2.0.21-SNAPSHOT.jar com.google.errorprone.ErrorProneCompiler Foo.java
```

This fails when run on JDK 1.8.0_121:
```
Exception in thread "main" java.lang.NoSuchFieldError: ANNOTATION_PROCESSOR_MODULE_PATH
	at com.sun.tools.javac.file.Locations.initHandlers(Locations.java:1814)
	at com.sun.tools.javac.file.Locations.<init>(Locations.java:141)
	at com.sun.tools.javac.file.BaseFileManager.createLocations(BaseFileManager.java:115)
	at com.sun.tools.javac.file.BaseFileManager.<init>(BaseFileManager.java:76)
	at com.sun.tools.javac.file.JavacFileManager.<init>(JavacFileManager.java:147)
	at com.google.errorprone.MaskedClassLoader$MaskedFileManager.<init>(MaskedClassLoader.java:67)
	at com.google.errorprone.MaskedClassLoader$MaskedFileManager.<init>(MaskedClassLoader.java:71)
	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:107)
	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:118)
	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:65)
	at com.google.errorprone.ErrorProneCompiler.main(ErrorProneCompiler.java:44)
```

[That field exists](https://github.com/google/error-prone-javac/blob/upstream/src/java.compiler/share/classes/javax/tools/StandardLocation.java#L70) in the version of `javax.tools.StandardLocation` compiled into the ant jar.  But, `javax.tools.StandardLocation` is also present in the JDK 1.8.0_121 `rt.jar`, and the version in `rt.jar` is missing the field.  The version in `rt.jar` "wins" since it's on the boot classpath.

**Comment by eaftan** [comment]
Can you try setting the bootclasspath as described in http://errorprone.info/docs/installation#command-line?

**Comment by msridhar** [comment]
Yeah that fixes it.  Sorry to miss that; the ant jar seemed to work on JDK 8 without hacking the bootclasspath before now.  Thanks!

**Comment by eaftan** [comment]
I think this surfaced because the v2.0.20 uses an updated javac 9 which has diverged farther from the Java 8 types.  I believe v2.0.19 still used a non-modulized javac.
