### ISSUE TITLE
NullPointerException in InstanceOfAndCastMatchWrongType

### ISSUE THREAD

**Issue by CodingFabian** [google/error-prone#662]
Failure location is:
[48,34] in the following snippet:

```
      if (arguments.length > index) {
        StringBuilder stringBuilder = new StringBuilder().append('[');
        boolean first = true;
        for (; index < arguments.length; index++) {
          if (arguments[index] instanceof Object[]) {
            for (Object value : ((Object[]) arguments[index])) {
              if (first) {
                first = false;
              } else {
                stringBuilder.append(", ");
              }
              stringBuilder.append(value);
            }
          } else {
            if (first) {
              first = false;
            } else {
              stringBuilder.append(", ");
            }
            stringBuilder.append(arguments[index]);
          }
        }
      }
```
line 48 is "            for (Object value : ((Object[]) arguments[index])) {"

```
[ERROR]      error-prone version: 2.0.20
[ERROR]      Stack Trace:
[ERROR]      java.lang.NullPointerException
[ERROR]   	at com.google.errorprone.bugpatterns.InstanceOfAndCastMatchWrongType$TreeScannerInstanceOfWrongType.visitInstanceOf(InstanceOfAndCastMatchWrongType.java:185)
[ERROR]   	at com.google.errorprone.bugpatterns.InstanceOfAndCastMatchWrongType$TreeScannerInstanceOfWrongType.visitInstanceOf(InstanceOfAndCastMatchWrongType.java:147)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCInstanceOf.accept(JCTree.java:2051)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:86)
[ERROR]   	at com.google.errorprone.bugpatterns.InstanceOfAndCastMatchWrongType$CastingMatcher.matches(InstanceOfAndCastMatchWrongType.java:103)
[ERROR]   	at com.google.errorprone.bugpatterns.InstanceOfAndCastMatchWrongType.matchTypeCast(InstanceOfAndCastMatchWrongType.java:68)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitTypeCast(ErrorProneScanner.java:1090)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitTypeCast(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCTypeCast.accept(JCTree.java:2022)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.visitParenthesized(TreeScanner.java:572)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitParenthesized(ErrorProneScanner.java:991)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitParenthesized(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCParens.accept(JCTree.java:1849)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.visitEnhancedForLoop(TreeScanner.java:305)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitEnhancedForLoop(ErrorProneScanner.java:696)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitEnhancedForLoop(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCEnhancedForLoop.accept(JCTree.java:1166)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:419)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:758)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1427)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.visitForLoop(TreeScanner.java:291)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitForLoop(ErrorProneScanner.java:728)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitForLoop(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCForLoop.accept(JCTree.java:1132)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:419)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:758)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1427)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.visitIf(TreeScanner.java:419)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:758)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitIf(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCIf.accept(JCTree.java:1427)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.visitBlock(TreeScanner.java:248)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:530)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitBlock(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1026)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.visitMethod(TreeScanner.java:206)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:898)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitMethod(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:898)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:90)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:590)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
[ERROR]   	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
[ERROR]   	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
[ERROR]   	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:605)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
[ERROR]   	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
[ERROR]   	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
[ERROR]   	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
[ERROR]   	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:41)
[ERROR]   	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
[ERROR]   	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1425)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1374)
[ERROR]   	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
[ERROR]   	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
[ERROR]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:137)
[ERROR]   	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:108)
[ERROR]   	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:118)
[ERROR]   	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:222)
[ERROR]   	at sun.reflect.GeneratedMethodAccessor472.invoke(Unknown Source)
[ERROR]   	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]   	at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]   	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
[ERROR]   	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:823)
[ERROR]   	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:129)
[ERROR]   	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]   	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]   	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]   	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
[ERROR]   	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
[ERROR]   	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR]   	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[ERROR]   	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ERROR]   	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ERROR]   	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ERROR]   	at java.lang.Thread.run(Thread.java:745)
```

**Comment by CodingFabian** [comment]
This error is new in 2.0.20 (2.0.19 worked)
and can be worked around by writing
```
          Object arg = arguments[index];
          if (arg instanceof Object[]) {
            for (Object value : ((Object[]) arg)) {
```

**Comment by CodingFabian** [comment]
looks like I was too slow and this is #651

**Comment by CodingFabian** [comment]
yeah confirmed fix by https://github.com/google/error-prone/commit/652f09c2dee4bd836b93f25e8119ffece64e332b
