### ISSUE TITLE
An unhandled exception was thrown by the Error Prone static analysis plugin with 2.0.21 and some lambdas

### ISSUE THREAD

**Issue by cheister** [google/error-prone#673]
We updated from 2.0.19 to 2.0.21 and started getting an NPE for two different pieces of code that used lambdas.  

The following snippet

```java
private FakeShardedJobQueue<String> queue = new FakeShardedJobQueue.Builder<String>()
      .clock(clock)
      .handler(handler)
      .transactionalEnqueuer((shardingKey, hook) -> hooks.put(shardingKey, hook))
      .build();
```

gave the error:

```
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
   .transactionalEnqueuer((shardingKey, hook) -> hooks.put(shardingKey, hook))
                                                          ^
  Please report this at https://github.com/google/error-prone/issues/new and include the following:

  error-prone version: 2.0.21
  Stack Trace:
  java.lang.NullPointerException
at com.google.errorprone.matchers.IsLastStatementInBlock.matches(IsLastStatementInBlock.java:31)
at com.google.errorprone.matchers.IsLastStatementInBlock.matches(IsLastStatementInBlock.java:25)
at com.google.errorprone.matchers.Matchers$4.matches(Matchers.java:127)
at com.google.errorprone.matchers.Matchers$5.matches(Matchers.java:146)
at com.google.errorprone.bugpatterns.AbstractReturnValueIgnored.expectedExceptionTest(AbstractReturnValueIgnored.java:163)
at com.google.errorprone.matchers.Matchers$3.matches(Matchers.java:112)
at com.google.errorprone.matchers.Matchers$4.matches(Matchers.java:127)
at com.google.errorprone.bugpatterns.AbstractReturnValueIgnored.matchMethodInvocation(AbstractReturnValueIgnored.java:80)
at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:907)
at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:146)
```

**Comment by Stephan202** [comment]
This is #657; a fix has been committed but not yet released.
