### ISSUE TITLE
java.lang.invoke.LambdaConversionException - interface conversion problem

### ISSUE THREAD

**Issue by ejbartelds** [google/error-prone#683]
The exception and callstack are somewhat similar to what's reported in https://github.com/google/error-prone/issues/525 but I'm not sure it is actually the same kind of problem, with the same kind of solution.

This is a Maven 3.3.3 project running error-prone 2.0.21, built on Bamboo 1.6.160 using JDK 1.8.0_92

```
build	17-Jul-2017 08:22:12	     error-prone version: 2.0.21
build	17-Jul-2017 08:22:12	     Stack Trace:
build	17-Jul-2017 08:22:12	     java.lang.BootstrapMethodError: call site initialization exception
build	17-Jul-2017 08:22:12	  	at java.lang.invoke.CallSite.makeSite(CallSite.java:328)
build	17-Jul-2017 08:22:12	  	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:296)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.bugpatterns.UngroupedOverloads$MethodFixSuggester.getFirstOccurrences(UngroupedOverloads.java:413)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.bugpatterns.UngroupedOverloads$MethodFixSuggester.buildMethodDescription(UngroupedOverloads.java:385)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.bugpatterns.UngroupedOverloads$MethodFixSuggester.buildAdaptedDescription(UngroupedOverloads.java:378)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.bugpatterns.UngroupedOverloads$MethodFixSuggester.describeFix(UngroupedOverloads.java:358)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.bugpatterns.UngroupedOverloads.matchClass(UngroupedOverloads.java:95)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:584)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
build	17-Jul-2017 08:22:12	  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
build	17-Jul-2017 08:22:12	  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
build	17-Jul-2017 08:22:12	  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
build	17-Jul-2017 08:22:12	  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:605)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
build	17-Jul-2017 08:22:12	  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:41)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1425)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1374)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.api.JavacTaskImpl$$Lambda$18/704482919.call(Unknown Source)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
build	17-Jul-2017 08:22:12	  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:137)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:108)
build	17-Jul-2017 08:22:12	  	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:118)
build	17-Jul-2017 08:22:12	  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne$CompilerInvoker.compile(JavacCompilerWithErrorProne.java:222)
build	17-Jul-2017 08:22:12	  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
build	17-Jul-2017 08:22:12	  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
build	17-Jul-2017 08:22:12	  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
build	17-Jul-2017 08:22:12	  	at java.lang.reflect.Method.invoke(Method.java:483)
build	17-Jul-2017 08:22:12	  	at org.codehaus.plexus.compiler.javac.errorprone.JavacCompilerWithErrorProne.performCompile(JavacCompilerWithErrorProne.java:91)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:943)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:137)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
build	17-Jul-2017 08:22:12	  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
build	17-Jul-2017 08:22:12	  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
build	17-Jul-2017 08:22:12	  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
build	17-Jul-2017 08:22:12	  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
build	17-Jul-2017 08:22:12	  	at java.lang.reflect.Method.invoke(Method.java:483)
build	17-Jul-2017 08:22:12	  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
build	17-Jul-2017 08:22:12	  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
build	17-Jul-2017 08:22:12	  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
build	17-Jul-2017 08:22:12	  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
build	17-Jul-2017 08:22:12	  Caused by: java.lang.invoke.LambdaConversionException: Type mismatch for lambda argument 1: interface javax.lang.model.element.Name is not convertible to interface javax.lang.model.element.Name
build	17-Jul-2017 08:22:12	  	at java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:267)
build	17-Jul-2017 08:22:12	  	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)
build	17-Jul-2017 08:22:12	  	at java.lang.invoke.CallSite.makeSite(CallSite.java:289)
build	17-Jul-2017 08:22:12	  	... 64 more
```

**Comment by ejbartelds** [comment]
I'll try upgrading JDK version to see what happens

**Comment by ejbartelds** [comment]
My mistake: the stack trace I reported occurred on 1.8.0_28 not 1.8.0_92 as I reported :-(

When run on 1.8.0_92 the error does not occur.
