### ISSUE TITLE
CanonicalDuration does not handle static imports of joda Duration methods

### ISSUE THREAD

**Issue by cheister** [google/error-prone#791]
The stacktrace for the error is 

```
error: An unhandled exception was thrown by the Error Prone static analysis plugin.
  static final Duration PROCESS_EXPIRATION = standardSeconds(120);
                                                             ^
      Please report this at https://github.com/google/error-prone/issues/new and include the following:
  
      error-prone version: 2.1.2
      Stack Trace:
      java.lang.NullPointerException
  	at com.google.errorprone.VisitorState.getEndPosition(VisitorState.java:353)
  	at com.google.errorprone.bugpatterns.CanonicalDuration.matchMethodInvocation(CanonicalDuration.java:165)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:907)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitMethodInvocation(ErrorProneScanner.java:146)
```

The code that fails is 

```
import static org.joda.time.Duration.standardSeconds;

public class Monitor {
  static final Duration PROCESS_EXPIRATION = standardSeconds(120);
```

The following testcase should reproduce the problem.

```
  @Test
  public void refactoringJodaStaticImport() throws Exception {
    BugCheckerRefactoringTestHelper.newInstance(new CanonicalDuration(), getClass())
        .addInputLines(
            "in/A.java", //
            "package a;",
            "import org.joda.time.Duration;",
            "import static org.joda.time.Duration.standardDays;",
            "import static org.joda.time.Duration.standardMinutes;",
            "import static org.joda.time.Duration.standardSeconds;",
            "public class A {",
            "  static final int CONST = 86400;",
            "  {",
            "    standardSeconds(86400);",
            "    org.joda.time.Duration.standardSeconds(86400);",
            "    standardSeconds(CONST);",
            "    Duration zero = standardSeconds(0);",
            "    standardDays(1);",
            "  }",
            "}")
        .addOutputLines(
            "out/A.java", //
            "package a;",
            "import org.joda.time.Duration;",
            "import static org.joda.time.Duration.standardDays;",
            "import static org.joda.time.Duration.standardMinutes;",
            "import static org.joda.time.Duration.standardSeconds;",
            "public class A {",
            "  static final int CONST = 86400;",
            "  {",
            "    standardDays(1);",
            "    org.joda.time.Duration.standardDays(1);",
            "    standardSeconds(CONST);",
            "    Duration zero = Duration.ZERO;",
            "    standardDays(1);",
            "  }",
            "}")
        .doTest(TEXT_MATCH);
  }
```

**Comment by eaftan** [comment]
Thanks for the excellent repro instructions and the test case!  I'll take a look at this.
