### ISSUE TITLE
FieldMissingNullable throws NullPointerException

### ISSUE THREAD

**Issue by andrewhabib** [google/error-prone#829]
Hi, 

I am using error-prone and found out that the check **FieldMissingNullable** throws nullpointer exception on many projects. 

I could isolate the problem by combining the two options: -XepAllDisabledChecksAsWarnings -Xep:FieldMissingNullable:OFF together; which no longer results in any exception. 

I am providing the stack trace as well.

     error-prone version: 2.1.1
     Stack Trace:
     java.lang.NullPointerException
  	at com.sun.tools.javac.code.Types.instance(Types.java:104)
  	at com.google.errorprone.dataflow.nullnesspropagation.NullnessPropagationTransfer.visitMethodInvocation(NullnessPropagationTransfer.java:485)
  	at com.google.errorprone.dataflow.nullnesspropagation.AbstractNullnessPropagationTransfer.visitMethodInvocation(AbstractNullnessPropagationTransfer.java:303)
  	at com.google.errorprone.dataflow.nullnesspropagation.AbstractNullnessPropagationTransfer.visitMethodInvocation(AbstractNullnessPropagationTransfer.java:126)
  	at org.checkerframework.dataflow.cfg.node.MethodInvocationNode.accept(MethodInvocationNode.java:79)
  	at org.checkerframework.dataflow.analysis.Analysis.callTransferFunction(Analysis.java:404)
  	at org.checkerframework.dataflow.analysis.Analysis.performAnalysis(Analysis.java:225)
  	at com.google.errorprone.dataflow.nullnesspropagation.TrustingNullnessAnalysis.getFieldInitializerNullness(TrustingNullnessAnalysis.java:115)
  	at com.google.errorprone.bugpatterns.nullness.FieldMissingNullable.matchVariable(FieldMissingNullable.java:89)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:1150)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitVariable(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCVariableDecl.accept(JCTree.java:968)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitClass(TreeScanner.java:187)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:590)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitClass(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:808)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:82)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:42)
  	at com.sun.source.util.TreeScanner.scan(TreeScanner.java:105)
  	at com.sun.source.util.TreeScanner.scanAndReduce(TreeScanner.java:113)
  	at com.sun.source.util.TreeScanner.visitCompilationUnit(TreeScanner.java:144)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:605)
  	at com.google.errorprone.scanner.ErrorProneScanner.visitCompilationUnit(ErrorProneScanner.java:146)
  	at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:591)
  	at com.sun.source.util.TreePathScanner.scan(TreePathScanner.java:56)
  	at com.google.errorprone.scanner.Scanner.scan(Scanner.java:64)
  	at com.google.errorprone.scanner.ErrorProneScannerTransformer.apply(ErrorProneScannerTransformer.java:41)
  	at com.google.errorprone.ErrorProneAnalyzer.finished(ErrorProneAnalyzer.java:145)
  	at com.sun.tools.javac.api.MultiTaskListener.finished(MultiTaskListener.java:120)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1425)
  	at com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1374)
  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:973)
  	at com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
  	at com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:137)
  	at com.google.errorprone.BaseErrorProneCompiler.run(BaseErrorProneCompiler.java:108)
  	at com.google.errorprone.ErrorProneCompiler.run(ErrorProneCompiler.java:118)
  	at com.google.errorprone.ErrorProneCompiler.compile(ErrorProneCompiler.java:65)
  	at com.google.errorprone.ErrorProneCompiler.main(ErrorProneCompiler.java:44)

**Comment by cushon** [comment]
See #708.
